### ISSUE TITLE
Force trip update

### ISSUE THREAD

**Issue by italoc** [flobz/psa_car_controller#119]
After 4 days my trip data is not updated, there is way to force trip data?

**Comment by flobz** [comment]
Look at #50

**Comment by italoc** [comment]
> Look at #50
> Also you can do a "wakeup" and after 1 minutes do a get vehicle status.
> The two url to call to do that are in the Readme

just tried but nothing change

**Comment by flobz** [comment]
Ok so it's #50
i close becauseiit's aa duplicate issue. 
Please look at already existing issues before opena new one.
