### ISSUE TITLE
customer_id is null

### ISSUE THREAD

**Issue by flash4it** [flobz/psa_car_controller#12]
when i try to start server-py it gives the following error:

 File "/home/pi/Desktop/psa_car_controller/MyPSACC.py", line 239, in on_mqtt_connect
    topics = [MQTT_RESP_TOPIC + self.customer_id + "/#"]
TypeError: can only concatenate str (not "NoneType") to str

because the custemer_id is null.

also from this other error
DEBUG :: refresh_remote_token: {'error': 'invalid_grant', 'error_description': 'grant is invalid'}
ERROR :: can't refresh_remote_token: {'error': 'invalid_grant', 'error_description': 'grant is invalid'}

thanks

**Comment by flobz** [comment]
Hello,
Is the customer id present in the config file ?

**Comment by flash4it** [comment]
> Hello,
> Is the customer id present in the config file ?


In the test.json file it is present but initialized to null 
  "customer_id": null,
also the  remote_refresh_token is null
 "remote_refresh_token": null

**Comment by flobz** [comment]
the problem come from the extraction of credentials with the app_decoder script, this script have probably failed.

**Comment by flash4it** [comment]
> the problem come from the extraction of credentials with the app_decoder script, this script has probably failed.

I tried the script with app version 1.25.0, 1.26.3, 1.27 but the test.json file is the same is there anything else I can try?

**Comment by flobz** [comment]
what command did you use ?

**Comment by flash4it** [comment]
> what command did you use ?

This is the command for version 1.27 of the mypeugeot app

python3 app_decoder.py com.psa.mym.mypeugeot_1.27.0-2103_minAPI24_apkmirror.com.apk

**Comment by flobz** [comment]
Ok you choose solution 2, so you need to start the app with the correct parameter, it's indicate in the readme

**Comment by flash4it** [comment]
> Ok you choose solution 2, so you need to start the app with the correct parameter, it's indicate in the readme

I have already used solution 2 this is what it gives me back.
python3 app_decoder.py /home/pi/Desktop/psa_car_controller/com.psa.mym.mypeugeot_1.27.0-2103_minAPI24_apkmirror.com.apk 
Requested API level 29 is larger than maximum we have, returning API level 28 instead.
mypeugeot email: mycoount
mypeugeot password: mypassoword
What is the car api realm : clientsB2CPeugeot, clientsB2CCitroen, clientsB2CDS, clientsB2COpel, clientsB2CVauxhall
clientsB2CPeugeot

Your vehicles: {'VINNUBMER': {'id': 'vehicule id'}}

the vin and id data are filled in correctly the vin value is correct but both customer_id and remote_refresh_token are null

**Comment by flobz** [comment]
start the app:

if you choose solution 1 : python3 server.py -f test.json -c charge_config1.json

if you choose solution 2 : python3 server.py -f test.json --remote-disable

**Comment by flash4it** [comment]
> python3 server.py -f test.json --remote-disable


thanks now i was able to see the values ​​it was not clear how the remote-disable command works

**Comment by flobz** [comment]
ok
