### ISSUE TITLE
[New Car model] Peugeot new 2008 p24

### ISSUE THREAD

**Issue by riddik14** [flobz/psa_car_controller#123]
Information to add my car model to the app:
What is your country code ? (ex: FR, GB, DE, ES...) IT (work for IT?)
Brand: Peugeot
Model: 2008 allure pack 3d nav
First ten letter of my VIN: VR3USHNSKM
engine 1.2 130hp
Useable Electric capacity in kw: no- gasoline
Fuel capacity in liter: 44

**Comment by flobz** [comment]
done with 29ebd01.
Thanks
