### ISSUE TITLE
Invalid voltage

### ISSUE THREAD

**Issue by user-e** [flobz/psa_car_controller#124]
Hello, 
I've installed your last [commit](https://github.com/flobz/psa_car_controller/commit/8ccb46a00c82adcbbb4562e11539a85764cd8b70) and i'm getting the data fro my Corsa-e, anyway seems that the 
 battery voltage never change even with different battery percentage:

> "battery": {
    "current": 0,
    "voltage": 84.5
  },
  "doors_state": null,
  "energy": [
    {
      "updated_at": "2021-05-14 18:01:24+00:00",
      "autonomy": 110,
      "battery": null,
      "charging": {
        "charging_mode": "No",
        "charging_rate": 0,
        "next_delayed_time": "PT1H",
        "plugged": false,
        "remaining_time": null,
        "status": "Disconnected"
      },
      "consumption": null,
      "level": 45,
      "residual": null,
      "type": "Electric"
    }

it's always 84.5, and seems a strange voltage too...
I got 84.5 even with a percentage of 73%

**Comment by flobz** [comment]
It's a percentage of the voltage. 
The real voltage is about 400v

**Comment by flobz** [comment]
Anyway it's not an issue. It's data provided by psa.

**Comment by HenningS81** [comment]
I think the assumption, that the battery voltage is corresponding to the high voltage battery is wrong. I think it is rather the 12 V battery. I seem to have a problem with that. And if I compare the data of the last two days, the voltage rises, whenever I drive. But if the car parks it's going downhill:
![Bild_2023-11-19_145003436](https://github.com/flobz/psa_car_controller/assets/43236351/879d0703-31cd-47b5-a8bc-2c35ec9eb1ad)
Battery voltage in the upper half, driven kilometers in the lower
