### ISSUE TITLE
error label unknow

### ISSUE THREAD

**Issue by riddik14** [flobz/psa_car_controller#125]
(.env) psa_remote@raspberry:/usr/local/src/psa_car_controller $ python3 app_decoder.py ~/peugeot128.apk
APK loading...
Requested API level 29 is larger than maximum we have, returning API level 28 instead.
RES_TABLE_LIBRARY_TYPE chunk is not supported
RES_TABLE_LIBRARY_TYPE chunk is not supported
APK loaded !
MyPeugeot email: mymail@icloud.com
MyPeugeot password: 
What is your country code ? (ex: FR, GB, DE, ES...)
IT
Warning: Can't get car model please check cars.json
Traceback (most recent call last):
  File "app_decoder.py", line 129, in <module>
    if "short_label" in vehicle and car.label == "unknown":
AttributeError: 'NoneType' object has no attribute 'label'

**Comment by cstueckrath** [comment]
have you tried app version 1.27?

**Comment by riddik14** [comment]
I have try with 1.27, 1.28 and 1.29

**Comment by flobz** [comment]
can you retry with the last version ?

**Comment by riddik14** [comment]
Resolved. I had two vehicles connected to my account. removed one works. so for two vehicles it takes 2 accounts.

thank you. you can close

**Comment by flobz** [comment]
should be fixed with 06d7c84e20ccf5cbe709664d09d0de4a5c158b68
