### ISSUE TITLE
[New Car model] Citroen e-C4

### ISSUE THREAD

**Issue by MasterAndi** [flobz/psa_car_controller#126]
I have a "Can't get car model" error.
Information to add my car model to the app:
- Brand: Citroën
- Model: ë-C4
- First ten letter of my VIN:  VR7BCZKXCM
- Useable Electric capacity in kw: 45
- Fuel capacity in liter:

**Comment by MasterAndi** [comment]
Found the e-c4 is allready in the car_model.py, but i still get the error message.
,2021-05-16 11:15:03,848 :: WARNING :: Can't get language
,2021-05-16 11:15:04,438 :: INFO :: update_data
,2021-05-16 11:15:04,440 :: WARNING :: Can't get car model, please report an issue on github with your car model and first ten letter of your VIN

I get the data of the car in the json response with /get_vehicleinfo, but the Dashboard shows no informations to the car.

**Comment by flobz** [comment]
Do you have the last version of the app?

**Comment by MasterAndi** [comment]
i use the latest docker container, is this the last version of the app ?
in iobroker i get all informations from the json file (use a script to import),
also the activation of the precondition works fine.
Just the dashboard of your app has still no data.

**Comment by flobz** [comment]
Ok I just published a new version, can you retry ? (tag: v2.3.4)
