### ISSUE TITLE
[New Car model] 2018 Peugeot 5008 II 1.2 PureTech 130 GT Line 

### ISSUE THREAD

**Issue by honkerst** [flobz/psa_car_controller#128]
I have a "Can't get car model" error.
Information to add my car model to the app:
- Brand: Peugeot
- Model: 5008 II 1.2 PureTech 130 GT Line (year 2018)
- First ten letter of my VIN:  VF3MRHNYHH
- Useable Electric capacity in kw: 0
- Fuel capacity in liter: 56

**Comment by flobz** [comment]
added with 05403a6.
Thanks
