### ISSUE TITLE
Server issue

### ISSUE THREAD

**Issue by atze09** [flobz/psa_car_controller#13]
**To Reproduce**:
- Solution 1 (App Version 1.27)
- Windows 10
Server is running:
I used the command in chrome browser http://localhost:5000/get_vehicleinfo/YOURVIN
This gives me the following error:
![image](https://user-images.githubusercontent.com/6229866/103036348-d86f7d80-4569-11eb-8ea9-adeb4c7de842.png)

Information in Browser is:
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

config.json:
{
    "client_id": "x",
    "client_secret": "x",
    "customer_id": "x",
    "proxies": {
        "http": "",
        "https": ""
    },
    "realm": "clientsB2COpel",
    "refresh_token": "x",
    "remote_refresh_token": "x"
}

Command 2.2, gives me the following error and the same browser error.
![image](https://user-images.githubusercontent.com/6229866/103037181-ac54fc00-456b-11eb-87fb-4a46024fbc91.png)

Commands 2.3 and 2.4 "http://localhost:5000/charge_control?vin=YOURVIN&percentage=80 " and "http://localhost:5000/charge_control?vin=yourvin&hour=6&minute=0 " gives no error, but i could not check the car if those commands are working.

**Comment by flobz** [comment]
the error come from python_dateutil, check the version, it should be >= 2.5.3

**Comment by atze09** [comment]
Thanks again flobz, after upgrading the dateutil it works.
awesome piece of software you have created!
What do you personally do with the information you get? do you put it into your own app or home automation?
i plan to integrate it into home assistant.
Do you have any plans to put the data in mqtt or something else?

**Comment by flobz** [comment]
Great !
Thanks,
I use Domoticz to change the charge threshold and the stop hour. I never link a button to an api in homeassistant but it should be possible.
I choose to develop an api rather than a mqtt client, because it is more universal.
I'm also developing a dashboard, to follow the consumption of the car.

**Comment by atze09** [comment]
Thanks again, i will Link ist to a Button AS a workaround, until someone with better programming Skills is building an HA Integration and Dashboard.

**Comment by flobz** [comment]
It could be interesting to share how you do that, it can help other pepole.

**Comment by atze09** [comment]
I will keep the Community updated.
One last question: is possible to add the Email and Password to config. So that it is not necessary to type in at a restart?

**Comment by flobz** [comment]
There are arguments to specify this at the start of the program.

**Comment by atze09** [comment]
Hello Flobz,
it's me once again.
Server is running well on raspbian, and i have access on pi with localhost.
But could not get acess with the IP of the pi, so "http://localhost:5000/get_vehicleinfo/YOURVIN" is working
but "http://192.168.17.192:5000/get_vehicleinfo/YOURVIN" is not working, thats why i have currently have no access from my home assistant.
Can your server be exposed to home assistant throught the ip?

**Comment by atze09** [comment]
Found it in line 95 in server.py now it is working.

Only need to get the connection with Home Assistant REST Api.
