### ISSUE TITLE
[New Car model] my model Opel corsa-e

### ISSUE THREAD

**Issue by atze09** [flobz/psa_car_controller#131]
I have a "Can't get car model" error.
Information to add my car model to the app:
- Brand: Opel
- Model: corsa-e
- First ten letter of my VIN:  VXKUHZKXZL
- Useable Electric capacity in kw: 46
- Fuel capacity in liter: 0

**Comment by flobz** [comment]
it's already added. But this error might occur if you haven't the last version.
