### ISSUE TITLE
Not a bug just a question: Is there a command to start charging now

### ISSUE THREAD

**Issue by CWfFO** [flobz/psa_car_controller#132]
Hi,
is there a command like http://localhost:5000/charge_now/YOURVIN/0 to start charing immediate?
http://localhost:5000/charge_now/YOURVIN/1 seems not to work 

KR 
Christian

**Comment by flobz** [comment]
This command should work and it's the command that you are looking for. Do you have any error when you do this request?

**Comment by CWfFO** [comment]
A long runtime - it seems to hang and no effect. But to be honest i tried it last 1 month ago and not with the latest version. I will give it a try again.
