### ISSUE TITLE
[New Car model] my model Opel Zafira Zafira-e Life Innovation

### ISSUE THREAD

**Issue by show2go** [flobz/psa_car_controller#139]
I have a "Can't get car model" error.
Information to add my car model to the app:
- Brand: Opel
- Model: Zafira Zafira-e Life Innovation 
- First ten letter of my VIN:  VXEVZZKXZMZ
- Useable Electric capacity in kw: 68
- Fuel capacity in liter: 0
THANK YOU!

**Comment by show2go** [comment]
Hello,
i now installed your image on docker in my synology...

when i run the command,
i get this:

python3 /psa_car_controller/app_decoder.                                                                                                                            
py /config/myOpel_v1.27.1_apkpure.com.apk                                                                                                                                                                   
APK loading...                                                                                                                                                                                              
Requested API level 29 is larger than maximum we have, returning API level 28 in                                                                                                                            
stead.                                                                                                                                                                                                      
APK loaded !                                                                                                                                                                                                
MyOpel email: "someemail"                                                                                                                                                                           
MyOpel password:                                                                                                                                                                                            
What is your country code ? (ex: FR, GB, DE, ES...)                                                                                                                                                         
AT                                                                                                                                                                                                          
get_vehicles:                                                                                                                                                                                               
Traceback (most recent call last):                                                                                                                                                                          
  File "/psa_car_controller/my_psacc.py", line 176, in get_vehicles                                                                                                                                         
    res = self.api().get_vehicles_by_device()                                                                                                                                                               
  File "/psa_car_controller/psa_connectedcar/api/vehicles_api.py", line 1331, in                                                                                                                            
 get_vehicles_by_device                                                                                                                                                                                     
    (data) = self.get_vehicles_by_device_with_http_info(**kwargs)  # noqa: E501                                                                                                                             
  File "/psa_car_controller/psa_connectedcar/api/vehicles_api.py", line 1400, in                                                                                                                            
 get_vehicles_by_device_with_http_info                                                                                                                                                                      
    return self.api_client.call_api(                                                                                                                                                                        
  File "/psa_car_controller/libs/oauth.py", line 77, in call_api                                                                                                                                            
    raise e                                                                                                                                                                                                 
  File "/psa_car_controller/libs/oauth.py", line 59, in call_api                                                                                                                                            
    return self._ApiClient__call_api(resource_path, method,                                                                                                                                                 
  File "/psa_car_controller/psa_connectedcar/api_client.py", line 157, in __call                                                                                                                            
_api                                                                                                                                                                                                        
    response_data = self.request(                                                                                                                                                                           
  File "/psa_car_controller/psa_connectedcar/api_client.py", line 347, in reques                                                                                                                            
t                                                                                                                                                                                                           
    return self.rest_client.GET(url,                                                                                                                                                                        
  File "/psa_car_controller/psa_connectedcar/rest.py", line 234, in GET                                                                                                                                     
    return self.request("GET", url,                                                                                                                                                                         
  File "/psa_car_controller/psa_connectedcar/rest.py", line 228, in request                                                                                                                                 
    raise ApiException(http_resp=r)                                                                                                                                                                         
psa_connectedcar.rest.ApiException: (500)                                                                                                                                                                   
Reason: Internal Server Error                                                                                                                                                                               
HTTP response headers: HTTPHeaderDict({'X-Backside-Transport': 'FAIL FAIL', 'Con                                                                                                                            
nection': 'close', 'Cache-Control': 'no-store, no-cache, must-revalidate, privat                                                                                                                            
e', 'Content-Type': 'application/hal+json', 'Date': 'Sun, 23 May 2021 12:04:14 G                                                                                                                            
MT', 'Expires': '0', 'X-Global-Transaction-ID': '08f333a560aa44a814babc3f', 'Acc                                                                                                                            
ess-Control-Expose-Headers': 'APIm-Debug-Trans-Id, X-RateLimit-Limit, X-RateLimi                                                                                                                            
t-Remaining, X-RateLimit-Reset, X-Global-Transaction-ID', 'Access-Control-Allow-                                                                                                                            
Origin': '*', 'Access-Control-Allow-Methods': 'GET', 'Set-Cookie': 'rememberMe=d                                                                                                                            
eleteMe; Path=/; Max-Age=0; Expires=Sat, 22-May-2021 12:03:52 GMT, JSESSIONID=f7                                                                                                                            
dhvIf6ajxtJPsTete9-XN1DWhh06Rmqb40gl_f; path=/, PSACountry=AT;Domain=.groupe-psa                                                                                                                            
.com;Path=/', 'X-RateLimit-Limit': 'name=rate-limit-1,150;', 'X-RateLimit-Remain                                                                                                                            
ing': 'name=rate-limit-1,0;'})                                                                                                                                                                              
HTTP response body: {"uuid":"042cfd83-6ac8-4855-afad-b49652edbd9b","code":50000,                                                                                                                            
"message":"Internal Server Error :500"}   

Your vehicles: []                                                                                                                                                                                           
No vehicle in your account is compatible with this API, you vehicle is probably                                                                                                                             
too old... 


Thank you very much for your work!

**Comment by flobz** [comment]
added with 05403a6.
Thanks
For your error, did you receive your car yet ? Please open an new issue if the error persist.
