### ISSUE TITLE
Connection was refused by server

### ISSUE THREAD

**Issue by atze09** [flobz/psa_car_controller#14]
Connection was refused by server

**To Reproduce**
1. solution 1
2. start command as described
3. at startup

**Config file**
same as last issue

**Environment (please complete the following information):**
 - OS: Win 10
 - Android app Version [e.g. 27.0]

**Additional context**
`2020-12-31 12:42:50,049 :: ERROR :: can't refresh_remote_token: {'error': 'invalid_grant', 'error_description': 'grant is invalid', 'refresh_token': 'token'}
2020-12-31 12:42:50,257 :: INFO :: save config change
2020-12-31 12:42:50,540 :: INFO :: Connected with result code {'session present': 0}
2020-12-31 12:42:50,543 :: INFO :: subscribe to psa/RemoteServices/to/cid/Number/#
2020-12-31 12:42:50,545 :: INFO :: subscribe to psa/RemoteServices/events/MPHRTServices/FIN/#
2020-12-31 12:42:50,547 :: WARNING :: Disconnected with result code 5
2020-12-31 12:42:50,548 :: WARNING :: The connection was refused.
`

**Comment by atze09** [comment]
Seems my home assistant penetrated the server too much?

**Comment by flobz** [comment]
See https://github.com/flobz/psa_car_controller/issues/9#issuecomment-742711025
Also The maximum of api call per day is around 1 every 2 minutes.

**Comment by atze09** [comment]
Works with new refresh token

**Comment by flobz** [comment]
Please update to the last version. It will renew the token automatically when it expired.

**Comment by atze09** [comment]
Thanks for the information I will test it later. 
I read something about mqtt. Is it now possible to have a information via mqtt?

> Please update to the last version. It will renew the token automatically when it expired.

**Comment by flobz** [comment]
Yes remote control is done with MQTT but it's not new.
