### ISSUE TITLE
DS7 Crossback E-Tense 300 4x4 

### ISSUE THREAD

**Issue by gritschen** [flobz/psa_car_controller#141]
I have a "Can't get car model" error.
Information to add my car model to the app:
- Brand: DS
- Model: DS7 Crossback E-Tense 300 4x4 
- First ten letter of my VIN:  VR1J45GBUL
- Useable Electric capacity in kw: 13.2 gross, 11.5 net usabable
- Fuel capacity in liter: 43
- Typ: Hybrid

**Comment by flobz** [comment]
added with 05403a6.
Thanks
