### ISSUE TITLE
Synology, Docker Image, psa_car_controller

### ISSUE THREAD

**Issue by show2go** [flobz/psa_car_controller#145]
Hi there!
Thanks for your amazing work!

I already installed the docker image, and it is running,
also the registry procedure and sms activation worked out fine...

i start the server with this command:
python3 /psa_car_controller/server.py -f /config/test.json -c /config/charge_config1.json -p 5010 -l 0.0.0.0 -r -b /config

i use port 5010 because 5000 is the synology itself

it does start correctly, and also updates every 2minutes:
looks like this:
2021-05-25 09:10:22,288 :: INFO :: charging status of VXEVZZKXZMZ025114 is Disco
nnected, battery level: 21 

but when i try to open http://192.168.55.110:5010 , it show me "404 - not found" in my browser

in the terminalwindow in docker, it shows: 

192.168.55.158 - - [25/May/2021 09:12:15] "GET / HTTP/1.1" 404 -

this means the programm gets the request, but isnt able to give anything back...

i am really stuck after trying many hours...

i also tried to install it on a local linux machine directly, and there, from the machine itself, i can see the website correctly when i enter localhost:5000

my goal is to have it running in docker on my synology, 
maybe you can give me a direction, what ist wrong on my side?

Thank you very much!

**Comment by sbauza** [comment]
Please follow the last step documented in https://github.com/flobz/psa_car_controller/blob/master/docs/Docker.md

You need to amend the dockerconfig.conf file by saying SHELL_ONLY=TRUE which will allow the init.sh script to run the server after a restart of the container.

Also, you need to edit the init.sh script by adding the -r flag before restarting the container, or it won't store the data it gets (or wait for a new release of the container, the current latest one needs to be updated with the pull request #129 that was merged recently)
