### ISSUE TITLE
Docker image for ARM architecture

### ISSUE THREAD

**Issue by fedearne** [flobz/psa_car_controller#149]
Hi

would it be possible to build a dockerimage for the ARM architecture, to run this on Raspberry PI?

The python:3-slim should support ARMv5, i don't know about the application dependencies.

-Morten

**Comment by italoc** [comment]
`FROM python:3
RUN cd / && git clone https://github.com/flobz/psa_car_controller.git
WORKDIR /config
RUN pip3 install -r /psa_car_controller/requirements.txt

COPY * /config/

RUN chmod +x /psa_car_controller/docker_files/init.sh

EXPOSE 5000
CMD /psa_car_controller/docker_files/init.sh`

i have built a docker image for raspberry with this Dockerfile, and works

**Comment by italoc** [comment]
you can find my image here

docker pull italoc/psa

**Comment by fedearne** [comment]
Works like a charm. Thank you for sharing.
