### ISSUE TITLE
HUTokenManager.xml

### ISSUE THREAD

**Issue by rldalex** [flobz/psa_car_controller#15]
Bonjour,
Après de longue recherche et le site prou les dev de PSA en maintenance.
Je n'arrive toujours pas à visualiser les échanges entre le serveur de PSA et l'application. Le certificat présent dans l'application est MWPMYMA1.pfx et non MWPMYMA1.pe donc sans le mot de passe impossible de l'ajouter dans le proxy pour certifier les échanges. Avec Frida même problème je bloque sur le bypass du SSL pinning. J'ai testé pas mal d'autre solution également mais toujours le même soucis.

Apparemment le système d'envoie des commandes au véhicule ne fonctionne plus de la même manière. Il n'y a plus le fichier HUTokenManager.xml lorsque l'on réalise le backup de l'application (version 2.7).

Du coup impossible d'utiliser la 1er méthode pour obtenir les informations du fichier test.json.

Si jamais je serai ravis d'en apprendre un peu plus.

Cordialement,
Alexandre.

**Comment by flobz** [comment]
Hello,
The pfx file can be converted to pem with an empty password:
openssl pkcs12 -in MWPMYMA1.pfx -out MWPMYMA1.pem -nodes
If you have the last last version of the app_decoder.py, it should work with 1.27.
Best regards

**Comment by rldalex** [comment]
Thanks for help. It's work !
