### ISSUE TITLE
API endpoints, except /vehicle/<VID>, Response with 4040 Statuscode

### ISSUE THREAD

**Issue by Windows81User** [flobz/psa_car_controller#150]
Hello,

I bought my new Peugeot 208 GT 130PS with petrol engine at the beginning of May.

Now I also wanted to experiment a bit with the API and I noticed that none of my previous 72 journeys can be retrieved via the API.

However, I have listed all my trips in the MyPeugeot app and the Telemaintaince service is also booked and activated.

I only get a 404 response from each of the API endpoints e.g. "/trips" , "/status" , "/telemetry" with the information that no data has been saved yet.

Does anyone know why this is happening?

Have anyone the same problem with his/her no hybrid/electro car ?

Many thanks in advance :)

**Comment by flobz** [comment]
duplicate with #57
