### ISSUE TITLE
Concern with program recorded when fan is turn on

### ISSUE THREAD

**Issue by HOzo123** [flobz/psa_car_controller#156]
**Describe the bug**
Using the PSA API, when I use command "http://localhost:5000/preconditioning/YOURVIN/1" to turn on the preconditioning of vehicle (e208), the preconditionning-program (already written) is removed. Issue is reproduced at 100%

**To Reproduce**
1. what command did you use
- using the APP from PSA, I'm written some preconditionning program (same result if 1, 2, 3 or 4 are written)
- the check of program written is confirmed using the PSA APP and this APP (by the server on http://127.0.0.1:5000/get_vehicleinfo/VIN)
- To turn on the preconditionning, I'm usisng command: http://localhost:5000/preconditioning/YOURVIN/1
- one minute after, the preconditionning is turned on but the preconditionning programs have been removed
2. when the bug append ?
at 100% when command "preconditionning is turn on".
3. Does it persist after restarting the program? 
Yes, I have re-create the token and no change; issue still present.

![before command precond](https://user-images.githubusercontent.com/85363152/120842599-32d72600-c56d-11eb-91d8-ecf050c28590.jpg)
![after command precond](https://user-images.githubusercontent.com/85363152/120842604-34a0e980-c56d-11eb-971c-4b253271486c.jpg)

**Config file**
Give the anonymize content of the config file

**Environment (please complete the following information):**
 - Linux debian updated some weeks ago (HW: Raspberry V4)
 - e208
 - Application updated some days ago

**Additional context**
nothing to add....

**Comment by HOzo123** [comment]
the same issue has been also reported by another person on "https://forums.automobile-propre.com/topic/controle-du-v%C3%A9hicule-via-lapi-peugeot-27814/?&page=5#comments"

**Comment by flobz** [comment]
Can you retry with the latest commit? I tried to fix this problem.

**Comment by HOzo123** [comment]
Hello Flobz,
I just retried (only one time); it's work perfectly now. Thank you for your prompt reply !

That topic is now closed.

**Comment by HOzo123** [comment]
Thank you for the great job performed by Flobz !
