### ISSUE TITLE
NEED_AUTHORIZATION

### ISSUE THREAD

**Issue by Horsi70** [flobz/psa_car_controller#158]
Hello,
Did not find a solution in the other tickets, so here a small description of the error I have:
 python3 app_decoder.py ../com.psa.mym.myopel_1.29.0-2118_minAPI24\(arm64-v8a\,armeabi-v7a\,x86\,x86_64\)\(nodpi\)_apkmirror.com.apk
APK loading...
Requested API level 29 is larger than maximum we have, returning API level 28 instead.
RES_TABLE_LIBRARY_TYPE chunk is not supported
RES_TABLE_LIBRARY_TYPE chunk is not supported
RES_TABLE_LIBRARY_TYPE chunk is not supported
RES_TABLE_LIBRARY_TYPE chunk is not supported
RES_TABLE_LIBRARY_TYPE chunk is not supported
APK loaded !
MyOpel email: p...
MyOpel password:
What is your country code ? (ex: FR, GB, DE, ES...)
LU
Traceback (most recent call last):
  File "app_decoder.py", line 84, in <module>
    token = res.json()["accessToken"]
KeyError: 'accessToken'
HOST_BRANDID : https://id-dcr.opel.com/mobile-services sitecode: OP_LU_ESP
{"session":"fc..asessionid..a9","returnCode":"NEED_AUTHORIZATION","token":"45..atoken..af"}

I tried with different country codes (FR, BE, LU). Just to be sure, the username and password to use are those from the account used in the MyOpel app?
Any idea what could be wrong? Installed on an Ubuntu 20.04 LTS with latest updates, as described in the installation manual.

Thanks a lot for any help

**Comment by flobz** [comment]
Sorry I don't know why it doesn't work.
