### ISSUE TITLE
ERROR :: Can't get altitude from API

### ISSUE THREAD

**Issue by lvenditti** [flobz/psa_car_controller#159]
I followed the video guide on you tube to finalize installation.
All went well but, on the log of APP I can see this message: 

ERROR :: Can't get altitude from API

and the altitude is not available on dashboard.

**Additional context**
My car is a citroen e-c4 (full electric)

**Comment by flobz** [comment]
Where do you live ?

**Comment by lvenditti** [comment]
I live in Italy.
Many thanks for you attention.

cheers.

**Comment by flobz** [comment]
The API use latitude and a longitude to get the altitude. Can you give me the the  latitude and a longitude that don't work ?

**Comment by thennart** [comment]
Hello,
Same error log about altitude for me in France.
I noticed API response has no lat / lon 

`"last_position":{
"type": "Feature",
"geometry":{
"coordinates":[
null,
null,
null
],
"type": "Point"
},`

Peugeot 3008 Hybrid 225

**Comment by flobz** [comment]
Ok so it's normal. PSA api doesn't provide the position so you can't get altitude from it.
