### ISSUE TITLE
404 when using Vauxhall brand

### ISSUE THREAD

**Issue by rmhomecouk** [flobz/psa_car_controller#163]
**Describe the bug**
On first attempt as signing in with Vauxhall UK, I receive a HTTP Error 404: Not Found error instantly.

**To Reproduce**
Start with  ./server.py --web-conf -l 0.0.0.0 -p 5001
Select Vauxhall brand and click submit. no matter if you have user/pass, the same 404 responds instantly.

**Config file**
no config yet, first attempt at starting

**Environment (please complete the following information):**
Linux Ubuntu

**Additional context**
2021-06-24 23:22:53,398 :: INFO :: update_data
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://172.22.32.142:5001/ (Press CTRL+C to quit)
172.22.32.106 - - [24/Jun/2021 23:23:33] "GET / HTTP/1.1" 200 -
172.22.32.106 - - [24/Jun/2021 23:23:33] "GET /assets/clientside.js?m=1624573280.045867 HTTP/1.1" 200 -
172.22.32.106 - - [24/Jun/2021 23:23:34] "GET /_dash-layout HTTP/1.1" 200 -
172.22.32.106 - - [24/Jun/2021 23:23:34] "GET /_dash-dependencies HTTP/1.1" 200 -
172.22.32.106 - - [24/Jun/2021 23:23:34] "GET /_favicon.ico?v=1.20.0 HTTP/1.1" 200 -
172.22.32.106 - - [24/Jun/2021 23:23:34] "POST /_dash-update-component HTTP/1.1" 200 -
172.22.32.106 - - [24/Jun/2021 23:23:34] "GET /config HTTP/1.1" 200 -
172.22.32.106 - - [24/Jun/2021 23:23:34] "GET /assets/clientside.js?m=1624573280.045867 HTTP/1.1" 304 -
172.22.32.106 - - [24/Jun/2021 23:23:34] "GET /_dash-dependencies HTTP/1.1" 200 -
172.22.32.106 - - [24/Jun/2021 23:23:34] "GET /_dash-layout HTTP/1.1" 200 -
172.22.32.106 - - [24/Jun/2021 23:23:34] "POST /_dash-update-component HTTP/1.1" 200 -
172.22.32.106 - - [24/Jun/2021 23:23:34] "POST /_dash-update-component HTTP/1.1" 200 -
172.22.32.106 - - [24/Jun/2021 23:23:42] "POST /_dash-update-component HTTP/1.1" 200 -
172.22.32.106 - - [24/Jun/2021 23:23:47] "POST /_dash-update-component HTTP/1.1" 200 -
172.22.32.106 - - [24/Jun/2021 23:23:50] "POST /_dash-update-component HTTP/1.1" 200 -
172.22.32.106 - - [24/Jun/2021 23:23:53] "POST /_dash-update-component HTTP/1.1" 200 -
172.22.32.106 - - [24/Jun/2021 23:23:56] "POST /_dash-update-component HTTP/1.1" 200 -

**Comment by rmhomecouk** [comment]
update: did a print(filename) on app_decoder and it was showing myvauxhll.apk as the file it was expecting.

my python skill are poor so I just renamed my apk to myvauxhll.apk and I'm getting further ( Can't get car model)

I'll add my car now :)

**Comment by italoc** [comment]
same think with citroen car but if i put my apk in /data folder with name mycitroen.apk nothing change

**Comment by rmhomecouk** [comment]
Don't put in the data folder leave in the root folder - that's where my file is

**Comment by italoc** [comment]
> Don't put in the data folder leave in the root folder - that's where my file is

in the root of the container? for me nothing change

**Comment by gavin0987** [comment]
Pretty sure you'll need myds.apk in the config directory if they app is not able to download it automatically.

**Comment by gavin0987** [comment]
Also where the setup page suggests "EN" for the English Language it appears that I had to enter "GB" to make it work.

**Comment by flobz** [comment]
> update: did a print(filename) on app_decoder and it was showing myvauxhll.apk as the file it was expecting
Ok I fixed this thanks
> Also where the setup page suggests "EN" for the English Language it appears that I had to enter "GB" to make it work.
I will fix that too.

**Comment by flobz** [comment]
I should be fixed now.

**Comment by italoc** [comment]
i have the same problem but with Citroen, i have the latest version of psa_car_controller 2.4.1 but if i select CITROEN i obtain ERROR 404

**Comment by flobz** [comment]
@italoc I should be fixed now with v2.4.2.

**Comment by italoc** [comment]
> @italoc It should be fixed now with v2.4.2.

Work great with this session.
