### ISSUE TITLE
[New Car model] Grandland X Hybrid 4

### ISSUE THREAD

**Issue by rmhomecouk** [flobz/psa_car_controller#164]
I have a "Can't get car model" error.
Information to add my car model to the app:
- Brand: Vauxhall
- Model: Grandland X Hybrid4
- First ten letter of my VIN:  W0VZ45GB3L
- Useable Electric capacity in kw: 13
- Fuel capacity in liter: 43
- 
Your vehicles: ["{'vin': 'W0VZ45GB3L', 'vehicle_id': '1567a4257453d', 'label': 'unknown', 'brand': 'C', 'abrp_name': None, 'battery_power': 46, 'fuel_capacity': 0, 'max_elec_consumption': 70, 'max_fuel_consumption': 30}"]

**Comment by flobz** [comment]
will be added with 30b6164 . Thanks
