### ISSUE TITLE
Exception on /get_vehicleinfo/###VIN###

### ISSUE THREAD

**Issue by gavin0987** [flobz/psa_car_controller#167]
It seems the Vauxhall API is not providing the mileage for my Vauxhall Corsa-E to this application.

When HomeAssistant calls psa_car_controller to get_vehicleinfo there is no data returned and I see a stack trace printed in the docker logs.

```
Exception on /get_vehicleinfo/VXxxxxxxxxxxxxx [GET]
PSAController    | Traceback (most recent call last):
PSAController    |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
PSAController    |     response = self.full_dispatch_request()
PSAController    |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
PSAController    |     rv = self.handle_user_exception(e)
PSAController    |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
PSAController    |     rv = self.dispatch_request()
PSAController    |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
PSAController    |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
PSAController    |   File "/psa_car_controller/web/views.py", line 133, in get_vehicle_info
PSAController    |     response=json.dumps(CONFIG.myp.get_vehicle_info(vin, from_cache).to_dict(), default=str),
PSAController    |   File "/psa_car_controller/my_psacc.py", line 156, in get_vehicle_info
PSAController    |     self.record_info(car)
PSAController    |   File "/psa_car_controller/my_psacc.py", line 459, in record_info
PSAController    |     **mileage = car.status.timed_odometer.mileage**
PSAController    | **AttributeError: 'NoneType' object has no attribute 'mileage'**
```

**To Reproduce**
1. what command did you use
      Standard setup using latest docker build, behavior seems to be cause by upstream issue.
2. when the bug append ?
      Bug has always existed for me
3. Does it persist after restarting the program? 
      Yes

**Config file**
Give the anonymize content of the config file

**Environment (please complete the following information):**
 - OS: **Docker (flobz/psa_car_controller:v2.3)**
 - Brand and model of car:    **Vauxhall Corsa-E**
 - Application version (commit number, branch) **Docker Tag: LATEST** 

**Additional context**
I have been working around the issue by editing the my_pssacc.py file and changing:

_mileage = car.status.timed_odometer.mileage_
to
_mileage = 0_

I am happy to run any tests as needed, just shout!

**Comment by flobz** [comment]
Thanks for reporting, I never had this problem. I will catch this error in next version.

**Comment by gavin0987** [comment]
Thanks, I am not entirely sure why the mileage is not coming through in the first place. The MyVauxhall app shows the cars mileage so would expect the API call to return the value to your code.

**Comment by flobz** [comment]
fix in develop branch
