### ISSUE TITLE
package name hard coded

### ISSUE THREAD

**Issue by pancky** [flobz/psa_car_controller#17]
Hello I had some issues with the app_decoder.py because the packagename "com.psa.mym.mypeugot" is hard coded.
I have an Opel Astra. I changed it to "com.psa.mym.myopel" now it works

**Comment by flobz** [comment]
Hello,
Thanks for your help. 
I fix the problem in [feature/dashboard](https://github.com/flobz/psa_car_controller/tree/feature/dashboard) branch.
