### ISSUE TITLE
ERROR :: abrp

### ISSUE THREAD

**Issue by nitr8** [flobz/psa_car_controller#173]
**Describe the bug**
abrp errors 

**To Reproduce**
Steps to reproduce the behavior: Start app with e-208
1. what command did you use: [Docker (nothing special - aka stick) / debian (-f config.json -c charge_config.json) ]
2. when the bug append: [Every 2 min]
3. Does it persist after restarting the program? [Yes]

**Config file**
```
---
    "abrp": {
        "abrp_enable_vin": [
            "VR3UHZKXXXX1234"
        ],
        "token": "12345a1b-1234-1234-abcd-cdab123e123"
    },
---
```
**Environment (please complete the following information):**
 - OS: [Docker container / Debian 10]
 - Android app Version [1.27 / 1.28]
 - Brand and model of car: [PEUGEOT e-208]
 - Application version (#171, master) 

**Additional context**
```
2021-07-01 20:16:07,580 :: ERROR :: abrp:
Traceback (most recent call last):
  File "/psa_car_controller/web/abrp.py", line 43, in call
    return response.json()["status"] == "ok"
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)
```

**Comment by flobz** [comment]
You should have more log with last version. Can you try ?

**Comment by nitr8** [comment]
Hi flobiz,

Thanks for the heads up.

```
2021-07-08 16:19:29,486 :: ERROR :: Bad
```

I guess the instructions have changed, i followed the guide but it seems the abrp site has changed - there is no more copy link. I emailed bo from abrp and used the API key provided, I guess thats the problem.

**Comment by flobz** [comment]
I still see it. Can you take a screen shot?

**Comment by nitr8** [comment]
sure - but a screenshot of what exactly?

**Comment by flobz** [comment]
Please read instructions carefully.
