### ISSUE TITLE
My car info config HTTP Error 404

### ISSUE THREAD

**Issue by token7240** [flobz/psa_car_controller#175]
![Cattura](https://user-images.githubusercontent.com/24840619/124296941-d0b51500-db5a-11eb-9d60-8461da1f0947.PNG)
 in the "Car Brand" field there is an error, Citroen is written Ci**r**troen
probably for this reason I get the 404 error

**Comment by flobz** [comment]
Should be fixed with v2.4.2

**Comment by token7240** [comment]
now work fine,thanks
