### ISSUE TITLE
Stop charging Command activates the Loading with a start time

### ISSUE THREAD

**Issue by calliou1234** [flobz/psa_car_controller#177]
Hello,

the command

`http://192.168.178.35:4995/charge_now/VIN123456/0`

turns off charging. The problem is, however, that each time the command is sent, loading is activated at the start time from the myPeugeot-App is set.
This can also be seen in the app.

With the command `http://192.168.178.35:4995/charge_now/VIN123456/1` it is not possible to start the charging process anymore!

Is there a command that only interrupts loading and not activate the start time, or is there a command to switch off the start time, or to activate immediate charging?

Thank you for your support.

**Comment by flobz** [comment]
No Peugeot doesn't provide this feature.
