### ISSUE TITLE
Wakeup command don’t work

### ISSUE THREAD

**Issue by italoc** [flobz/psa_car_controller#178]
If I run wake up command i can’t see update, if I run refresh on official spa app I see update.

I have search in my log but I don’t have error

my wake up request return TRUE but no data update

psa_car_controller v2.4.2

**Comment by flobz** [comment]
Are you sure it works on psa android app ?
For me it doesn't work for both for few days.

**Comment by italoc** [comment]
> Are you sure it works on psa android app ?
> For me it doesn't work for both for few days.

I use iOS and with iOS app works, but I think that I can’t refresh too quickly, if I refresh every 2-3 hours work (in the iOS app)

**Comment by lelas33** [comment]
One code line is missing in latest release of MyPSACC class.

In method wakeup()  =>
      self.mqtt_client.publish(MQTT_REQ_TOPIC + self.__get_mqtt_customer_id() + "/VehicleState", msg)

**Comment by flobz** [comment]
You are right thanks ! But even with this line it doesn't work for me... It works for you ?

**Comment by lelas33** [comment]
Yes it works for me with "/VehCharge/state".

(I had swapped with "/VehicleState" in previous comment)

**Comment by flobz** [comment]
I was wrong. It works and fixed with last version. Thanks @lelas33.
