### ISSUE TITLE
D'ont stop charge when threshold is reached

### ISSUE THREAD

**Issue by token7240** [flobz/psa_car_controller#180]
when I set the threshold to a value, the machine continues to load up to 100%, do you know why?

![Cattura](https://user-images.githubusercontent.com/24840619/124632726-e42aed80-de84-11eb-8788-0240d6ef42ca.PNG)

**Comment by Flodu31** [comment]
Same for me.
Sometimes it works, sometimes not.
Florent

**Comment by flobz** [comment]
Thr car should send a message to the API server when charge begin. Sometimes the car didn't send this message...

**Comment by maivorbim** [comment]
In my case setting charge threshold to 80% works fine on Peugeot e208.

Not sure if related, but make sure you have remote_token set in config file.

**Comment by DavidFFerreira** [comment]
I have the ec4 and ive got an error 
Exception on /charge_control [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/psa_car_controller/web/views.py", line 197, in get_charge_control
    charge_control = CONFIG.chc.get(vin)
AttributeError: 'Config' object has no attribute 'chc'

sooo it only sync when i restart, than if I want to check values again, i need to restart the addon =/

**Comment by DavidFFerreira** [comment]
oken7240  can u help me to create something similiar to your cards?

**Comment by Flodu31** [comment]
> I have the ec4 and ive got an error
> Exception on /charge_control [GET]
> Traceback (most recent call last):
> File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2070, in wsgi_app
> response = self.full_dispatch_request()
> File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1515, in full_dispatch_request
> rv = self.handle_user_exception(e)
> File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1513, in full_dispatch_request
> rv = self.dispatch_request()
> File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1499, in dispatch_request
> return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
> File "/psa_car_controller/web/views.py", line 197, in get_charge_control
> charge_control = CONFIG.chc.get(vin)
> AttributeError: 'Config' object has no attribute 'chc'
> 
> sooo it only sync when i restart, than if I want to check values again, i need to restart the addon =/

I have exactly the same error with the last version :( any idea? Thanks
