### ISSUE TITLE
Wakeup not working

### ISSUE THREAD

**Issue by Dario82** [flobz/psa_car_controller#183]
Hello,
with this latest docker image release, the wakeup not working.

My request log:
2021-07-09 12:53:36,090 :: INFO :: ask wakeup to XXXXXX
2021-07-09 12:53:36,328 :: INFO :: save config change
2021-07-09 12:53:36,329 :: INFO :: {"access_token": null, "customer_id": "XXXXXX", "correlation_id": "XXXXXX", "req_date": "2021-07-09T10:53:36Z", "vin": "XXXXXX", "req_parameters": {"action": "state"}}
172.18.1.40 - - [09/Jul/2021 12:53:36] "GET /wakeup/XXXXXX HTTP/1.1" 200 -
172.18.1.40 - - [09/Jul/2021 12:53:49] "GET /get_vehicleinfo/XXXXXX HTTP/1.1" 200 -
["XXXXXX" -> I've replaced the original values]

If I ask a wakeup from peugeot app, the data will be update.

Thank you,
Dario.

**Comment by flobz** [comment]
Are you using the 2.4.3 version?

**Comment by Dario82** [comment]
I'm using your latest docker image version on the hub.

latest: Pulling from flobz/psa_car_controller
Digest: sha256:e9cc3464944760ac9c4151cc86b2522a274d065b8f36e7d11b11523ec1554c9b
Status: Image is up to date for flobz/psa_car_controller:latest
docker.io/flobz/psa_car_controller:latest

**Comment by flobz** [comment]
I can't find any version with this hash.

**Comment by RaphaelChochon** [comment]
Hello,

I have a fresh Debian installation with the same problem. WakeUp from ``psa_car_controller`` doesn't work, while it works with the Android app.

As @Dario82  I have the "access_token" set to null in the activity log, could this be the problem?
In my ``config.json`` file, I also have the "remote_refresh_token" set to null, and the error message on launch "ERROR :: remote_refresh_token isn't defined" as shown on issue #184

Is this related?

Part of my log :
```
2021-07-12 08:27:52,174 :: INFO :: save config change
2021-07-12 08:27:52,677 :: INFO :: ["{'vin': 'XXXXXXX', 'vehicle_id': 'XXXXXXX', 'label': 'e-208', 'brand': 'Peugeot', 'abrp_name': 'peugeot:e208:20:50', 'battery_power': 46, 'fuel_capacity': 0, 'max_elec_consumption': 70, 'max_fuel_consumption': 0}"]
2021-07-12 08:27:52,977 :: INFO :: save config change
2021-07-12 08:27:52,977 :: ERROR :: remote_refresh_token isn't defined
2021-07-12 08:27:53,596 :: INFO :: update_data
2021-07-12 08:29:10,094 :: INFO :: ask wakeup to XXXXXXX
2021-07-12 08:29:10,393 :: INFO :: save config change
2021-07-12 08:29:10,393 :: INFO :: {"access_token": null, "customer_id": "XXXXXXX", "correlation_id": "XXXXXXX", "req_date": "2021-07-12T08:29:10Z", "vin": "XXXXXXX", "req_parameters": {"action": "state"}}
2021-07-12 08:29:53,413 :: INFO :: charging status of XXXXXXX is Finished, battery level: 100

```

**Comment by Dario82** [comment]
> I can't find any version with this hash.

I use your latest docker image in hub.docker.com
flobz/psa_car_controller
By flobz • Updated 8 days ago

**Comment by Dario82** [comment]
Today, I don't get anything. is it my problem or PSA?

**Comment by mr-sven** [comment]
As I understand the code right, you need the refresh_remote_token for accessing the MQTT service. So if its empty you have to renew your OTP data.

**Comment by Dario82** [comment]
Yes... But... 
Until yesterday, only the wakeup not worked.
From today, everithing...
Is there a new problem or is it a my problem?

**Comment by mr-sven** [comment]
Is your status request working?

**Comment by Dario82** [comment]
Nope..
Last update 7.54 (today).

Do you check if your app update the data?
My app isn't working now...

**Comment by mr-sven** [comment]
Strange my request processor is working fine, did you try to reauth completely?

**Comment by Dario82** [comment]
yes, I've tried it.
my request processor return 7.54 today update.
But my car is on charge and this information isn't present on the json.
And, on my PSA app I see the same update. 
I think this is a PSA problem.
Can you wakeup your car with PSA app?

**Comment by mr-sven** [comment]
Currently its working, status updates are send

**Comment by Dario82** [comment]
Ok, it is my problem.
Thank you for your help.

Remain active the wakeup problem only.

**Comment by mr-sven** [comment]
ok, turn you car on and off (manual wakeup) , maybe it losts the connection to the server

**Comment by Dario82** [comment]
I've tried it, nope.  :)

**Comment by mr-sven** [comment]
Sometimes the app also hangs, for a few hours until status is returned without touching the car. I think they have still issues with the communication between the car and there cloud. Thats possible a reason why the b2c API is still not published.

**Comment by Dario82** [comment]
Maybe... now I found a touchscreen update. I'll try with this.

And... for wakeup problem I can add this log:
2021-07-14 14:34:30,897 :: INFO :: save config change
**,2021-07-14 14:34:30,897 :: ERROR :: remote_refresh_token isn't defined**
,2021-07-14 14:34:30,900 :: WARNING :: Can't get language
,2021-07-14 14:34:31,892 :: ERROR :: Can't get altitude from API
,2021-07-14 14:34:31,905 :: INFO :: update_data
,2021-07-14 14:34:31,978 :: ERROR :: Can't get altitude from API
, * Running on all addresses.
,   WARNING: This is a development server. Do not use it in a production deployment.
, * Running on http://172.18.1.42:5000/ (Press CTRL+C to quit)

**Comment by mr-sven** [comment]
ok, do you update via USB? can you log the time. The Seller said it takes 4 hours.

**Comment by Dario82** [comment]
The app running now... And I haven't update anything yet.
I' have all the data (battery, mileage, ecc ecc) now but I haven't the GPS position.

LOG:
2021-07-14 19:06:29,396 :: DEBUG :: vin:XXXXX longitude:XX.XXXX latitude:XX.XXXX date:2021-07-14 05:54:14+00:00 mileage:22990.0 level:81.0 charge_date:2021-07-14 17:06:00+00:00 level_fuel:0.0 moving:False
,2021-07-14 19:06:29,397 :: DEBUG :: position already saved
,2021-07-14 19:06:29,551 :: DEBUG :: {"status": "ok", "missing": "Missing telemetry: power, speed, "}
,2021-07-14 19:06:29,552 :: DEBUG :: charging_status:Disconnected 

The longitude and latitude shown is an old update, I'm been in that position before this today's problem.

**Comment by CalicodesIles** [comment]
@Dario82 OK so now you are in the same situation as other people : some have a null value like said precisely in this issue [#50](https://github.com/flobz/psa_car_controller/issues/50) and others have an old value that is never updated.
It has the same source : no kinetic values retrieved from PSA API.

**Comment by Dario82** [comment]
But it is all ok before yesterday.
I've request the telemaintenance service, yesterday!
If I call the service for disable the telemaintenance, can I have the value?

**Comment by CalicodesIles** [comment]
I had the same situation : télémaintenance option activated and GPS information lost definitely after that.

I ask Peugeot support to remove the option, it was done a few weeks ago but still, no GPS information.

**Comment by Dario82** [comment]
Then... is it impossible to have the gps data again??

**Comment by CalicodesIles** [comment]
Unfortunately, in the different comments, no one seems to have recovered GPS through API when they lost it before

**Comment by Dario82** [comment]
incredible...

**Comment by mr-sven** [comment]
Hm, currently no updates from my car, App not working and last data from api is yesterday noon.

**Comment by Dario82** [comment]
I've an update from app (no gps) but I haven't update from psa_car_controller wakeup.

**Comment by mr-sven** [comment]
Update is working now, but GPS is frozen

**Comment by Dario82** [comment]
I've tried it now:
2021-07-21 08:20:40,540 :: INFO :: ask wakeup to XXXXX
,172.18.1.40 - - [21/Jul/2021 08:20:40] "GET /wakeup/XXXXX HTTP/1.1" 200 -
,2021-07-21 08:20:40,877 :: INFO :: save config change
,2021-07-21 08:20:40,897 :: INFO :: {"access_token": null, "customer_id": "XXXXX", "correlation_id": "XXXXX", "req_date": "2021-07-21T06:20:40Z", "vin": "XXXXX", "req_parameters": {"action": "state"}}
But, **last_update: 2021-07-20 11:35:16**

If I request a wakeup from MyPeugeot app and a /get_vehicleinfo I have:
**last_update: 2021-07-21 08:22:19**

**Comment by Dario82** [comment]
Hello, any news?

**Comment by Dario82** [comment]
Hello, when you can resolve this problem? 
I've updated to latest version (docker image) but I have this problem yet!
Thank you.

**Comment by flobz** [comment]
Remove the container and make sure to have the last version.
You are the only one who have this issue.

**Comment by Dario82** [comment]
I've tried it.
