### ISSUE TITLE
Feature Idee

### ISSUE THREAD

**Issue by moritz31** [flobz/psa_car_controller#186]
Hey @flobz i currently sit on a mobile app finding out how the psa api stuff works. 
Your psa car controller has a possibility to set a charge limit, would it maybe possible to provide some endpoints for an app or something like this where we can change the charge limit dynamically ?

**Comment by dreimer1986** [comment]
Well, you can set it with a simple curl.
curl -s "http://127.0.0.1:5000/charge_hour?vin=YOURVIN&hour=%hours%&min=%minutes%"
