### ISSUE TITLE
Charge speed based on "charging_rate"

### ISSUE THREAD

**Issue by SamuelBrucksch** [flobz/psa_car_controller#187]
Hi,

i think the `charging_rate` is based on the WLTP range of the car. For example on my 75kWh Zafira-e and a 16A single phase charge it says `20` (i guess it charges 20km range per hour).

Let's make the math:
WLTP consumption: 68/330*100 = 20.6kWh/100km
20km requires 20.6/(100/20)kWh = 4.12kW (should actually be around 3.6kW)

Now with 3P 16A:
`charging_rate` is 64 now
64km requires 20.6/(100/64)kWh = 13,2 (should actually be 11)

The error here is roughly the same in both cases, so maybe one of the numbers is slightly wrong (bat capacity, or wltp range).

I think i heard of other people that said the `charging_rate` numbers are consistent.

I can also verify this on a fast charger later if it helps.

**Comment by mr-sven** [comment]
I'm unclear where your numbers came from. What is the `68`, the 75kWh Zafira is declared with 27,3 - 24,4 kWh/100 km.
The e-208 with emergency loader (1.8 kW) returns `charging_rate` at 6.

**Comment by mr-sven** [comment]
Maybe it is the value of the DC Converter Amp output.
This make more sense to me:
```
Assume the zafira has a battery voltage of 180 V
20 A * 180 V = 3.6 kW
64 A * 180 V = 11.52 kW

Assume the e-208 has a battery voltage of 300 V
6 A * 300 V = 1.8 kW
```

**Comment by SamuelBrucksch** [comment]
68 is the usable battery capacity. The WLTP consumption includes charging losses, but that is not relevant as the charge_rate shows charged km/h so it shows what actually get's into the battery. We can ignore the losses here, so we need to calculate based on real consumption of WLTP range.

It definitely is km/h, you can compare it with the app.

**Comment by mr-sven** [comment]
If you flip the calculation, the value are far away from beeing even. I think you can onyl estimate the power consumption from this value.

(100/20) * 3.6 = 18
(100/64) * 11 = 17.18
(100/20) * 4.1 = 20.5
(100/34) * 6.9 = 20

(100/6) * 1.8 = 30

**Comment by SamuelBrucksch** [comment]
The e208 will have different values than the zafira of course. It also has a totally different consumption. 18 to 20 is not that far away and could be caused by rounding issues, which are obviously there if you compare 3,6kW and 4,1kW charging.

Anyways even if they are not pretty accurate with my calculation, you can still estimate the charge speed, as the values seem to be consistent. I can still check on a few other days if they change but i doubt it as i saw some of those values a few times already.

The current avg charge speed is also not very accurate if you compare integer numbers from soc to estimate charged energy. For example 4.5% to 6.4% charge on my Zafira will be 1.29kWh, but the API will provide 5-6% soc change which will result in 0,68kWh.

**Comment by flobz** [comment]
I'dont understand the point of this topic...

**Comment by SamuelBrucksch** [comment]
When you use this in combination with ABRP a more accurate charge speed is important. Especially on a fast charger the speed calculated based on this should be more accurate.

**Comment by flobz** [comment]
Can you do a fix?

**Comment by flobz** [comment]
I try to do it but charge rate is not very accurate so I did a mean of the old solution and the new one : 086a56b4dd6db0a396f5366a0073d9df8cf6c050
