### ISSUE TITLE
Setting the charge hour "Bad Request The browser (or proxy) sent a request that this server could not understand"

### ISSUE THREAD

**Issue by calliou1234** [flobz/psa_car_controller#197]
Hello,

I started a discussion and HOzo123 answered that he manipulated the code to get the command work.

But  I won´t do that and therefore I´m not sure if there is an general fault.

I have an Peugeot 208 and you tested it with the same car type.

With the command

http://192.168.178.35:4995/charge_hour?vin=VR3XXXXXXXXXXXX&hour=22&min=30

i get an error `Bad RequestThe browser (or proxy) sent a request that this server could not understand.`

Is there anything wrong with my command?

I've tried several times now but it doesn't work.

Thanks for your help
Thomas

**Comment by flobz** [comment]
it's minute not min. Can you retry with last version

**Comment by HOzo123** [comment]
Hello,
I have uploaded the last version and replaced "min" by "minute": now, it's working perfectly !
Thank you @flobz  !
