### ISSUE TITLE
Can't configure DS3 etense

### ISSUE THREAD

**Issue by am-technix** [flobz/psa_car_controller#198]
Hello,

I cannot configure my DS ; first step is OK, but URL config_otp automatically redirect to initial config page.

This is a screenshot of the end of step #1 and logs before beeing redirect to /config.

![DS_pb2021-08-07_14-54](https://user-images.githubusercontent.com/788943/128601019-200920f7-4b6d-4617-b03d-ab0bbdf14f2a.png)

![pb_my_ds2021-08-07_14-55](https://user-images.githubusercontent.com/788943/128601021-4af4a14c-9373-4096-8165-100d90c845d2.png)

My config.json file

![image](https://user-images.githubusercontent.com/788943/128601312-23fd20e5-3539-443a-ad11-2534c12336da.png)

Can I do some tests to give you more informations ?

**Comment by joszz** [comment]
Same issue here with a Citroën ë C4

**Comment by joszz** [comment]
Ah figured it out, this issue is the same;
https://github.com/flobz/psa_car_controller/issues/181

it's because of the config files being different. Starting it with below works;
python3 server.py -f config.json -c charge_config.json --web-conf1

**Comment by flobz** [comment]
Yeah I will edit the doc
