### ISSUE TITLE
decoder.py

### ISSUE THREAD

**Issue by mounik34** [flobz/psa_car_controller#2]
Bonjour, 
J'aimerais bien tester tout ceci mais le decodage du backup me donne des erreurs : 

 python3 app_decoder.py  backup.ab password
  File "app_decoder.py", line 38
    os.system(f"java -jar {script_dir}/abe-all.jar unpack {argv[1]} backup.tar {password}")
                                                                                         ^
SyntaxError: invalid syntax

**Comment by mounik34** [comment]
En supprimant le f une autre erreur : 

 File "app_decoder.py", line 70
    print(f"\nYour vehicles: {res}")
                                  ^
SyntaxError: invalid syntax

**Comment by mounik34** [comment]
En supprimant le 2eme f (ligne 70) 

Traceback (most recent call last):
  File "app_decoder.py", line 9, in <module>
    from ChargeControl import ChargeControl, ChargeControls
  File "/var/www/html/script/psa_car_controller/ChargeControl.py", line 15
    self.list: dict = {}
             ^
SyntaxError: invalid syntax

**Comment by flobz** [comment]
Avez vous une version de python supérieure à 3.6 ?

**Comment by mounik34** [comment]
3.5.3

**Comment by mounik34** [comment]
avec une 3.6.9 ca va un peu plus loin : 

`sh: 1: java: not found
Traceback (most recent call last):
  File "app_decoder.py", line 57, in <module>
    remote_refresh_token = json.loads(base64.b64decode(remote_enc))["refresh_token"]
KeyError: 'refresh_token'
`

**Comment by flobz** [comment]
il faut installer java sur sa machine

**Comment by mounik34** [comment]
Yess ;(

Avec java, meme erreur qui suit  : 

Traceback (most recent call last):
  File "app_decoder.py", line 57, in <module>
    remote_refresh_token = json.loads(base64.b64decode(remote_enc))["refresh_token"]
KeyError: 'refresh_token'

**Comment by flobz** [comment]
Avez-vous lancé une commande distantes sur votre véhicule avant de lancer la sauvegarde ?

**Comment by mounik34** [comment]
oui j'avais fait ca ... 
Je vais refaire la manip, recup la sauvegarde et je reteste ...

**Comment by flobz** [comment]
Oui ça devrait fonctionner aussi avec un émulateur. Quelle version de l'application avez-vous utilisé ? J'ai fait mes tests avec la version 1.25.2.

**Comment by mounik34** [comment]
1.26.1

**Comment by flobz** [comment]
ça doit venir de la version... Pouvez esseyer avec la version 1.25.2 ?

**Comment by mounik34** [comment]
OK, le script decode est ok avec la manip faite sur l'app v1.25.2

Puis au lancement du sreveur : 

2020-11-25 15:44:22,772 :: INFO :: server start
Traceback (most recent call last):
  File "server.py", line 89, in <module>
    myp = MyPSACC.load_config(name=args.config.name)
  File "/var/www/html/intranet/julien/flobz/MyPSACC.py", line 340, in load_config
    return MyPSACC(**json.loads(str))
TypeError: __init__() got an unexpected keyword argument 'headers'

**Comment by flobz** [comment]
Ok désolé, une erreur dans mon code, ça devrait être corrigé maintenant.

**Comment by flobz** [comment]
Peux-tu supprimer le fichier de conf test.json et le régénérer en relançant app_decoder.py

**Comment by mounik34** [comment]
Y'a du mieux : le serveur demande mail et pass ! et :+1: 
 * Serving Flask app "server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
Traceback (most recent call last):
  File "server.py", line 109, in <module>
    chc = ChargeControls.load_config(myp, name=args.charge_control)
  File "/var/www/html/intranet/julien/flobz/ChargeControl.py", line 31, in load_config
    with open(name, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'charge_control1.json'
2020-11-25 16:12:29,133 :: INFO :: Connected with result code {'session present': 0}
2020-11-25 16:12:29,134 :: INFO :: subscribe to psa/RemoteServices/to/cid/AP-ACNT2xxxx/#
2020-11-25 16:12:29,135 :: INFO :: subscribe to psa/RemoteServices/events/MPHRTServices/VIN/#

**Comment by flobz** [comment]
effectivement c'est une erreur dans la doc cette fois ci, :
lance le server avec la commande suivante: 
python3 server.py -f test.json -c charge_config1.json

**Comment by mounik34** [comment]
OK, toujours qqchose d'affiché mais une requete sur etat fonctionne ;))

* Serving Flask app "server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
Traceback (most recent call last):
  File "server.py", line 109, in <module>
    chc = ChargeControls.load_config(myp, name=args.charge_control)
  File "/var/www/html/intranet/julien/flobz/ChargeControl.py", line 36, in load_config
    charge_control_list.list[vin] = ChargeControl(psacc,vin,**el)
  File "/var/www/html/intranet/julien/flobz/ChargeControl.py", line 55, in __init__
    self.set_stop_hour(stop_hour)
  File "/var/www/html/intranet/julien/flobz/ChargeControl.py", line 66, in set_stop_hour
    self._next_stop_hour = datetime.now().replace(hour=stop_hour[0], minute=stop_hour[1], second=0)
TypeError: 'NoneType' object is not subscriptable
2020-11-25 16:19:51,952 :: INFO :: Connected with result code {'session present': 0}
2020-11-25 16:19:51,952 :: INFO :: subscribe to psa/RemoteServices/to/cid/AP-ACNT2711/#
2020-11-25 16:19:51,952 :: INFO :: subscribe to psa/RemoteServices/events/MPHRTServices/VIN  /#
127.0.0.1 - - [25/Nov/2020 16:20:41] "GET /get_vehicleinfo/VIN  HTTP/1.1" 200 -

**Comment by flobz** [comment]
Ok encore une erreur que je viens de corriger, pouvez-vous ressayer ?

**Comment by mounik34** [comment]
Super ! 
Tout roule et je recupere bien pour le moment les infos du vehicule ;))

Je ferai d'autres tests demain ... et si tu pouvais m'aiguiller pour enregistrer ces infos à intervalle regulier dans jeedom ca serait cool !

Une option pour aussi lancer et rendre accessible depuis reseau le serveur ?
 j'ai mis  ligne102 server.py : t1 = Thread(target=app.run(host='0.0.0.0', port=5000))

Julien

**Comment by flobz** [comment]
Ok super.
Je suis entrain d'ajouter la compatibilité avec la version 1.26.
Pour jeedom, je ne l'ai jamais utilisé mais en s'appuyant sur des requètes http ça devrait pas être trop compliqué.
Je vais rajouter l'option listen tu as raison.
