### ISSUE TITLE
Charge Control not working anymore

### ISSUE THREAD

**Issue by jaykijay** [flobz/psa_car_controller#201]
**Describe the bug**
/charge_now/VIN/0
control does nothing anymore. Using the offical App still works.
The same issue exists with charge_thresold.. it does not work anymore. Does 2 Retrys which fail and then stops.

**To Reproduce**
/charge_now/VIN/0
-> INFO :: {"access_token": null, "customer_id": "OV-", "correlation_id": "", "req_date": "2021-08-11T19:14:18Z", "vin": "VXKXXXXXXXXXXXX", "req_parameters": {"program": {"hour": 12, "minute": 0}, "type": "immediate"}}

**Config file**

    "client_id": "xxx",
    "client_secret": "xxxx",
    "co2_signal_api": null,
    "country_code": "DE",
    "customer_id": "OP-xxxx",
    "proxies": {
        "http": "",
        "https": ""
    },
    "realm": "clientsB2COpel",
    "refresh_token": "xxxxx-xx-xx-xxx",
    "remote_refresh_token": null,
    "weather_api": "4xxxxx5"

**Environment (please complete the following information):**
 - OS: latest Docker version

**Additional context**
Stopped working since a few days, worked fine before. App still works fine.

Update:

I added mitm as proxy and running /charge_now/VIN/0 does only trigger these two Requests which for me do not include any charge control message?:
![grafik](https://user-images.githubusercontent.com/24495677/129093965-e603fd71-382a-4f21-8985-22d82a84b106.png)

**Comment by flobz** [comment]
-> INFO :: {"access_token": null
It seems to be the problem. . It shouldn't be null

**Comment by jaykijay** [comment]
You're right.
I resetted all settings and now its workingn again. Thanks for your work :)
