### ISSUE TITLE
python3.7: can't open file 'server.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Blackei** [flobz/psa_car_controller#202]
Hi,

ich habe jetzt auch nicht die Ahnung, bekomme beim Start aber folgenden Fehler.

python3.7: can't open file 'server.py': [Errno 2] No such file or directory

**Comment by kurim** [comment]
Das sieht sehr danach aus als wäre das was du runtergeladen hast nicht vollständig, beschreib einmal wie du vorgegangen bist.
Am besten auf English damit alle mit helfen können.

**Comment by Blackei** [comment]
Hi,

i have installed Python 3.8.4 with this:

https://maker-tutorials.com/python3-pip-raspberry-pi-installieren/

and then:

sudo apt-get install python3-typing-extensions python3-pandas python3-plotly python3-paho-mqtt  python3-six python3-dateutil python3-brotli  libblas-dev  liblapack-dev gfortran python3-pycryptodome libatlas3-base python3-cryptography


Thanks for hep

Lars

**Comment by kurim** [comment]
Hi Lars,

what is included in your working folder of psa-car (screenshot)?

**Comment by Blackei** [comment]
Hi,

i have no Idea what you want, sorry....When you say my which Ordner I can make a screenshot.
Sorry Linux ist not my system ;-)

**Comment by kurim** [comment]
Basicly it should be looks like this.

![image](https://user-images.githubusercontent.com/1880220/129785676-11380b79-544c-404e-8600-4b81502fb21a.png)

Also you can follow this guide: https://youtu.be/XO7-N7G3biU
