### ISSUE TITLE
Not receiving SMS with Peugeot208 (2020)

### ISSUE THREAD

**Issue by Donixon** [flobz/psa_car_controller#204]
Not sure if it's a bug, but can't seem to find any information about it. 
I got a new Peugeot 208 (2020) and have the MyPeugeot app installed on my OnePlus8t. Logged in to it and added the car. This works all fine.
Installed PSA-CAR-CONTROLLER in Home-Assistant and logged in. Now I am at the Send SMS step, but I won't receive anything. My first thought was; how is it EVER going to send a SMS to me, when I have not put my telephone-number in the app (I'm guessing it will get the number from the PSA-account?). So I opened up the app and could add my phone-number. 

Still not getting any SMS. Am I missing something? Can't find any information about the "setup" of the app.

**Comment by flobz** [comment]
Please read the FAQ before open an issue.
