### ISSUE TITLE
weather_api issue

### ISSUE THREAD

**Issue by marcorizzi** [flobz/psa_car_controller#206]
Configured inside config.json file the weather_api with my code something like 
"weather_api": "8ab0sd617b64577c8fb59e3f059aa70c" but nothing happen on the homepage to get the weather temperature.
Double checked on the log file and no trace was found about about this topic.

Any suggestion?

**Comment by flobz** [comment]
Hello,
Do you have a list of trips?

**Comment by marcorizzi** [comment]
Yes sure I have the list of trips but into the database there's not information other then date and km.
