### ISSUE TITLE
Can't control climate

### ISSUE THREAD

**Issue by BrunoN17** [flobz/psa_car_controller#209]
Hi! I have the psa_car_controller installed into my home assistant using the addon.
I can see the car status by using sensors, but for some reason I can't send the pre-conditioning commands to the car. Nothing happens when I execute the command.

After executing this is what I get in the log:

172.30.32.1 - - [28/Aug/2021 01:45:56] "GET /get_vehicleinfo/<VIN HIDDEN>?from_cache=1 HTTP/1.1" 200 -

Do you know what can be wrong?

Thanks!

**Comment by BrunoN17** [comment]
Hi again

I believe I might have found the issue, just don't know how to fix it

When I'm starting the addon I receive the following error:
2021-08-28 02:14:57,900 :: ERROR :: remote_refresh_token isn't defined

How can I get the token?

Thanks!

**Comment by flobz** [comment]
go to /config_otp  page.
