### ISSUE TITLE
app_decoder.py : can't get credentials due to 'dealers': {} empty

### ISSUE THREAD

**Issue by jlayec** [flobz/psa_car_controller#21]
First of all thanks for the great job!

**Describe the bug**
using the new release available branch master
Can't initialize the test.json file
Error due to empty dealers': {} in the json answer

**To Reproduce**
```
python3 app_decoder.py ../com.psa.mym.mypeugeot_1.27.apk
APK loading...
Requested API level 29 is larger than maximum we have, returning API level 28 instead.
APK loaded !
mypeugeot email: xxxx
mypeugeot password: xxxx
What is the car api realm : clientsB2CPeugeot, clientsB2CCitroen, clientsB2CDS, clientsB2COpel, clientsB2CVauxhall
clientsB2CPeugeot
What is your country code ? (ex: FR, GB, DE, ES...)
FR
Traceback (most recent call last):
  File "app_decoder.py", line 124, in <module>
    customer_id = res_dict["dealers"]["apv"]["data"]["Brand"] + "-" + res_dict["id"]
KeyError: 'apv'
```

**json output leading to the bug**
{'id': 'xxxxxxxxxxxxxxxxx', 'language': 'fr', 'country': 'FR', 'profile': {'email': 'xxxxxxxxxx@xxxxx.xxxxx', 'civility': 'xxxx', 'last_name': 'xxxxx', 'first_name': 'xxxxx'}, 'dealers': {}, 'vehicles': [{'vin': 'xxxxxxxxxxxxxx', 'lcdv': 'xxxxxxxxxxxxxx', 'short_label': 'xxxxxxxx', 'warranty_start_date': xxxxxxxxxxxxxxx, 'visual': 'https://visuel3d-secure.peugeot.com/V3DImage.ashx?xxxxxxxxxxxxxxxxxxxx', 'eligibility': ['xxxxx', 'xxxx', 'xxxxx', 'xxxx', 'xxxx', 'xxxxx'], 'attributes': ['xxxxx', 'xxxxx', 'xxxxx', 'wxxxx', 'xxxxx'], 'type_vehicle': x, 'external_ws_status': 'OK', 'mileage': {'value': xxxx, 'source': 1, 'timestamp': xxxxxxxxxx}}], 'settings_update': xxxxxx, 'terms_service': {'cguForValidation': 'xxxx', 'lastCguAlreadyValidated': 'xxxxx'}, 'early_adopter': [], 'service_state': ['REMOTELEV'], 'cgu_validation': True}

**Comment by flobz** [comment]
Ok it should be fixed now : 6bb3c93a1e837c4cd792078258fc27a1aa568094.

**Comment by jlayec** [comment]
Excellent job! Thanks :)

`Success !!!`

**Comment by flobz** [comment]
Thanks
