### ISSUE TITLE
Statistics do not update

### ISSUE THREAD

**Issue by maivorbim** [flobz/psa_car_controller#210]
**Describe the bug**
Average consumption and electricity consumption do not update, despite performing multiple trips and charges.

**Environment (please complete the following information):**
Latest HomeAssistant running PSA Car Controller v2.4.4
 - Brand and model of car
Peugeot e208

![2](https://user-images.githubusercontent.com/34894081/131217963-7e7e6e38-f49f-4410-85c8-c8d3093a22cc.png)
![1](https://user-images.githubusercontent.com/34894081/131217964-057cec49-9484-467c-811c-e972e28199f1.png)

**Comment by flobz** [comment]
Do you have some errors?

**Comment by maivorbim** [comment]
Do not see any errors. This is what shows up in the log once I access the dashboard:

172.30.32.1 - - [28/Aug/2021 16:17:21] "GET / HTTP/1.1" 200 -
172.30.32.1 - - [28/Aug/2021 16:17:21] "GET /assets/clientside.js?m=1628345176.0 HTTP/1.1" 304 -
172.30.32.1 - - [28/Aug/2021 16:17:21] "GET /_dash-layout HTTP/1.1" 200 -
172.30.32.1 - - [28/Aug/2021 16:17:21] "GET /_dash-dependencies HTTP/1.1" 200 -
172.30.32.1 - - [28/Aug/2021 16:17:21] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [28/Aug/2021 16:17:21] "GET /assets/images/consumption.svg HTTP/1.1" 304 -
172.30.32.1 - - [28/Aug/2021 16:17:21] "GET /assets/images/electricity%20bill.svg HTTP/1.1" 304 -
172.30.32.1 - - [28/Aug/2021 16:17:21] "GET /assets/images/pollution.svg HTTP/1.1" 304 -
172.30.32.1 - - [28/Aug/2021 16:17:21] "GET /assets/images/battery-charge-line.svg HTTP/1.1" 304 -
172.30.32.1 - - [28/Aug/2021 16:17:21] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [28/Aug/2021 16:17:21] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [28/Aug/2021 16:17:21] "POST /_dash-update-component HTTP/1.1" 204 -
172.30.32.1 - - [28/Aug/2021 16:17:21] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [28/Aug/2021 16:17:22] "GET /style.json HTTP/1.1" 200 -
172.30.32.1 - - [28/Aug/2021 16:17:22] "GET /assets/sprites/osm-liberty@2x.json HTTP/1.1" 304 -
172.30.32.1 - - [28/Aug/2021 16:17:22] "GET /assets/sprites/osm-liberty@2x.png HTTP/1.1" 304 -
172.30.32.1 - - [28/Aug/2021 16:17:25] "GET / HTTP/1.1" 200 -
172.30.32.1 - - [28/Aug/2021 16:17:25] "GET /assets/clientside.js?m=1628345176.0 HTTP/1.1" 304 -
172.30.32.1 - - [28/Aug/2021 16:17:25] "GET /_dash-layout HTTP/1.1" 200 -
172.30.32.1 - - [28/Aug/2021 16:17:25] "GET /_dash-dependencies HTTP/1.1" 200 -
172.30.32.1 - - [28/Aug/2021 16:17:26] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [28/Aug/2021 16:17:26] "GET /assets/images/consumption.svg HTTP/1.1" 304 -
172.30.32.1 - - [28/Aug/2021 16:17:26] "GET /assets/images/pollution.svg HTTP/1.1" 304 -
172.30.32.1 - - [28/Aug/2021 16:17:26] "GET /assets/images/battery-charge-line.svg HTTP/1.1" 304 -
172.30.32.1 - - [28/Aug/2021 16:17:26] "GET /assets/images/electricity%20bill.svg HTTP/1.1" 304 -
172.30.32.1 - - [28/Aug/2021 16:17:26] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [28/Aug/2021 16:17:26] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [28/Aug/2021 16:17:26] "POST /_dash-update-component HTTP/1.1" 204 -
172.30.32.1 - - [28/Aug/2021 16:17:28] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [28/Aug/2021 16:17:28] "GET /style.json HTTP/1.1" 200 -
172.30.32.1 - - [28/Aug/2021 16:17:28] "GET /assets/sprites/osm-liberty@2x.json HTTP/1.1" 304 -
172.30.32.1 - - [28/Aug/2021 16:17:28] "GET /assets/sprites/osm-liberty@2x.png HTTP/1.1" 304 -

**Comment by maivorbim** [comment]
Problem resolved on its own after 10 trips.
