### ISSUE TITLE
Docker - Dashboard unavailable (components are missing)

### ISSUE THREAD

**Issue by gino54** [flobz/psa_car_controller#217]
**Description of the bug**
Unable to load the dashboard.
Some needed components are not found. 
You will find some URLs below : 
https://unpkg.com/dash-core-components@2.0.0/dash_core_components/dash_core_components.js
https://unpkg.com/dash-table@5.0.0/dash_table/bundle.js

**To Reproduce**
I just create and start a new docker based on the latest version available : 
`docker run -d -ti --name psa_car_controller_e208   --publish 5050:5000   -v /home/pi/psa_car_controller/config:/config   --restart unless-stopped   flobz/psa_car_controller`

**Environment (please complete the following information):**
Tested on a Raspberry Pi and on MacOs with flobz/psa_car_controller:latest

<img width="1440" alt="Capture d’écran 2021-09-05 à 18 43 18" src="https://user-images.githubusercontent.com/1218181/132134756-8cea8f32-72af-424e-ae14-9154fbdb5469.png">

**Comment by maivorbim** [comment]
Same problem with v.2.4.5 release

**Comment by jaykijay** [comment]
It is working again now as the unkpg Urls are available now.
This seemed to be a Problem on unpkgs Site.

**Comment by Cassiopea1** [comment]
Yesterday evening worked for me also. I could input my account and car info. After a few trips today, I have also data in the web ui, but the sensors and switches are unavailable (it is the first installation for me). Ideas? Thanks.

**Comment by flobz** [comment]
Ok I close the issue.
@Cassiopea1 please open a ticket with more informations

**Comment by Cassiopea1** [comment]
@flobz No need for another ticket. I've used the IP address of my RPi in the sensor configuration and not the one specified in the Add-on log (as "dreimer1986" mentioned).
May I suggest you to add this peace of information to the  "HomeAssistant - Peugeot Integration" README.md?
`Look for "IPofTheSoftware" in the "* Running on http://172.30.33.5:5000/ (Press CTRL+C to quit)" line in the Add-on log after you start the Add-on.`
