### ISSUE TITLE
Other api information

### ISSUE THREAD

**Issue by atze09** [flobz/psa_car_controller#22]
Can you give us a short description or tutorial how to control other things from the api (lights) or get other information from the api( sensor states?)
I would like to implement more information into my home assistant.
Thank you in advance

**Comment by flobz** [comment]
Look at the callback.py file.

If you want to add endpoint to the api , preconditioning function is a good example

**Comment by Tiph60** [comment]
http://localhost:5000/preconditioning/YOURVIN/1 -> Start the preconditioning BUT it remove any Programmed preconditioning...
callback.py file say "activate" (and no "1") argument but nothing else with it

**Comment by flobz** [comment]
Please open an other issue.
I didn't implement programmed preconditionning. The request to start precontionning must also contain programmed conditionning parameters and for now it send "no programmed conditioning".
