### ISSUE TITLE
Dashboard is damaged

### ISSUE THREAD

**Issue by CWfFO** [flobz/psa_car_controller#224]
Hi,
my car was damaged. It was at the garage. During this time the server was stopped. After it was fixed and i got it back i started the server again in record mode. Now my dash damaged and looks like this.

**Describe the bug**
Dashboard damaged

**To Reproduce**
1. access debug
2. when the bug append ?
3. persistent

**Config file**
Give the anonymize content of the config file

**Environment (please complete the following information):**
 - OS: raspbian
 - Android app Version 1.27.1
 - corsa-e
 - 2.4.5

**Additional context**
Add any other context about the problem here

![1](https://user-images.githubusercontent.com/79962883/133841074-2abdb14a-3950-4d7e-86ef-74aee461369b.PNG)
![2](https://user-images.githubusercontent.com/79962883/133841073-f88f5e4c-2a51-434a-bfca-83ee16f1c244.PNG)
.

**Comment by flobz** [comment]
Give server log and browser console log please.

**Comment by CWfFO** [comment]
Not sure what you need in detail. Activity.log?

Here is a screenshot from browser console
![3](https://user-images.githubusercontent.com/79962883/133842126-cb8c048f-daa3-4c58-9a46-eab45b13bd7a.PNG)
g?

**Comment by CWfFO** [comment]
I hope this it is:  

 CGroup: /system.slice/psa_car_controller.service
           └─13138 /usr/bin/python3 server.py -f test.json -c charge_config.json -r -l 192.168.99.13 
Sep 17 21:40:57 pike python3[13138]: 192.168.99.38 - - [17/Sep/2021 21:40:57] "GET /assets/images/battery-charge-line.svg HTTP/1.1" 200 -
Sep 17 21:40:57 pike python3[13138]: 192.168.99.38 - - [17/Sep/2021 21:40:57] "GET /assets/images/electricity%20bill.svg HTTP/1.1" 200 -
Sep 17 21:40:57 pike python3[13138]: 192.168.99.38 - - [17/Sep/2021 21:40:57] "GET /control?header=false HTTP/1.1" 200 -
Sep 17 21:40:58 pike python3[13138]: 192.168.99.38 - - [17/Sep/2021 21:40:58] "GET /assets/clientside.js?m=1631827245.0 HTTP/1.1" 200 -
Sep 17 21:40:59 pike python3[13138]: 192.168.99.38 - - [17/Sep/2021 21:40:59] "GET /_dash-layout HTTP/1.1" 200 -
Sep 17 21:40:59 pike python3[13138]: 192.168.99.38 - - [17/Sep/2021 21:40:59] "GET /_dash-dependencies HTTP/1.1" 200 -
Sep 17 21:40:59 pike python3[13138]: 192.168.99.38 - - [17/Sep/2021 21:40:59] "POST /_dash-update-component HTTP/1.1" 200 -
Sep 17 21:40:59 pike python3[13138]: 192.168.99.38 - - [17/Sep/2021 21:40:59] "GET /assets/images/sync.svg HTTP/1.1" 200 -
Sep 17 21:40:59 pike python3[13138]: 192.168.99.38 - - [17/Sep/2021 21:40:59] "GET /assets/images/battery-charge.svg HTTP/1.1" 200 -
Sep 17 21:40:59 pike python3[13138]: 192.168.99.38 - - [17/Sep/2021 21:40:59] "GET /assets/images/mileage.svg HTTP/1.1" 200 -

**Comment by flobz** [comment]
Did you try another browser?

**Comment by CWfFO** [comment]
Mobile, Tablet, Laptop (Chrome / Firefox / Edge), all the same. Also with disabled pi-hole, delete cockies. More ideas i don't have.

**Comment by CWfFO** [comment]
Every info is there. Only the format of the page is horrible

**Comment by CWfFO** [comment]
Any further ideas?

**Comment by CWfFO** [comment]
The network tab shows me that https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css is not working correct. could this be my problem?
If i open it in the browser i get:
"Mit dieser XML-Datei sind anscheinend keine Style-Informationen verknüpft. Nachfolgend wird die Baum-Ansicht des Dokuments angezeigt. "
"There does not appear to be any style information associated with this XML file. The following is the tree view of the document. "

Latest version i have now.
No docker image. 

![4](https://user-images.githubusercontent.com/79962883/134133848-76072e40-e206-4a09-93c3-d3a420a5296c.PNG)

**Comment by flobz** [comment]
Ok so there is a problem to get this fille.
For me this url is working...
You have a proxy? 
In any case not a problem from the app.

**Comment by CWfFO** [comment]
I found it: The ip for stackpath.bootstrapcdn.com has changed. I had an entry in a host file. Thanks for your help
