### ISSUE TITLE
[New Car model] Citroen C5 Aircross Hybrid

### ISSUE THREAD

**Issue by frozengpu** [flobz/psa_car_controller#227]
I have a "Can't get car model" error.
Information to add my car model to the app:
- Brand: Citroen
- Model: C5 Aircross Hybrid
- First ten letter of my VIN:  VR7A4DGZSM
- Useable Electric capacity in kw: 13.2
- Fuel capacity in liter: 43

**Comment by flobz** [comment]
added c414fa56d6195a5a8a6a879801a95858d5a30f04
