### ISSUE TITLE
Home Assistant  - Several Issues

### ISSUE THREAD

**Issue by DavidFFerreira** [flobz/psa_car_controller#231]
In home assistant, the automations stop work after last update. Soo, I cannot get any info using automation from http://myip/psa/vin...etc...
In PSA Controller addon, I get a few things, but today my card disapear in Control tab
I errors and warning in logs

`2021-09-27 09:29:52,691 :: WARNING :: Can't get language
/psa_car_controller/web/view/views.py:8: UserWarning: 
The dash_core_components package is deprecated. Please replace
`import dash_core_components as dcc` with `from dash import dcc`
  import dash_core_components as dcc`

`2021-09-27 09:30:08,849 :: WARNING :: charge begin but API isn't updated`
`2021-09-27 09:32:09,774 :: WARNING :: Disconnected with result code 1`

![image](https://user-images.githubusercontent.com/32928749/134875197-b1391487-b660-480c-8ee0-8f89be8b2394.png)
![image](https://user-images.githubusercontent.com/32928749/134875281-cb089f6a-c961-4a63-a0c6-66c3df3e42bf.png)

![image](https://user-images.githubusercontent.com/32928749/134873356-dfc52011-7689-4d1c-a0c6-62b071df201c.png)

**Comment by DavidFFerreira** [comment]
ok maybe I did find out why this is not working
the code was deprecated from PSA =/

![image](https://user-images.githubusercontent.com/32928749/134891767-5e8208c3-91e4-4315-bcbe-9c7390a44775.png)

**Comment by flobz** [comment]
Close as it doesn't follow the bug template

**Comment by DavidFFerreira** [comment]
or you just dont want to solve =)
