### ISSUE TITLE
Config OTP - SSL Certificate verify

### ISSUE THREAD

**Issue by gino54** [flobz/psa_car_controller#234]
**Describe the bug**
I've an error when I submit de config_otp form.

![Capture d’écran 2021-09-24 à 19 30 41](https://user-images.githubusercontent.com/1218181/134942050-e2084317-2c6f-40fd-87e8-14750bc79f77.png)

**To Reproduce**
1. what command did you use

`docker pull flobz/psa_car_controller
docker run -d -ti --name psa_car_controller   --publish 5050:5000   -v /home/pi/psa_car_controller/config:/config   --restart unless-stopped   flobz/psa_car_controller`

2. when the bug append ?
When I submit the form on the http://192.168.0.32:5050/config_otp page

3. Does it persist after restarting the program? 
yes

4. Does it persist after recreate config by going to http://server_address:port/log/config? 
yes

**Config file**
`{
    "abrp": {
        "abrp_enable_vin": [],
        "token": ""
    },
    "client_id": "XXXXXXXXXSEAMS TO BE CORRECTXXXXXXXXXX",
    "client_secret": "XXXXXXXXSEAMS TO BE CORRECTXXXXXXXXXXX",
    "co2_signal_api": null,
    "country_code": "FR",
    "customer_id": "AP-ACNTXXXXXSEAMS TO BE CORRECTXXXXXX",
    "proxies": {
        "http": "",
        "https": ""
    },
    "realm": "clientsB2CPeugeot",
    "refresh_token": "xxxxxxxxxxxxxxxSEAMS TO BE CORRECTxxxxxxxxxx",
    "remote_refresh_token": "xxxxxxxxxxxxSEAMS TO BE CORRECTxxxxxxxxxxxxx",
    "weather_api": null
}`
Fields seams to be correctly completed.

**Environment (please complete the following information):**
 - OS: MacOS
 - Brand and model of car : Peugeot e208
 - Application version (commit number, branch) docker latest (probably 2.5.1. Maybe you can add the version number on a footer on the app ;-) )
 - Logs from server 
`2021-09-27 16:00:19,328 :: INFO :: save config change
Traceback (most recent call last):
  File "/psa_car_controller/server.py", line 15, in <module>
    conf.load_app()
  File "/psa_car_controller/libs/config.py", line 103, in load_app
    self.start_remote_control()
  File "/psa_car_controller/libs/config.py", line 63, in start_remote_control
    self.myp.start_mqtt()
  File "/psa_car_controller/my_psacc.py", line 341, in start_mqtt
    self.mqtt_client.connect(MQTT_SERVER, 8885, 60)
  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 941, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 1104, in reconnect
    sock.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)`

Thank you

**Comment by flobz** [comment]
look at #135 
It's a temporary error caused by PSA server

**Comment by flobz** [comment]
I updated the FAQ to explain this issue : 9947be8125ff97bd19452fa51ae36f0c84c64995
