### ISSUE TITLE
Disable stop charging when reaching 100% threshold

### ISSUE THREAD

**Issue by maivorbim** [flobz/psa_car_controller#235]
**Describe the bug**
It appears that PSA Car Controller sends a stop charge command (deferred charging) when the car reaches 100% charge threshold. However, this stop charge command is sent prematurely, as even after the car reaches 100% it still has about 15 minutes of charging time remaining untill actually completely full, according to MyPeugeot App.

Expected behaviour: the stop charge command (deferred charging) should be sent only if the threshold set by the user is different from 100%.

@flobz could you please check the code whether the stop charge command is sent even in case the threshold is set to 100% ?

**Environment**
 - OS: Home Assistant
 - Peugeot e208
 - PSA CC app v2.5.1

**Log**
2021-10-01 08:35:22,518 :: INFO :: charging status of VR###### is InProgress, battery level: 100
2021-10-01 08:35:22,519 :: INFO :: Charge threshold is reached, stop the charge

**Comment by flobz** [comment]
Thank. I will look at it.

**Comment by flobz** [comment]
done 42d5e06399b5f50c0ac2e909868fb47ddc2c6a5f

**Comment by maivorbim** [comment]
Great! Thanks!
