### ISSUE TITLE
Certificate verify failed

### ISSUE THREAD

**Issue by christof62** [flobz/psa_car_controller#260]
PSA Car Controller home assistant plugin stops during startup after update from 2.5.1 to 2.5.3

After deinstallation and installation registration could be started but reported bug after entering code and PIN.
Restarting addon always leads to following failure:

Containerised psa_car_controller loading...
2021-10-25 08:57:06,431 :: INFO :: save config change
2021-10-25 08:57:07,052 :: INFO :: ["{'vin': 'VX.....', 'vehicle_id': '...', 'label': 'corsa-e', 'brand': 'C', 'abrp_name': 'opel:corsae:20:50', 'battery_power': 46, 'fuel_capacity': 0, 'max_elec_consumption': 70, 'max_fuel_consumption': 0}"]
2021-10-25 08:57:07,378 :: INFO :: save config change
Traceback (most recent call last):
  File "/psa_car_controller/server.py", line 22, in <module>
    conf.load_app()
  File "/psa_car_controller/libs/config.py", line 105, in load_app
    self.start_remote_control()
  File "/psa_car_controller/libs/config.py", line 63, in start_remote_control
    self.myp.start_mqtt()
  File "/psa_car_controller/my_psacc.py", line 341, in start_mqtt
    self.mqtt_client.connect(MQTT_SERVER, 8885, 60)
  File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)

**Comment by dreimer1986** [comment]
I did as recommended now and forked the repo https://github.com/flobz/psacc-ha to https://github.com/dreimer1986/psacc-ha. I changed the name for fun, changed the link to the repo and the version. Installed it, configured it, set the port 5000 again and rebooted a few times. Still works fine here.

**Comment by egpall** [comment]
> Hice lo recomendado ahora y bifurqué el repositorio https://github.com/flobz/psacc-ha a https://github.com/dreimer1986/psacc-ha . Cambié el nombre por diversión, cambié el enlace al repositorio y la versión. Lo instalé, lo configuré, configuró el puerto 5000 nuevamente y reinició varias veces. Todavía funciona bien aquí.

I have done it too and for now everything is fine, and the configuration without any SSL failure or anything

**Comment by albenex** [comment]
trying again for the Nst time:
now instead using my own forked repo I'm using @dreimer1986 's one: https://github.com/dreimer1986/psacc-ha
logged in. 
OTP received and submitted along with PIN:
as usual first submit has SSL error: 
![image](https://user-images.githubusercontent.com/2207059/139966953-33d959d3-df2c-4f49-b3b9-1ba8e5ad298e.png)
then second submit goes well:
![image](https://user-images.githubusercontent.com/2207059/139966978-3a6417d3-76e4-4f16-89ce-c2b0b2b0f876.png)
and as stated on prev posts on firs run i've updated data:
![image](https://user-images.githubusercontent.com/2207059/139967005-bdbfbe21-4a43-4905-816b-d88310116c38.png)

then I reboot add-on and it crashes:
![image](https://user-images.githubusercontent.com/2207059/139967069-83d07542-32cf-4605-9bf9-0a042557df2e.png)

also, I try to se local tcp port to 5000 and reboot add-on to confirm changes: same SSL issue.

then, following @camuxx86  advice i search and move "otp.bin" file inside psacc-HA addon:
`root@alpi4:~# cd /
root@alpi4:/# find | grep "otp.bin"
./usr/lib/firmware/ath6k/AR6003.1/hw2.1.1/otp.bin
./usr/lib/firmware/ath6k/AR6003/hw2.1.1/otp.bin
./usr/lib/firmware/ath6k/AR6003/hw2.0/otp.bin.z77
./usr/lib/firmware/ath6k/AR6003/hw1.0/otp.bin.z77
./usr/share/hassio/addons/data/8be7c74b_psacc/otp.bin
root@alpi4:/# mv /usr/share/hassio/addons/data/8be7c74b_psacc/otp.bin /usr/share/hassio/addons/data/8be7c74b_psacc/otp.bin.back
root@alpi4:/#`

restart add-on et voilà, no SSL error:
![image](https://user-images.githubusercontent.com/2207059/139967394-10ed667e-e7c0-4e41-8dca-f222300ff646.png)

but:
![image](https://user-images.githubusercontent.com/2207059/139967411-34764b9d-f04e-49ab-8d33-81dfc9ac0ccc.png)

interface is basically empty.

my gear:
Host: raspberry pi4
OS: raspbian stretch
SW: Docker + Home Assistant Supervised + psacc-HA 2.5.1 (same behavior on .2 and .3)
car: Peugeot e-208
locale: IT

**Comment by flobz** [comment]
If the interface is empty is because remote control doesn't work.

**Comment by Hayajiro** [comment]
According to Peugeot, the SSL Error on MQTT is in the process of being fixed. For me, for example, it's working again.

**Comment by camuxx86** [comment]
@albenex I was trying to fix my last post but I dropped it for error.
Anyway, moving OTP.BIN make the service start but doesn't update the data...
I restored the original position of otp.bin and I'm in your same situation...(again)

**Comment by albenex** [comment]
now, without any action performed on my side, i have some information on interface.. and noticed that commands (like refresh etc) are not working. however if i launch http request with "get_vehicleinfo/VIN" it's updated. 
not much but better than nothing

**Comment by slashbv** [comment]
for me running in container still doesn't work, the container doesn't start

Traceback (most recent call last):
  File "/psa_car_controller/server.py", line 22, in <module>
    conf.load_app()
  File "/psa_car_controller/libs/config.py", line 105, in load_app
    self.start_remote_control()
  File "/psa_car_controller/libs/config.py", line 63, in start_remote_control
    self.myp.start_mqtt()
  File "/psa_car_controller/my_psacc.py", line 341, in start_mqtt
    self.mqtt_client.connect(MQTT_SERVER, 8885, 60)
  File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)

**Comment by albenex** [comment]
> for me running in container still doesn't work, the container doesn't start


please read all posts below

**Comment by bbr111** [comment]
Same problem here. install docker container.
Works until reboot:

now this error:
Traceback (most recent call last):
  File "/psa_car_controller/server.py", line 22, in <module>
    conf.load_app()
  File "/psa_car_controller/libs/config.py", line 105, in load_app
    self.start_remote_control()
  File "/psa_car_controller/libs/config.py", line 63, in start_remote_control
    self.myp.start_mqtt()
  File "/psa_car_controller/my_psacc.py", line 341, in start_mqtt
    self.mqtt_client.connect(MQTT_SERVER, 8885, 60)
  File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)

**Comment by PatrikNorrgard** [comment]
How can it work the first time, but not subsequent times? What changes between initial setup and a reboot? Surely the remote servers certificate is not changing between reboots?

**Comment by flobz** [comment]
Please update to v2.5.4. It should fixed the certificate issue.
The problem was related to the Docker image.

**Comment by Freezman31** [comment]
Worked for me !

**Comment by flobz** [comment]
Wonderful ! :)

**Comment by albenex** [comment]
confirmed working also for me.
just had to use my own fork of spaccabit-HA with "2.5.4” inside config.json

tried rebooting docker couple times and it just works. 
great work

**Comment by DreamT80** [comment]
@flobz , that sounds great! Can you pekade update the HA repo as well? (Sorry if this opens the issue again).

**Comment by flobz** [comment]
Yes I forgot!

**Comment by DreamT80** [comment]
Works now :). And the plugin works great now as well!

**Comment by maivorbim** [comment]
Works great! Thank you flobz!

**Comment by egpall** [comment]
Thanks flobz!!!!
