### ISSUE TITLE
[New Car model] N5008 GT-Line

### ISSUE THREAD

**Issue by alvaro-duarte** [flobz/psa_car_controller#264]
I have a "code":40410,"message":"No vehicule found"
Information to add my car model to the app:
- Brand: Peugeot
- Model: N5008 GT-LINE 1.6L BLUEHDI 120 S&S EAT6
- First ten letter of my VIN:  VF3MCBHZWJ
- Useable Electric capacity in kw: 0
- Fuel capacity in liter: 60

**Comment by flobz** [comment]
added with dbea1db
