### ISSUE TITLE
[New Car model] 508 SW 2.0 HDI

### ISSUE THREAD

**Issue by alvaro-duarte** [flobz/psa_car_controller#265]
I have a "Can't get car model" error.
Information to add my car model to the app:
- Brand: Peugeot
- Model: 508 SW 2.0 HDI 163CV
- First ten letter of my VIN: VF38ERHH
- Useable Electric capacity in kw: 0
- Fuel capacity in liter: 72

**Comment by flobz** [comment]
added with dbea1db
