### ISSUE TITLE
Stopped capture trips and charges

### ISSUE THREAD

**Issue by kurim** [flobz/psa_car_controller#266]
**Describe the bug**
For some reason it stop to capture trips and charge, also initial currently I need to run "get_vehicleinfo" to get the "get_control_tabs" fixed

**To Reproduce**
1. what command did you use:  -r -d --web-conf -l 192.168.xxx.xx
2. when the bug append ? Since 10-30
3. Does it persist after restarting the program? Yes
4. Does it persist after recreate config by going to http://server_address:port/config? Yes (I do a complete reinstall)

**Config file**
```
{
    "abrp": {
        "abrp_enable_vin": [
            "VXKxxxxxxxxxxxxxx"
        ],
        "token": "31e33016-xxxx-456b-8cf0-xxxxxxxxxxxx"
    },
    "client_id": "07364655-xxxx-4194-8158-xxxxxxxxxxxx",
    "client_secret": "xxxx",
	"co2_signal_api": "c1ebf1xxxxxxxxxx",
    "country_code": "DE",
    "customer_id": "OP-ACNT200007451195",
    "customer_id": "OP-ACNT20000xxxxxxx",
    "proxies": {
        "http": "",
        "https": ""
    },
    "realm": "clientsB2COpel",
    "refresh_token": "69446ad9-xxxx-4bcd-a134-xxxxxxxxxxxx",
    "remote_refresh_token": "f05c9e6b-xxxx-4f1f-80d0-xxxxxxxxxxxx",
    "weather_api": "387fb03f95c279xxxxxxxxxxxxxxxxxx"
}
```

**Environment (please complete the following information):**
 - OS: Linux 5.10.63-v7+
 - Opel Corsa-e
 - Git: Master also tried 2.5.3
 - Log from http://server_address:port/log and browser console log:
 There is nothing mentioned about it...

**Additional context**
I need to restart psa_car_controller because it crashed on charging event as mentioned here #239

Sidenote: Data on tronity still works correctly

**Comment by flobz** [comment]
-R REFRESH, --refresh REFRESH
                        refresh vehicles status every x min

**Comment by kurim** [comment]
basically it was not required initially did you change it that it is required?
