### ISSUE TITLE
[New Car model] DS7 Crossback e-tense

### ISSUE THREAD

**Issue by ghiki** [flobz/psa_car_controller#273]
I have a "Can't get car model" error.
Information to add my car model to the app:
- Brand: DS
- Model: DS7  Crossback e-tense 4x4
- First ten letter of my VIN:  VR1J45GBUM
- Useable Electric capacity in kw: 13.2
- Fuel capacity in liter: 43

**Comment by flobz** [comment]
added with dbea1db
