### ISSUE TITLE
[New Car model] my model

### ISSUE THREAD

**Issue by piposhub** [flobz/psa_car_controller#280]
I have a "No Vehicle fondl" error. But I can see my vehicle in mobile App or services-store.peugeot.sk
Information to add my car model to the app:
- Brand: Peugeot
- Model: 3008
- First ten letter of my VIN:  VF3MJEHZRJ
- Useable Electric capacity in kw: NaN
- Fuel capacity in liter: 53

**Comment by flobz** [comment]
Added in last version
