### ISSUE TITLE
Error "local variable 'customer_id' referenced before assignment"

### ISSUE THREAD

**Issue by ProtossBlaster** [flobz/psa_car_controller#281]
**Describe the bug**
When i try to configure the PSA Car Controller  Ver 2.5.4 i receive this error

"local variable 'customer_id' referenced before assignment"

I have removed and reistalled the PSA Car controller on Home Assistant without result 

![Schermata 2021-11-23 alle 16 48 24](https://user-images.githubusercontent.com/43983380/143061457-07e16456-4a2a-4ff0-86fa-b65219ff0750.png)

**Comment by egpall** [comment]
It happens exactly the same

**Comment by show2go** [comment]
Yes, i have the same error,
i tried it on different installs
Home Assistant, RPI3, and Virtualbox with debian

**Comment by p-rintz** [comment]
The exact error in logs is the following:

```
2021-11-23 23:30:24,927 :: ERROR :: Traceback (most recent call last):
  File "/psa_car_controller/app_decoder.py", line 107, in firstLaunchConfig
    res_dict = res2.json()["success"]
KeyError: 'success'
{"code":"495", "message": "Invalid or expired client certificate"}
```

**Comment by Dragonfly-terra** [comment]
I don't know if it is car-brand related?
But I have tested it in docker and Home assistant but I am running in same issue when I select peugeot.

**Comment by ProtossBlaster** [comment]
> I don't know if it is car-brand related?
> But I have tested it in docker and Home assistant but I am running in same issue when I select peugeot.

With the last version 2.5.4 there is a problem, with old version haven't a problem

**Comment by flobz** [comment]
Unfortunately I have the same issue. 
It's a PSA server issue.
Can someone try to do a fresh install of MyPeugeot(or any other brand) on a smartphone and tell me if it works  well ?

**Comment by flobz** [comment]
> > I don't know if it is car-brand related?
> > But I have tested it in docker and Home assistant but I am running in same issue when I select peugeot.
> 
> With the last version 2.5.4 there is a problem, with old version haven't a problem

I just tried 2.5.0 without sucess...

**Comment by ProtossBlaster** [comment]
> Unfortunately I have the same issue.
> It's a PSA server issue.
> Can someone try to do a fresh install of MyPeugeot(or any other brand) on a smartphone and tell me if it works well ?

I have try to remove and installed MyPeugeot  on Andrid Phone and working fine

**Comment by Dragonfly-terra** [comment]
> Unfortunately I have the same issue. It's a PSA server issue. Can someone try to do a fresh install of MyPeugeot(or any other brand) on a smartphone and tell me if it works well ?

>I have try to remove and installed MyPeugeot on Andrid Phone and working fine

Tested with 2 android phones (one which didn't have the MyPeugeot app installed) and both are working.

**Comment by flobz** [comment]
Ok thanks for your help. I work on the fix.

**Comment by flobz** [comment]
Fixed with last version.

**Comment by STaN33130** [comment]
Hello ! Thank you for your job. Now i have this error : Invalid password or PKCS12 data

**Comment by show2go** [comment]
Hi, and thanks for your great work!
i tried it on Home Assistant and i also get the same  failure: Invalid password or PKCS12 data

on a RPI3 i get
Traceback (most recent call last): File "/home/pi/psa_car_controller-master/app_decoder.py", line 109, in firstLaunchConfig customer_id = BRAND[package_name]["brand_code"] + "-" + res_dict["id"] KeyError: 'id' {"success":{"language":"fr","country":"FR","profile":{"email":""},"dealers":{},"vehicles":[],"settings_update":1636983910,"terms_service":{"cguForValidation":"40","lastCguAlreadyValidated":"40"},"early_adopter":[],"service_state":[],"cgu_validation":false}}

thanks

**Comment by flobz** [comment]
What is your car brand?

**Comment by STaN33130** [comment]
For me Peugeot

**Comment by Dragonfly-terra** [comment]
First of all thank you Flobz for your work.
I have uninstalled the add-on and then reïnstalled it again. I get the same error: Invalid password or PKCS12 data

When I looked at the app_decoder.py file (in the Diff and Merged folder on my home assistant I found out that the app_decoder.py still has the old data (without the committed changes). (I don't know if is normal)

When I put the changes in the app_decoder.py by hand I get a error like show2go describes.

If there is anything I can test for you please let me know. (My knowledge is a bit limited but I will do anything to help)

Thank you again flobz

**Comment by show2go** [comment]
Mine is Opel
thx

**Comment by ProtossBlaster** [comment]
> Hello ! Thank you for your job. Now i have this error : Invalid password or PKCS12 data (my password is ok)

It happens exactly the same

**Comment by flobz** [comment]
I forget to update add-on repository. Now you should be able to update the add-on and login should work.

**Comment by p-rintz** [comment]
I updated to the newest 2.5.5 version and it is currently throwing the following error:
(I input 'DE' as country code btw, as I can see 'FR' in the error code for some reason)
Brand: Peugeot

```
2021-11-25 21:56:29,691 :: ERROR :: Traceback (most recent call last):
  File "/psa_car_controller/app_decoder.py", line 109, in firstLaunchConfig
    customer_id = BRAND[package_name]["brand_code"] + "-" + res_dict["id"]
KeyError: 'id'
{"success":{"language":"fr","country":"FR","profile":{"email":""},"dealers":{},"vehicles":[],"settings_update":1637772830,"terms_service":{"cguForValidation":"496","lastCguAlreadyValidated":"496"},"early_adopter":["REMOTELEV"],"service_state":[],"cgu_validation":false}}
```

**Comment by show2go** [comment]
me to Home assistant
Traceback (most recent call last): File "/psa_car_controller/app_decoder.py", line 109, in firstLaunchConfig customer_id = BRAND[package_name]["brand_code"] + "-" + res_dict["id"] KeyError: 'id' {"success":{"language":"fr","country":"FR","profile":{"email":""},"dealers":{},"vehicles":[],"settings_update":1636983910,"terms_service":{"cguForValidation":"40","lastCguAlreadyValidated":"40"},"early_adopter":[],"service_state":[],"cgu_validation":false}}

**Comment by Dragonfly-terra** [comment]
I have the same error as p-rintz discribes. But I use input 'NL'.
`Traceback (most recent call last): File "/psa_car_controller/app_decoder.py", line 109, in firstLaunchConfig customer_id = BRAND[package_name]["brand_code"] + "-" + res_dict["id"] KeyError: 'id' {"success":{"language":"fr","country":"FR","profile":{"email":""},"dealers":{},"vehicles":[],"settings_update":1637772830,"terms_service":{"cguForValidation":"496","lastCguAlreadyValidated":"496"},"early_adopter":["REMOTELEV"],"service_state":[],"cgu_validation":false}}`

But when I use something like 'DE', I get this error: (Perhaps it has nothing to do with this error, but more that is registered to my dutch account. 
`Traceback (most recent call last): File "/psa_car_controller/app_decoder.py", line 82, in firstLaunchConfig token = res.json()["accessToken"] KeyError: 'accessToken' HOST_BRANDID : https://id-dcr.peugeot.com/mobile-services sitecode: AP_DE_ESP{"session":"65413173b8a7b(there more numbers here)","returnCode":"NEED_AUTHORIZATION","token":"9805c24b24c015f2691bd(there more numbers here)"}`

**Comment by show2go** [comment]
same as Dragonfly
origin AT

Traceback (most recent call last): File "/psa_car_controller/app_decoder.py", line 82, in firstLaunchConfig token = res.json()["accessToken"] KeyError: 'accessToken' HOST_BRANDID : https://id-dcr.opel.com/mobile-services sitecode: OP_DE_ESP{"session":"f89e17b377a46ec88505624e26e12bd9","returnCode":"NEED_AUTHORIZATION","token":"0ca2e29962440ebc604ca52239decb34fa5946b3cf372cb740c2e995e638ab22"}

**Comment by STaN33130** [comment]
For me success (FR), but never receive SMS on OTP config

**Comment by ProtossBlaster** [comment]
I have update to 2.5.5  country IT 
This is the error on screen
Traceback (most recent call last): File "/psa_car_controller/app_decoder.py", line 109, in firstLaunchConfig customer_id = BRAND[package_name]["brand_code"] + "-" + res_dict["id"] KeyError: 'id' {"success":{"language":"fr","country":"FR","profile":{"email":""},"dealers":{},"vehicles":[],"settings_update":1637772830,"terms_service":{"cguForValidation":"496","lastCguAlreadyValidated":"496"},"early_adopter":["REMOTELEV"],"service_state":[],"cgu_validation":false}}

**Comment by flobz** [comment]
A new release is builing which should fixed the issue for other than french customer.

**Comment by egpall** [comment]
Thanks

**Comment by aferraz** [comment]
Thanks @flobz
 work for me but I have to delete and install the addon

Regards
 Alessandro

**Comment by flobz** [comment]
Ok thanks for your return. I closed the issue.
