### ISSUE TITLE
getting this error when i run the app, nothing is really updating on the webpage and car is showing in libya?

### ISSUE THREAD

**Issue by ee-dpit** [flobz/psa_car_controller#284]
* Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-11-27 22:03:23,505 :: INFO :: charging status of VR3F4DGZTKY211884 is Disconnected, battery level: 0
127.0.0.1 - - [27/Nov/2021 22:03:26] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Nov/2021 22:03:26] "GET /assets/clientside.js?m=1638037092.3052714 HTTP/1.1" 304 -
127.0.0.1 - - [27/Nov/2021 22:03:27] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [27/Nov/2021 22:03:27] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [27/Nov/2021 22:03:27] "GET /_favicon.ico?v=2.0.0 HTTP/1.1" 200 -
2021-11-27 22:03:27,786 :: WARNING :: Failed to generate figure, there is probably not enough data yet
127.0.0.1 - - [27/Nov/2021 22:03:27] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [27/Nov/2021 22:03:27] "GET /control?header=false HTTP/1.1" 200 -
127.0.0.1 - - [27/Nov/2021 22:03:27] "GET /assets/images/settings.svg HTTP/1.1" 304 -
127.0.0.1 - - [27/Nov/2021 22:03:27] "GET /assets/clientside.js?m=1638037092.3052714 HTTP/1.1" 304 -
127.0.0.1 - - [27/Nov/2021 22:03:27] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [27/Nov/2021 22:03:27] "GET /_dash-dependencies HTTP/1.1" 200 -
2021-11-27 22:03:27,965 :: ERROR :: get_control_tabs:
Traceback (most recent call last):
  File "/home/ee/Documents/Car updates/psa_car_controller/web/view/control.py", line 33, in get_control_tabs
    value=str(int(car.status.timed_odometer.mileage)))],
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
127.0.0.1 - - [27/Nov/2021 22:03:27] "POST /_dash-update-component HTTP/1.1" 200 -

**Comment by ee-dpit** [comment]
PEugeot 508 SW Plug-in Hybrid 225

**Comment by flobz** [comment]
it will be fixed in next release. Thanks for reporting.
