### ISSUE TITLE
I can not enter 127.0.0.1 with installation by docker

### ISSUE THREAD

**Issue by javiges** [flobz/psa_car_controller#289]
**Describe the bug**
I used this to create the docker but when I give the ip http://127.0.0.1:5000, nothing happens

docker run -d -ti --name psa_car_controller1
--publish 5000:5000
-v /docker/config:/config
--restart unless-stopped
flobz/psa_car_controller

**To Reproduce**
1. what command did you use
2. when the bug append ?
3. Does it persist after restarting the program? 
4. Does it persist after recreate config by going to http://server_address:port/config? 

**Config file**
Give the anonymize content of the config file

**Environment (please complete the following information):**
 - OS: [Ubuntu 20. Lts] Home Assistant Core Docker
 - Ds7 performance Line Diésel
 - Application version (1.33.3)
 - Log from http://server_address:port/log and browser console log

**Additional context**

**Comment by flobz** [comment]
give the log of docker container please
