### ISSUE TITLE
Reduce minimum trip length for statistics

### ISSUE THREAD

**Issue by maivorbim** [flobz/psa_car_controller#295]
**Describe the bug**
Based on empirical evidence, it seems that the PSACC statistics are calculated only taking into account trips which are at least 10 km long. While I understand the rationale for this (longer trips equals more accurate consumption values), for those living in the city and taking shorter trips to work the statistics become useless, as they are never updated. 

Proposed changes:

- eliminate the minimum trip length threshold or at least reduce it to 5 km trips, which should be enough distance to calculate accurate consumption.

**Comment by flobz** [comment]
Hello,
A good solution in my opinion is to be able to change this settings.

**Comment by flobz** [comment]
it will be added in next release
