### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'HUTokenManager.xml'

### ISSUE THREAD

**Issue by Maxus1998** [flobz/psa_car_controller#3]
Hi,

I just tried out your program.

I first want to point out that I used the myOpel app as I own a an Opel Corsa.

In line 57 in app_decoder tries to load the file "HUTokenManager.xml" which does not exist when extracting the backup of the myOpel app (I already changed "apps/com.psa.mym.mypeugeot" and "com.psa.mym.mypeugeot_preferences.xml" to "com.psa.mym.mypeugeot_preferences.xml"/"com.psa.mym.mypeugeot_preferences.xml"

I tried searching through all xml files with 'grep -R --include="*.xml" "refresh_token" ./' (because of line 59) already but could not find it.
Do you have any idea what would need to be done here?

**Comment by Maxus1998** [comment]
Nevermind, I forgot to issue a remote in step 1.4 start a remote request
Did it on another device which did not work out with adb.

I guess the command needs to be successful (could not connectt to the car) though as I am getting key error refresh_token.

**Comment by flobz** [comment]
Hello,
I updated the program, can you retry ?

**Comment by Maxus1998** [comment]
Hi,
thanks for the fast update.
I managed to get further now indeed, but sadly another error message appeared...

Traceback (most recent call last):
  File "app_decoder.py", line 77, in <module>
    psacc.connect(client_email, client_paswword)
  File "/home/max/psa_car_controller/MyPSACC.py", line 98, in connect
    self.manager.init_with_user_credentials(user, password, realm)
  File "/home/max/psa_car_controller/MyPSACC.py", line 33, in init_with_user_credentials
    self._token_request(self._grant_password_request(login, password, realm), True)
  File "/home/max/.local/lib/python3.8/site-packages/oauth2_client/credentials_manager.py", line 190, in _token_request
    CredentialManager._handle_bad_response(response)
  File "/home/max/.local/lib/python3.8/site-packages/oauth2_client/credentials_manager.py", line 78, in _handle_bad_response
    raise OAuthError(HTTPStatus(response.status_code), error.get('error'), error.get('error_description'))
oauth2_client.credentials_manager.OAuthError: 400  - invalid_grant : The provided access grant is invalid, expired, or revoked.

I used clientsB2COpel as realm and the myOpel access data (copied them directly out of the browser to make sure that they are correct.

**Comment by Maxus1998** [comment]
I added a separate issue for this
https://github.com/flobz/psa_car_controller/issues/4
