### ISSUE TITLE
No values have been entered or retrieved since 12/18.

### ISSUE THREAD

**Issue by nuiler** [flobz/psa_car_controller#303]
**Describe the bug**
No values have been entered or retrieved since 12/18.

**To Reproduce**
1. what command did you use
2. since 12/18
3. yes
4. Does it persist after recreate config by going to http://server_address:port/config? 

**Config file**
Give the anonymize content of the config file

**Environment (please complete the following information):**
 - Home Assistant
 - Opel Grandland X
 -2.6.0
 - 2021-12-22 00:01:46,782 :: WARNING :: charge begin but API isn't updated

**Additional context**

**Comment by flobz** [comment]
If the API isn't updated it's a PSA issue, not a PSA Car Controller one.
