### ISSUE TITLE
[New Car model] DS7 Crossback Etense 225

### ISSUE THREAD

**Issue by jesperdc** [flobz/psa_car_controller#308]
I have a "Can't get car model" error.
Information to add my car model to the app:
- Brand: DS
- Model: DS7 Crossback Etense 225
- First ten letter of my VIN: VR1J4DGZUM 
- Useable Electric capacity in kw: 13,2
- Fuel capacity in liter: 43

**Comment by jesperdc** [comment]
@flobz do i have to do more to get the car on the list? :)

/jesper

**Comment by flobz** [comment]
Please follow the doc : https://github.com/flobz/psa_car_controller/blob/master/FAQ.md
