### ISSUE TITLE
App shows only data of e-208. For 508 it gives "Internal Server Error"

### ISSUE THREAD

**Issue by potsch** [flobz/psa_car_controller#31]
I installed the app and followed the instructions from the githug page. I have two cars e-208 and 508 hybrid. When asking for the car state, it only works for the e-208. The webpage for the 508 gives me an "500: Internal Server Error". The log of the terminal states it `ask wakeup to VINof508`. Also I'm getting this error when restarting the script `OSError: [Errno 98] Address already in use
`
Can anybody explain what went wrong and offer help?

**Comment by flobz** [comment]
The program doesn't handle hybrid car yet. That's why it doesn't work.  
Your second error mean that the first instance of the script is still alive.

**Comment by jlayec** [comment]
Hello
I m working on the hybrid branch of this repo
U can try it and give me the output of the console so i can add the 508 hybrid.
Regards

**Comment by flobz** [comment]
@potsch I close the issue since we haven't any update from you.
