### ISSUE TITLE
[New Car model] Citroën C4 (2022)

### ISSUE THREAD

**Issue by peixsoft** [flobz/psa_car_controller#312]
I have a "Can't get car model" error.
Information to add my car model to the app:
- Brand: Citroën
- Model: C4
- First ten letter of my VIN:  VR7BAHNSBM
- Useable Electric capacity in kw: 0
- Fuel capacity in liter: 50

**Comment by flobz** [comment]
Please follow the doc : https://github.com/flobz/psa_car_controller/blob/master/FAQ.md
