### ISSUE TITLE
I get no IP adress from HA add-onv

### ISSUE THREAD

**Issue by RGBTyp** [flobz/psa_car_controller#314]
I can't get the data in home assistant because I can't get a valid IP address from the add-on. 

The log from the add-on shows:

2022-01-16 00:20:08,400 :: INFO :: update_data
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)

Can anyone help me?

**Comment by dreimer1986** [comment]
![image](https://user-images.githubusercontent.com/29841368/149643222-ee8285c1-e29f-425c-94fa-3e7a076460ed.png)

Do that in settings and then just use the IP of your HA instance. This fixes the sometimes changing IPs you otherwise would have.

**Comment by RGBTyp** [comment]
Yes that worked.

Thank you very much!
