### ISSUE TITLE
NO IP assigned

### ISSUE THREAD

**Issue by H08X** [flobz/psa_car_controller#316]
Hi 
I might be asking a NooB question here, i have been searching high and low, without finding a solution.

II have installed the HA PSA module from HACS and the auth part has been completed, and i can see Data is received, all is good BUT:

I constantly get 

 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)

What am i doing wrong ?
  

**Describe the bug**

**To Reproduce**
1. what command did you use
2. when the bug append ?
3. Does it persist after restarting the program? 
4. Does it persist after recreate config by going to http://server_address:port/config? 

**Config file**
Give the anonymize content of the config file

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
 - Brand and model of car
 - Application version (commit number, branch or tag)
 - Log from http://server_address:port/log and browser console log

**Additional context**

**Comment by dreimer1986** [comment]
https://github.com/flobz/psa_car_controller/issues/314
