### ISSUE TITLE
[New Car model] Peugeot 3008 II 1.2 PureTech 130 GT Line (2017)

### ISSUE THREAD

**Issue by rdousset44** [flobz/psa_car_controller#319]
I have a "Can't get car model" error only for this vehicule ; no issue with my e-208.
Information to add my car model to the app:
- Brand: Peugeot
- Model: SUV 3008 II 1.2 PureTech 130 GT Line (year 2017)
- First ten letter of my VIN: VF3MRHNYHH
- Useable Electric capacity in kw: 0
- Fuel capacity in liter: 53

I see a similar VIN in the 'car_model.py' but with incorrect model infos !
   CarModel("SUV 5008 II 2018", 0, 56, reg=r"VF3MRHNY.*"),  #  VF3MRHNYHH

(screenshot from peugeot app)
![image](https://user-images.githubusercontent.com/97254510/151145530-b32bfd53-63a3-4c43-a81f-1c16767b2eeb.png)

**Comment by flobz** [comment]
Please follow the doc : https://github.com/flobz/psa_car_controller/blob/master/FAQ.md
