### ISSUE TITLE
server no longer starting

### ISSUE THREAD

**Issue by aleblack** [flobz/psa_car_controller#320]
**Describe the bug**
Suddendly at 3:00am today, the server stopped working.
I tried to manually start it (instead using systemd) and this is what i get:

```
2022-01-30 12:19:28,697 :: ERROR :: Please reconnect by going to config web page
Traceback (most recent call last):
  File "server.py", line 22, in <module>
    conf.load_app()
  File "/opt/psa_car_controller/libs/config.py", line 110, in load_app
    raise ConnectionError
ConnectionError
2022-01-30 12:19:28,699 :: INFO :: save config change
```

**To Reproduce**
1. what command did you use? -  `python3 server.py -f mycarconfig.json -c charge_config.json -r`
2. when the bug append? - 30th January at 3:00 am
3. Does it persist after restarting the program? - yes
4. Does it persist after recreate config by going to http://server_address:port/config? - yes

**Config file**
```json
{
    "abrp": {
        "abrp_enable_vin": [
            "VR3UHxxxxxxxxxxxx"
        ],
        "token": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
    },
    "client_id": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "client_secret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "co2_signal_api": "xxxxxxxxxxxxxxxx",
    "country_code": "IT",
    "customer_id": "XX-xxxxxxxxxxxxxxxx",
    "proxies": {
        "http": "",
        "https": ""
    },
    "realm": "clientsB2CPeugeot",
    "refresh_token": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "remote_refresh_token": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "weather_api": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
}
```

**Environment (please complete the following information):**
 - OS: RPI4 - rasbpian 10.11 
 - Brand and model of car - e-208
 - Application version - latest master branch
 - Log from http://server_address:port/log and browser console log - not available

**Comment by aleblack** [comment]
Solved, please close.

**Comment by flobz** [comment]
Can you explain how you solve this please?
