### ISSUE TITLE
[New Car model] New berlingo

### ISSUE THREAD

**Issue by pafsan** [flobz/psa_car_controller#321]
I have a "Can't get car model" error.
Information to add my car model to the app:
- Brand: Citroen
- Model: New Berlingo
- First ten letter of my VIN:  VR7ERHNPJK
- Useable Electric capacity in kw: None (not electric)
- Fuel capacity in liter: 60l

**Comment by pafsan** [comment]
[](url
![V3DImage](https://user-images.githubusercontent.com/48994484/153389351-363fc8c7-69d0-430b-9b3a-483f78e27144.png)
)

**Comment by flobz** [comment]
Please follow the doc : https://github.com/flobz/psa_car_controller/blob/master/FAQ.md
