### ISSUE TITLE
Trips not shown in "Trips" page of dashboard

### ISSUE THREAD

**Issue by Pgr73** [flobz/psa_car_controller#325]
**Describe the bug**

Trips not shown in "Trips" page of dashboard, even after a few trips.

**To Reproduce**
1. what command did you use :   As per latest Docker image
2. when the bug append ?         Since the dashboard was installed
3. Does it persist after restarting the program?  Yes
4. Does it persist after recreate config by going to http://server_address:port/config? Yes

**Config file**
Give the anonymize content of the config file

{
    "abrp": {
        "abrp_enable_vin": [
            "VR3UHZKXZxxxxxxx"
        ],
        "token": "xxxxx-xxxx-xxxx-xxxx-xxxx"
    },
    "client_id": "xxxxx-xxxx-xxxxx-xxxx-xxxxx",
    "client_secret": "xxxxxxxxxxxxxxxxxxxxxxxxxx",
    "co2_signal_api": null,
    "country_code": "FR",
    "customer_id": "AP-ACNTxxxxxxxx",
    "proxies": {
        "http": "",
        "https": ""
    },
    "realm": "clientsB2CPeugeot",
    "refresh_token": "xxxx-xxxx-xxxx-xxxx-xxxxx",
    "remote_refresh_token": "xxxxx-xxx-xxx-xxx-xxxxx",
    "weather_api": "xxxxxxx"
}
**Environment (please complete the following information):**
 - OS: [20.04.3 LTS (GNU/Linux 5.4.0-1052-raspi aarch64) in a Docker container]
 - Brand and model of car : Peugeot e-208
 - Application version (commit number, branch or tag) : "Latest" Docker image on Feb, 22nd 2022 assumed to be v2.6.0: Merge pull request #274 from flobz/develop
 - Log from http://server_address:port/log and browser console log : No particular error message in  log (I think !)

**Additional context**

Dear @flobz, I'm not sure this is strictly speaking a bug in your code. 

Since I have installed the latest PSA server version, I have done a couple of trips and the car has been charged a couple of times.

In the web dashboard, I see the charging records and it looks fine. I also use the get_vehicleinfo route from Node-Red and I'm getting the info back, as I was expecting.

![image](https://user-images.githubusercontent.com/76474695/155520447-a0830320-1ced-4467-8787-d4becf7cdaa1.png)

Abrp also receives the battery SOC.

However, I see nothing in the "Trips" tab and most statistics are not calculated:

![image](https://user-images.githubusercontent.com/76474695/155520542-c1e39827-258f-498d-a1cc-7d5911010825.png)

![image](https://user-images.githubusercontent.com/76474695/155520680-2bd86e43-d033-4d8e-ad56-885af325a1f9.png)

I've done a bit of digging and I see that I have only one record in the "Position" table of the "info.db" database : 

`
    sqlite> .open info.db
    sqlite> select * from position;
    2021-03-27 12:42:04+00:00|VR3UHZKXZLxxxxxxx|5.5865|45.36565|25360.8|76||0||304
`

Before I go any further, I need to point out that I've been using your PSA sever for a long time in an early version (I was one of your early adopters ;) in Dec 2020) and I'm "suffering" from the "Last position not updated" problem ( #50 ) that I understand is a result of having activated the "Telemaintenance" option (what a mistake I did, as it has not shown any value !).

From what I could pick up from your code (sorry, I'm not a Phyton expert at all !), the date you are using to populate this "Position" table is the last GPS position date, which, in my case, is always the same (March 27, 2021), due to the issue mentioned above, and I'm assuming that the database record is being overwritten at each insert in the table as the timestamp is the primary key of the table :

`
sqlite> .schema position
`
`
CREATE TABLE position (Timestamp DATETIME PRIMARY KEY,
                                                             VIN TEXT, longitude REAL,
                                                             latitude REAL,
                                                             mileage REAL,
                                                             level INTEGER,
                                                             level_fuel INTEGER,
                                                             moving BOOLEAN,
                                                             temperature INTEGER,
                                                             altitude INTEGER);
`

Could you please confirm that is the reason why my dashboard does not display any trip ?

Now, assuming that you confirm my understanding, may I suggest that instead of using the last position date ` my_psacc.py, line 185: date = car.status.last_position.properties.updated_at` , you could use another date. For example, when looking at the data available in the get_vehicleinfo route, you could use the "service" or the "energy" updated_at date/time. This would enable to have trips in the dashboard, even if the GPS position remains always the same. Unfortunately, my Python and Github skills are too low to do and propose the change though a pull request, sorry !

If my understanding is not correct, then could you please provide some assistance to understand why my trips are empty in the dashboard ?

Thanks in advance !

PS: What a great piece of work you have done with this server !!! 👍 🥇

**Comment by flobz** [comment]
Hello,
I'm glad that you appreciate my work. 
I don't see how we can guess that a trip was made with only a date ?

**Comment by flobz** [comment]
Well thank you very much for the tips, It seem promising ! I will try that and if it work well it will be added to next version.

**Comment by flobz** [comment]
Well thank you very much for the tips, It seem promising ! I will try that and if it work well it will be added to next version.

**Comment by flobz** [comment]
It's added to last version
