### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by joseftogo** [flobz/psa_car_controller#335]
![image](https://user-images.githubusercontent.com/49909506/160499084-15edad76-f30a-4a88-9c16-0d6cf6aea989.png)
![image](https://user-images.githubusercontent.com/49909506/160499312-c9171000-1737-42c3-942c-ddc46d79da4e.png)

Hallo, nach dem Installieren von Python und den dependencies (über beide vorgeschlagenen Befehle) erhalte ich beim öffnen von server.py diese Fehlermeldung.

Ubuntu 20.04

Danke.

**Comment by flobz** [comment]
Close as it doesn't follow the bug template
