### ISSUE TITLE
Feature Request: Automatically postpone scheduled charge time when percentage threshold is set

### ISSUE THREAD

**Issue by cbruegg** [flobz/psa_car_controller#339]
Firstly, many thanks for this project! It's really useful.

I've noticed that when setting a percentage threshold and leaving the car plugged for multiple days, it still charges beyond the threshold. This is because it eventually starts charging at the scheduled time and depending on the car's responsiveness, PSA-CC may detect this only rather late.

One way to prevent this would be to monitor how close the current time is to the scheduled charging time. If it's below a certain threshold, PSA-CC could push the scheduled charge time to a later date. I've played around with the code and it could probably be implemented like this: https://github.com/cbruegg/psa_car_controller/commit/c1f43e60ee25a6683a97a9f7bb7f7b9375c233e2

That said, I'm not very familiar with the internals of the project yet, so perhaps there'd be a better way to implement this.

**Comment by flobz** [comment]
Thanks for your contribution I will look into it!

**Comment by flobz** [comment]
Can you create a mr?

**Comment by cbruegg** [comment]
I'll try to verify the implementation first and test it a little. I'll create a merge request after that :)

**Comment by flobz** [comment]
Great! :)

**Comment by Nico04** [comment]
I'm using this plugin in Home assistant for months now 🙂
How to use than feature in home assistant?
