### ISSUE TITLE
[E2008] Peugeot

### ISSUE THREAD

**Issue by drumstick77** [flobz/psa_car_controller#342]
I have a "Can't get car model" error.
Information to add my car model to the app:
- Brand: Peugeot
- Model: E2008
- First ten letter of my VIN:  VR3UKZKXZL
- Useable Electric capacity in kw:  45
- Fuel capacity in liter: 
I'm getting the following error:

2022-04-03 23:55:03,514 :: WARNING :: Disconnected with result code 5
2022-04-03 23:55:03,514 :: WARNING :: The connection was refused.

I believe I have entered the correct email, password, because I have received the SMS
which I have entered along with the PIN which I believe is the PIN that I used on the app.
I can see on HA that it is showing that my car is charging (because it currently is charging), but that's pretty much it. everything else is empty.

please advise. thanks

**Comment by flobz** [comment]
Please follow the doc : https://github.com/flobz/psa_car_controller/blob/master/FAQ.md

**Comment by drumstick77** [comment]
Where can I find the car_models.yaml file please?

**Comment by flobz** [comment]
There is a link in the doc.

**Comment by drumstick77** [comment]
Thanks. I think I now understand what that doc mean. thanks
Lastly, how can I change the unit to miles and miles/hr?

**Comment by drumstick77** [comment]
and from Euros to Pounds.

**Comment by flobz** [comment]
you can change Euros to Pounds by modifying the config.ini file.  For miles/hr it's not possible.
