### ISSUE TITLE
 'Car' object has no attribute 'get_car_by_vin'

### ISSUE THREAD

**Issue by flobz** [flobz/psa_car_controller#343]
### Discussed in https://github.com/flobz/psa_car_controller/discussions/340
avril 03 16:40:10 raspberrypi psa_car_controller[2188]: File "", line 677, in _load_unlocked
avril 03 16:40:10 raspberrypi psa_car_controller[2188]: File "", line 728, in exec_module
avril 03 16:40:10 raspberrypi psa_car_controller[2188]: File "", line 219, in _call_with_frames_removed
avril 03 16:40:10 raspberrypi psa_car_controller[2188]: File "/usr/local/src/psa_car_controller/.env/lib/python3.7/site-packages/psa_car_controller/web/view/views.py", line 399, in
avril 03 16:40:10 raspberrypi psa_car_controller[2188]: Charging.set_default_price(get_default_car())
avril 03 16:40:10 raspberrypi psa_car_controller[2188]: File "/usr/local/src/psa_car_controller/.env/lib/python3.7/site-packages/psa_car_controller/psacc/application/charging.py", line 45, in set_default_price
avril 03 16:40:10 raspberrypi psa_car_controller[2188]: Charging.set_charge_price(charge, conn, cars.get_car_by_vin(charge.vin))
avril 03 16:40:10 raspberrypi psa_car_controller[2188]: AttributeError: 'Car' object has no attribute 'get_car_by_vin'
avril 03 16:40:10 raspberrypi psa_car_controller[2188]: WARNING: dev bundles requested with serve_locally=False.
avril 03 16:40:10 raspberrypi psa_car_controller[2188]: This is not supported, switching to serve_locally=True

**Comment by flobz** [comment]
Please follow the docs : https://github.com/flobz/psa_car_controller/blob/master/FAQ.md

**Comment by HOzo123** [comment]
Hello @flobz, It seems, there is still concern(s). I just posted a note in the discussion area.

Thank you
