### ISSUE TITLE
Can't include it as iframe in Hassio

### ISSUE THREAD

**Issue by Chaosflori25** [flobz/psa_car_controller#345]
**Describe the bug**
An iFrame in Homeassistant needs a webpage that supports https, what I didn't find how to enable it.

**To Reproduce**
1. what command did you use
I just tried opening it with https://[myip]:[myport]
2. when the bug append ?
Since the installation
3. Does it persist after restarting the program? 
yes
4. Does it persist after recreate config by going to http://server_address:port/config? 
yes
**Config file**
Give the anonymize content of the config file

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
Linux(Ubuntu) with Docker
 - Brand and model of car
Peugeot e208
 - Application version (commit number, branch or tag)
2.5.1
 - Log from http://server_address:port/log and browser console log
```
192.168.178.10 - - [06/Apr/2022 17:33:00] code 400, message Bad request version ('¨^9UXzª\x0fM\x86D<Üîz¸6\x08µn8Uéö\x94(')
192.168.178.10 - - [06/Apr/2022 17:33:00] "üP÷	p*iñòÜQÍW,#Ûì?Ä°ÖË¦  ¨^9UXzªMD<Üîz¸6µn8Uéö(" HTTPStatus.BAD_REQUEST -
192.168.178.10 - - [06/Apr/2022 17:33:00] code 400, message Bad request version ('´\x83ÌGë\x99')
192.168.178.10 - - [06/Apr/2022 17:33:00] "ütÖM$C7ø}Ç]&ÃDÔñ	Cm1CÝ%®À Jh¥=æÆkEíFëØ ´ÌGë" HTTPStatus.BAD_REQUEST -
192.168.178.10 - - [06/Apr/2022 17:33:00] code 400, message Bad request version ('\x1a\x1a\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x01\x93::\x00\x00\x00\x17\x00\x00ÿ\x01\x00\x01\x00\x00')
192.168.178.10 - - [06/Apr/2022 17:33:00] "ühÿ¡R7²¤ë¥ízjøìù¼1ÝHgìNÖ ÜCx3ºpH4ÚÉD<ÜS[$.ÿ8¦D& À+À/À,À0Ì©Ì¨ÀÀ/5::ÿ" HTTPStatus.BAD_REQUEST -
192.168.178.10 - - [06/Apr/2022 17:33:00] code 400, message Bad request version ('jj\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x01\x93\x9a\x9a\x00\x00\x00\x17\x00\x00ÿ\x01\x00\x01\x00\x00')
192.168.178.10 - - [06/Apr/2022 17:33:00] "ü®ÔRÐ\j¦Á¹ûÂ®Ô9¤ÊÕÂÆ½²É2ö+×WM ùG	X°ßL&²ÌA,ë,s	bô^îB jjÀ+À/À,À0Ì©Ì¨ÀÀ/5ÿ" HTTPStatus.BAD_REQUEST -
```
**Additional context**
I tried changing the proxy but this leads to the container crashing on me. I hope I didn't miss something easy.

**Comment by flobz** [comment]
Why use iframe instead of ingress : https://www.home-assistant.io/blog/2019/04/15/hassio-ingress/ ?
I personally use this app behind a nginx https proxy without issue.
