### ISSUE TITLE
Sprache kann nicht abgerufen werden

### ISSUE THREAD

**Issue by Trunks1982** [flobz/psa_car_controller#347]
Direkt nach der Installation vom Docker kommt das.Woran kann das liegen?

![Bildschirmfoto 2022-04-08 um 17 38 20](https://user-images.githubusercontent.com/62701386/162475664-3174a08a-c086-4a13-8e65-7cfe03cfe6c0.png)

**Comment by flobz** [comment]
Close as it doesn't follow the bug template
