### ISSUE TITLE
[New Car model] my model

### ISSUE THREAD

**Issue by Espressoshooter** [flobz/psa_car_controller#360]
I have a "Can't get car model" error.
Information to add my car model to the app:
- Brand: Peugeot
- Model: e-Rifter
- First ten letter of my VIN:  VR3EZZKXZM
- Useable Electric capacity in kw: 45
- Fuel capacity in liter:

**Comment by flobz** [comment]
please follow this guide  https://github.com/flobz/psa_car_controller/blob/master/FAQ.md#1-cant-get-car-model 
Thanks :)
