### ISSUE TITLE
open weather map api key syntax

### ISSUE THREAD

**Issue by italoc** [flobz/psa_car_controller#365]
In which syntax I can put the open weather map key in config.ini?

**Comment by CWfFO** [comment]
For my understanding it is config.json
In this form:
 "weather_api": "your_API_Key"

Nevertheless it is not working for me.

**Comment by tomechio** [comment]
Could it be that _consumption by weather_ chart doesn't work due to missing _kinetic_ and _last position_ information?
After all the weather service needs to get some coordinates to give the temperature of the area where the vehicle is.
