### ISSUE TITLE
Psa_car_controller and MyOpel app conflict

### ISSUE THREAD

**Issue by lebetz** [flobz/psa_car_controller#367]
**Describe the bug**
I have MyOpel app on my Android phone and psa_car_controller in recording mode running. 
It seems that only one of them receives an event from the car. I. e. a trip is shown either in MyOpel app or in psa_car_controller dashboard. Never in both. 
I couldn't find out when it appears in the app. Maybe only if the app is active when the trip ends. 

Is this a know behavior and is it not allowed to use both simultanously? 

**To Reproduce**
1. what command did you use
2. when the bug append ?
3. Does it persist after restarting the program? 
4. Does it persist after recreate config by going to http://server_address:port/config? 

**Config file**
Give the anonymize content of the config file

**Environment (please complete the following information):**
 - OS: Linux
 - Brand and model of car: Opel Mokka-e

**Comment by flobz** [comment]
MyOpel app receive trips by Bluetooth... 
I don't have this issue anyway.
