### ISSUE TITLE
Service definition

### ISSUE THREAD

**Issue by CWfFO** [flobz/psa_car_controller#368]
Hi,
i have the following service definition:
_[Unit]
Description=Remote Control of PSA car
After=network-online.target

[Service]
User=root
WorkingDirectory=/home/pi/Opel/psa_car_controller-master
ExecStart=psa-car-controller -f test.json -c charge_config.json -r -l 192.168.99.13 -m xxx -P yyy
Restart=on-failure
RestartSec=1m
Environment=PYTHONUNBUFFERED=true

[Install]
WantedBy=multi-user.target_

The Problem is the user. With user root it works, with user pi i can not access the web page. I don't see an error in the logfiles. 
I just updated to the latest version. In former times it worked. But i did not an update since ~half a year.
Permissions of the directory (and any files and dirs inside):
drwxr-xr-x 17 pi   pi       4096 Mai 17 16:01 psa_car_controller-master
I am running Raspbian Buster.

Any ideas?

**Comment by flobz** [comment]
maybe an error with journalctl -xf ?

**Comment by CWfFO** [comment]
This is the only error i see:
ImportError: cannot import name 'dcc' from 'dash' (/home/pi/.local/lib/python3.7/site-packages/dash/__init__.py)
Uninstall and new install from dash didn't help

**Comment by flobz** [comment]
google
