### ISSUE TITLE
position empty

### ISSUE THREAD

**Issue by robotfishe** [flobz/psa_car_controller#371]
Trying to migrate from Tronity API over to your code so I can run my own server for this info instead of paying Tronity to use theirs.

Tronity gives me accurate position data, but psa_car_controller doesn't. Here's the data I get from :5000/getvehicleinfo/VIN:

{"embedded": null, "links": {"_self": {"deprecation": null, "href": "https://api.groupe-psa.com/connectedcar/v4/user/vehicles/VEHICLE ID/status", "hreflang": null, "name": null, "profile": null, "templated": null, "title": null, "type": null}, "vehicle": null}, "battery": {"current": 0.0, "voltage": 96.0}, "doors_state": null, "energy": [{"updated_at": "2022-05-24 22:48:15+00:00", "autonomy": 310.0, "battery": null, "charging": {"charging_mode": "No", "charging_rate": 0, "next_delayed_time": "PT1M", "plugged": false, "remaining_time": null, "status": "Disconnected"}, "consumption": null, "level": 93.0, "residual": null, "type": "Electric"}], "environment": null, "ignition": null, "kinetic": {"acceleration": null, "moving": null, "pace": null, "speed": null}, "last_position": {"type": "Feature", "geometry": {"coordinates": [null, null, null], "type": "Point"}, "properties": {"heading": null, "signal_quality": null, "type": null, "updated_at": null}}, "preconditionning": {"air_conditioning": {"failure_cause": null, "programs": null, "status": "Disabled", "updated_at": "2022-05-24 22:48:15+00:00"}}, "privacy": {"state": "None"}, "safety": null, "service": {"type": "Electric", "updated_at": "2022-05-24 22:48:15+00:00"}, "timed_odometer": {"updated_at": null, "mileage": 412.4}}

Everything is as expected and correct/matches what's in the Vauxhall app, except the last position being all "null".

The command I'm running to start the server is:

python3 psa_car_controller -f config.json -r -l 0.0.0.0 -d

Car is a Vauxhall Mokka-E.

**Comment by dreimer1986** [comment]
https://github.com/flobz/psa_car_controller/issues/50

**Comment by robotfishe** [comment]
I did read that thread before posting and my issue is not the same. In my case, unlike as discussed there, Tronity _is_ able to read the location from the PSA API and report it. That means the problem can't be with the PSA API. Could you please reopen this issue?
