### ISSUE TITLE
Wrong electricity consumption values

### ISSUE THREAD

**Issue by maivorbim** [flobz/psa_car_controller#372]
**Describe the bug**
PSA CC dashboard shows wrong electricity consumption values. Currently it shows: 1.24e + 3 kWh. This looks like the values are out of bounds for the variable defined.

**Environment (please complete the following information):**
 - OS: Home Assistant 2022.5.5
 - Brand and model of car: Peugeot e208
 - Application version: PSA CC v2.6.0
 
![Untitled](https://user-images.githubusercontent.com/34894081/170433662-ede71a0e-628e-4f5f-aef4-72c5e3d8b1f8.png)

**Comment by flobz** [comment]
fixed in v3
