### ISSUE TITLE
Dormant entities

### ISSUE THREAD

**Issue by drumstick77** [flobz/psa_car_controller#374]
Hi, hope you can help me with this.
I've recently had my HA crashed. I rebuilt it and restored.
I am able to get my PSACC logged into my peugeot account and sorted out the token etc.
But what I notice is that all the entities are showing unavailable.
I've then removed the PSACC addon, rem'd out every lines in configuration.yaml in relation to PSACC. I've also rem'd out !sensor.yaml because I only have e2008 sensors in them.
I've restarted HA and those entities are still there!
Is there a way to remove them completely? or reset PSACC so that I can start with a clean slate? Thanks

**Comment by dreimer1986** [comment]
Yes, the official Hme Assistant way:
Go to https://yourdomain/config/entities
Loof for your problematic ones and be dure that the y have this 
![image](https://user-images.githubusercontent.com/29841368/174462876-d3513743-248f-49dd-b0fa-a6fbbc069b7a.png) symbol on the right. Click on it and fiund the delete button blow.
![image](https://user-images.githubusercontent.com/29841368/174462840-d6076d9c-75e7-46a4-a070-3638b3acba52.png)
