### ISSUE TITLE
added a pull request that was closed for a car model

### ISSUE THREAD

**Issue by rchiileea** [flobz/psa_car_controller#376]
I added a pull request after following instructions to add car vin and model, but pull request was closed and I did not see the model added inside the models list?

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/174427677-6425a4b3-392c-4f3f-b5e5-6ed81615a038.png)
car is in but installed and still get this (home assistant) or am i being to quick off the mark here

**Comment by proximagr** [comment]
same problem, I have a DS7. I added the plug in at Home Assistant. It returns most values null. 
At logs WARNING: Can't get car model, please report an issue on github with your car model and first ten letter of your VIN : VR1J4DGZUN
http://HAIP:5000/get_vehicleinfo/VR1J4DGZUNXXXXX returns:
{"embedded": null, "links": {"_self": {"deprecation": null, "href": "https://api.groupe-psa.com/connectedcar/v4/user/vehicles/1566c4978536a524552317056546c6b314d4463354d54556a497a566c5a546c68596a4a6a4e3245344d444d355a4445335954466a4d444e684e6a497a4e7a59314f4745324f5463304d4745785a6d46684f4441785a6d466a4e7a677a5a6d59315a6a46684e6a42684e4468694d44453d/status", "hreflang": null, "name": null, "profile": null, "templated": null, "title": null, "type": null}, "vehicle": null}, "battery": {"current": 0.0, "voltage": 85.0}, "doors_state": null, "energy": [{"updated_at": "2022-06-18 11:48:28+00:00", "autonomy": 0.0, "battery": null, "charging": {"charging_mode": "Slow", "charging_rate": 0, "next_delayed_time": "PT0S", "plugged": false, "remaining_time": null, "status": "Disconnected"}, "consumption": null, "level": 0.0, "residual": null, "type": "Electric"}, {"updated_at": "2022-06-18 11:48:28+00:00", "autonomy": 230.0, "battery": null, "charging": null, "consumption": null, "level": 0.0, "residual": null, "type": "Fuel"}], "environment": null, "ignition": null, "kinetic": {"acceleration": null, "moving": null, "pace": null, "speed": null}, "last_position": {"type": "Feature", "geometry": {"coordinates": [null, null, null], "type": "Point"}, "properties": {"heading": null, "signal_quality": null, "type": null, "updated_at": null}}, "preconditionning": {"air_conditioning": {"failure_cause": null, "programs": null, "status": "Disabled", "updated_at": "2022-06-18 11:48:27+00:00"}}, "privacy": {"state": "None"}, "safety": null, "service": {"type": "Hybrid", "updated_at": "2022-06-18 11:48:28+00:00"}, "timed_odometer": {"updated_at": null, "mileage": 4823.6}}

**Comment by rchiileea** [comment]
> same problem, I have a DS7 Crossback E-Tense 225. Looking at the car_models.yml , there is only the DS7 Crossback E-Tense 300 4x4 model. Not the 225 model.
> 
> I added the plug in at Home Assistant. It returns most values null. At logs WARNING: Can't get car model, please report an issue on github with your car model and first ten letter of your VIN : VR1J4DGZUN http://HAIP:5000/get_vehicleinfo/VR1J4DGZUNXXXXX returns: {"embedded": null, "links": {"_self": {"deprecation": null, "href": "https://api.groupe-psa.com/connectedcar/v4/user/vehicles/XXXXXXXXXXXXXXXX/status", "hreflang": null, "name": null, "profile": null, "templated": null, "title": null, "type": null}, "vehicle": null}, "battery": {"current": 0.0, "voltage": 85.0}, "doors_state": null, "energy": [{"updated_at": "2022-06-18 11:48:28+00:00", "autonomy": 0.0, "battery": null, "charging": {"charging_mode": "Slow", "charging_rate": 0, "next_delayed_time": "PT0S", "plugged": false, "remaining_time": null, "status": "Disconnected"}, "consumption": null, "level": 0.0, "residual": null, "type": "Electric"}, {"updated_at": "2022-06-18 11:48:28+00:00", "autonomy": 230.0, "battery": null, "charging": null, "consumption": null, "level": 0.0, "residual": null, "type": "Fuel"}], "environment": null, "ignition": null, "kinetic": {"acceleration": null, "moving": null, "pace": null, "speed": null}, "last_position": {"type": "Feature", "geometry": {"coordinates": [null, null, null], "type": "Point"}, "properties": {"heading": null, "signal_quality": null, "type": null, "updated_at": null}}, "preconditionning": {"air_conditioning": {"failure_cause": null, "programs": null, "status": "Disabled", "updated_at": "2022-06-18 11:48:27+00:00"}}, "privacy": {"state": "None"}, "safety": null, "service": {"type": "Hybrid", "updated_at": "2022-06-18 11:48:28+00:00"}, "timed_odometer": {"updated_at": null, "mileage": 4823.6}}


do you know how to add the model to the yaml for a commit?

**Comment by proximagr** [comment]
> > same problem, I have a DS7 Crossback E-Tense 225. Looking at the car_models.yml , there is only the DS7 Crossback E-Tense 300 4x4 model. Not the 225 model.
> > I added the plug in at Home Assistant. It returns most values null. At logs WARNING: Can't get car model, please report an issue on github with your car model and first ten letter of your VIN : VR1J4DGZUN http://HAIP:5000/get_vehicleinfo/VR1J4DGZUNXXXXX returns: {"embedded": null, "links": {"_self": {"deprecation": null, "href": "https://api.groupe-psa.com/connectedcar/v4/user/vehicles/XXXXXXXXXXXXXXXX/status", "hreflang": null, "name": null, "profile": null, "templated": null, "title": null, "type": null}, "vehicle": null}, "battery": {"current": 0.0, "voltage": 85.0}, "doors_state": null, "energy": [{"updated_at": "2022-06-18 11:48:28+00:00", "autonomy": 0.0, "battery": null, "charging": {"charging_mode": "Slow", "charging_rate": 0, "next_delayed_time": "PT0S", "plugged": false, "remaining_time": null, "status": "Disconnected"}, "consumption": null, "level": 0.0, "residual": null, "type": "Electric"}, {"updated_at": "2022-06-18 11:48:28+00:00", "autonomy": 230.0, "battery": null, "charging": null, "consumption": null, "level": 0.0, "residual": null, "type": "Fuel"}], "environment": null, "ignition": null, "kinetic": {"acceleration": null, "moving": null, "pace": null, "speed": null}, "last_position": {"type": "Feature", "geometry": {"coordinates": [null, null, null], "type": "Point"}, "properties": {"heading": null, "signal_quality": null, "type": null, "updated_at": null}}, "preconditionning": {"air_conditioning": {"failure_cause": null, "programs": null, "status": "Disabled", "updated_at": "2022-06-18 11:48:27+00:00"}}, "privacy": {"state": "None"}, "safety": null, "service": {"type": "Hybrid", "updated_at": "2022-06-18 11:48:28+00:00"}, "timed_odometer": {"updated_at": null, "mileage": 4823.6}}
> 
> do you know how to add the model to the yaml for a commit?

yes, I added the car and committed. Now it needs an author to approve the pull request. 
here: https://github.com/flobz/psa_car_controller/pull/379

**Comment by flobz** [comment]
#378 was merged and include in v3.0.4 available in https://github.com/flobz/psacc-ha-beta
