### ISSUE TITLE
Feature Request: Add mileage to the charge log

### ISSUE THREAD

**Issue by JHCD** [flobz/psa_car_controller#386]
As a user of a company electric vehicle, I have to record the mileage for a charge in order to be reimbursed by my employer for the costs. 

Would it be possible to add the mileage to the charge log?

**Comment by flobz** [comment]
A SQL query might do the tricks ?

**Comment by stevoh6** [comment]
> A SQL query might do the tricks ?

Yes and no, I was playing with sql in order to display some data in grafana, but its tricky. I think it will be more reliable to store mileage once charging stared. 

If you tell me how you can adjust database structure, I can try prepare pull request with this change :-)

**Comment by stevoh6** [comment]
I tried implement this feature. 

Who else can test my changes?
