### ISSUE TITLE
Although my VIN exists at the car_models.yml still Can't get car model error

### ISSUE THREAD

**Issue by proximagr** [flobz/psa_car_controller#389]
Although my VIN exists at the car_models.yml still Can't get car model error

Error:
2022-08-05 12:43:43,061 :: WARNING :: Can't get car model, please report an issue on github with your car model and first ten letter of your VIN : VR1J4DGZUN
2022-08-05 12:43:43,064 :: INFO ::
Your vehicles: ["{'vin': 'VR1J4DGZUNYXXXXXXX',

car_models.yml entry:
- !CarModel
  name: DS7 Crossback E-Tense 225
  battery_power: 13.2
  fuel_capacity: 43
  abrp_name:
  reg: VR1J4DGZ.*
  max_elec_consumption: 70
  max_fuel_consumption: 30

any suggestions? 

thank you

**Comment by flobz** [comment]
Close as it doesn't follow the bug template
