### ISSUE TITLE
NEED_AUTHORIZATION

### ISSUE THREAD

**Issue by brewmark27** [flobz/psa_car_controller#395]
When submitting the config info, I get a "NEED_AUTHORIZATION" error. I Have tried it in a Docker en Home Assistant set-up, but both set ups give me the same error. I have read that this error occurred with multiple people in the beginning, but could not find how it was solved. Can someone please help me how to solve this problem.

**Versions:**
Docker: v3.0.4
Home Assistant: V2.6.0

**Log:**
2022-08-31 17:53:54,024 :: WARNING :: Can't get language
2022-08-31 17:53:55,819 :: INFO :: update_data
2022-08-31 17:57:31,722 :: ERROR :: Traceback (most recent call last):
File "/psa_car_controller/libs/psa/setup/app_decoder.py", line 46, in firstLaunchConfig
token = res.json()["accessToken"]
KeyError: 'accessToken'

HOST_BRANDID : https://id-dcr.opel.com/mobile-services sitecode: OP_NL_ESP{"session":"b6cab784fa9d86ddd653c75f8e0e2fc8","returnCode":"NEED_AUTHORIZATION","token":"_TOKEN_"}
2022-08-31 18:29:45,301 :: WARNING :: Can't get language
2022-08-31 18:29:48,176 :: INFO :: update_data
2022-08-31 18:39:32,973 :: ERROR :: Traceback (most recent call last):
File "/psa_car_controller/libs/psa/setup/app_decoder.py", line 46, in firstLaunchConfig
token = res.json()["accessToken"]
KeyError: 'accessToken'

HOST_BRANDID : https://id-dcr.opel.com/mobile-services sitecode: OP_NL_ESP{"session":"a2d563d242f0761d01804fefa028a3ef","returnCode":"NEED_AUTHORIZATION","token":"_TOKEN_"}

**Comment by flobz** [comment]
Can you retry with last version ? (v3.0.5)

**Comment by nischi** [comment]
I do have the same issue with the newest version. Any idea why?

**Comment by nischi** [comment]
Hmm now i used DE as country code instead of CH. now it works :)

**Comment by flobz** [comment]
@nischi what is your preferred language? German ?

**Comment by nischi** [comment]
@flobz yes exactly, german or english. does not matter.

**Comment by mikogrencel** [comment]
Still doesn't work for me. I tried with PL and GB countries. first authentication was with wrong password but later corrected
[logs_error_doker.log](https://github.com/flobz/psa_car_controller/files/10360476/logs_error_doker.log)

**Comment by GeraldPape** [comment]
Maybe you have tried to often to register the script/mobile.

Open the moble app, in the top right click un the user icon, then click on your name. There is a text with "registered smartphones" or so with a recycle bin next to it. click the recycle bin and let it remove all registrations.
You need to re-register the app and the psa-controller. Give stelantis some time, everything there takes ages.
After many minutes I was able to retrive data again,...
