### ISSUE TITLE
opel api is not used when entering opel realm

### ISSUE THREAD

**Issue by Maxus1998** [flobz/psa_car_controller#4]
I entered my account crednetials and realm 'clientsB2COpel' which did not work

I then checked with which parameters the credentials_manager gets called in MyPSACC.py:33
Still "https://idpcvs.peugeot.com/am/oauth2/access_token" and "clientsB2CPeugeot" were used.
The correct values would be "https://idpcvs.opel.com/am/oauth2/access_token" and "clientsB2COpel"
After changing them in MyPSACC.py (oauth_url and realm) it worked. It seems like only the oauth_url needs to be changed to get the vehicle list. Leaving realm did not make a difference

**Comment by flobz** [comment]
Ok, I fixed the program, can you retry ?
Can you also give me the version of the android app that you use ?

**Comment by Maxus1998** [comment]
Works for me

I was using version 1.26.2

**Comment by flobz** [comment]
Last version of Mypeugeot is also 1.26.2, it seems they have a lot of source code in common.
