### ISSUE TITLE
This is not supported, switching to serve locally=True

### ISSUE THREAD

**Issue by pika28** [flobz/psa_car_controller#411]
Hello,

As an alternative to the addon 2.6.0 version present on home assistant, I installed the linux 3.0.4 version on a VM of my Freebox.

When I run the `psa-car-controller --web-conf` command, I get this.

```
2022-10-06 09:08:08,404 :: ERROR :: Bad config
WARNING: dev bundles requested with serve_locally=False.
This is not supported, switching to serve locally=True
2022-10-06 09:08:08,818:: INFO:: NumExpr defaulting to 2 threads.
2022-10-06 09:08:10,369 :: INFO :: update data
```

An idea?

**Comment by Higgins91** [comment]
same for me on a raspberry Pi3 and PiOS. Same error message... 
I come to think of port/protocol filtering on the freebox side? (I'm at Free too)

**Comment by flobz** [comment]
Close as it doesn't follow the bug template
