### ISSUE TITLE
Last position on map is not updated

### ISSUE THREAD

**Issue by duemila2** [flobz/psa_car_controller#413]
Last position in map is different from the one reported by the last status API.

`/get_vehicleinfo/<VIN>`

`{"embedded": null, "links": {"_self": {"deprecation": null, "href": "OMITTED", "hreflang": null, "name": null, "profile": null, "templated": null, "title": null, "type": null}, "vehicle": null}, "battery": {"current": 0.0, "voltage": 84.0}, "doors_state": null, "energy": [{"updated_at": "2022-10-10 07:44:40+00:00", "autonomy": 250.0, "battery": null, "charging": {"charging_mode": "No", "charging_rate": 0, "next_delayed_time": "PT14H", "plugged": false, "remaining_time": "PT0S", "status": "Disconnected"}, "consumption": null, "level": 77.0, "residual": null, "type": "Electric"}], "environment": null, "ignition": null, "kinetic": {"acceleration": null, "moving": false, "pace": null, "speed": null}, "last_position": {"type": "Feature", "geometry": {"coordinates": [8.51146, 44.33411, -6], "type": "Point"}, "properties": {"heading": 0.0, "signal_quality": 9.0, "type": "Aquire", "updated_at": "2022-10-10 07:44:20+00:00"}}, "preconditionning": {"air_conditioning": {"failure_cause": null, "programs": null, "status": "Disabled", "updated_at": "2022-10-10 07:44:40+00:00"}}, "privacy": {"state": "None"}, "safety": null, "service": {"type": "Electric", "updated_at": "2022-10-10 07:44:40+00:00"}, "timed_odometer": {"updated_at": null, "mileage": 22190.1}}`

map:

<img width="1223" alt="Schermata 2022-10-10 alle 09 45 48" src="https://user-images.githubusercontent.com/28447761/194819976-85e68e76-6fe1-4499-a1e6-6bc45fcce803.png">

**Comment by kurim** [comment]
I have the same issue, since 01.10.
But also TomTom Traffic does not work anymore and if I press on info to check Dataconnection and Services:
First is set to active and scond show not connected.

Can you check for your car?

**Comment by dreimer1986** [comment]
In theory we have a biiiig report for these problems or better API flaws by PSA: https://github.com/flobz/psa_car_controller/issues/50
I am quite sure this has something to do with free2move in the former form to not exist anymore... The whole API is the WORST of all car manufacturer's.

**Comment by duemila2** [comment]
I'm not sure if it is a PSA issue: calling get_vehicleinfo/<VIN> API the position is correct, only on map is not updated

**Comment by dreimer1986** [comment]
In my case the coords are frozen since then. in the api output, too as I use these on my Home Assistant.

**Comment by kurim** [comment]
> In my case the coords are frozen since then. in the api output, too as I use these on my Home Assistant.

You mean it freeze since Free2Move is gone, yes that would make sense, because it freeze on: 2022-09-30 19:56:43+00:00

**Comment by gerar19** [comment]
It doesn't record my trips either...

**Comment by duemila2** [comment]
Up for this issue. On database and on data sent to ABRP the last position is correct, in the map seems to be stuck to a very old position. Please investigate.

**Comment by flobz** [comment]
fix in last version
