### ISSUE TITLE
Permission denied for activity.log

### ISSUE THREAD

**Issue by zurnib** [flobz/psa_car_controller#414]
**Describe the bug**
When starting as service, I get the following error message:

Oct 21 09:32:02 Asgard2 psa-car-controller[23128]: PermissionError: [Errno 13] Permission denied: '/activity.log'

**To Reproduce**
1. what command did you use

`[Unit]
Description=PSA Controller
After=network-online.target

[Service]
ExecStart=/usr/local/bin/psa-car-controller -c -r -d
Restart=on-failure
RestartSec=1m
Environment=PYTHONUNBUFFERED=true
User=psa

[Install]
WantedBy=multi-user.target`

3. when the bug append ?
4. Does it persist after restarting the program? Yes
5. Does it persist after recreate config by going to http://server_address:port/config? N/A

**Config file**

`{
    "abrp": {
        "abrp_enable_vin": [],
        "token": ""
    },
    "client_id": "xxx",
    "client_secret": "xxx",
    "co2_signal_api": null,
    "country_code": "DE",
    "customer_id": "OP-xxx",
    "proxies": {
        "http": "",
        "https": ""
    },
    "realm": "clientsB2COpel",
    "refresh_token": "xxx",
    "remote_refresh_token": "xxx",
    "weather_api": null
}
`

**Environment (please complete the following information):**
 - OS: [e.g. Windows]: Raspian Buster
 - Brand and model of car: Opel Corsa
 - Application version (commit number, branch or tag)
 - Log from http://server_address:port/log and browser console log

**Additional context**
I installed the script with psa-car-controller --web-conf and I could launch the psa-car-controller under User pi successfully, the data was shown (I visualize it in FHEM). Then I copied your .service file to my system, created the psa user and just changed the location of the psa-car-controller to /usr/local/bin/. The activity.log file is located in /home/pi/.

**Comment by rimrul** [comment]
> The activity.log file is located in /home/pi/.

No. That's the `activity.log` file from your tests as `pi`. The file is created in the workdir of the process, in this case `/`. And it seems like `psa` can't write there.

Did you create the `psa` user with `adduser --system --no-create-home psa`?

**Comment by zurnib** [comment]
Yes, I even copy & pasted the line from the file.

**Comment by zurnib** [comment]
BTW, when root runs the process, everything works fine

**Comment by flobz** [comment]
Please look at this fix: https://github.com/flobz/psa_car_controller/commit/6bcc2cd1d4ce1f76dec8263037d1c9ddc3e4d4e1
