### ISSUE TITLE
Cross Origin Access not possible any more

### ISSUE THREAD

**Issue by pdigbrs** [flobz/psa_car_controller#427]
Would it be possible to enable Cross Origin access?
At least make it possible to turn it on by setting-file?
So e.g. change the code to:

from flask_cors import CORS  # add this line
...
app = Flask(__name__)
CORS(app)   # add this line

With the last versions it was possible to have a self made HTML-Page
hosted on a raspberry pi which could call a Javascript-Request on
http://ipAddressOfRaspberryPi:5000/get_vehicleinfo/xxxxxx?from_cache=1
and show a nice web page.
Now, I get a "cross origin" error in my page.

Many Thanks for your great work anyway!
It is much better then any
PSA-Software in the car´s displays and the non-working smartphone-app...   ;)

Ingo

**Comment by flobz** [comment]
could you please give me a way to reproduce this error.
