### ISSUE TITLE
Command 'charge_hour' doesn't work ('Bad Request')

### ISSUE THREAD

**Issue by Aelbaert** [flobz/psa_car_controller#434]
With command: 'http://myip:5000/charge_hour?vin=myvin&hour=23&min=12' I get the feedback: 

"Bad Request
The browser (or proxy) sent a request that this server could not understand."

I'm using v3.0.6 (in Home Assistant) on a Raspberry Pi 4

All other commands work (e.g. I can stop charging at 80% or start the climate control remotely).

I've added the Home Assistant - PSA Car controller logs for a few minutes when first noted and added the logs from http://server_address:port/log ( today, after recreating the config file ). 
If more info needed, please point me to location where to get please.

Regards and thanks in advance, 
Albert

**To Reproduce**
1. [what command did you use]: (http://myip:5000/charge_hour?vin=myvin&hour=23&min=12)
2. when the bug append ?
3. Does it persist after restarting the program? Yes
4. Does it persist after recreate config by going to http://server_address:port/config?  YES

**Config file**
Give the anonymize content of the config file
Not available for me, but entered: Car Brand: Opel; Country Code: NL and correct email and password and PIN-code

**Environment (please complete the following information):**
 - OS: [Home Assistant Operation System]
 - Brand and model of car: Corsa-e
 - Application version (V3.0.6)
 - Log from http://server_address:port/log and browser console log

**Additional context**
[HA-PSA-log.txt](https://github.com/flobz/psa_car_controller/files/10069571/HA-PSA-log.txt)

**Comment by flobz** [comment]
Hello,
Sorry I made a mistake in the readme : https://github.com/flobz/psa_car_controller/commit/5e3632c142976861813a38eb2e66b0ab15286ddc
