### ISSUE TITLE
Summary, Trip and map tabs don't refresh

### ISSUE THREAD

**Issue by arakeri10** [flobz/psa_car_controller#439]
Hello

On a debian, the application works well. It is possible to define the max % and the Charge tab indicates all the charges. 

The others tabs (summary, trip and map) don't display anything. 

Is there a parameter to modify in a configuration file?

Thanks ;)

**Comment by DavidFFerreira** [comment]
same probleme, since last update 06/10/2022 I got 0 records =/

**Comment by amaciasf** [comment]
It hasn't synced for me since 6/11. On the other hand, the loads do synchronize. The map never worked for me.

Peugeot e-208.

**Comment by gerar19** [comment]
> It hasn't synced for me since 6/11. On the other hand, the loads do synchronize. The map never worked for me.
> 
> Peugeot e-208.

same here...

**Comment by SinaDD** [comment]
I have the same problem, the app works fine, It is possible to define the max % and the Charge tab indicates almost all the charges, but don´t have trip updates since 14/10, and the map never worked for me.

I have all installen on docker, I trie to create a new docker and have the same problem. I have a Peugeot e-208.

**Comment by gerar19** [comment]
This is my Charges, but Trips don't record.... And I reinstall all but it's the same... Why? Thanks 

![charges yes](https://user-images.githubusercontent.com/11975151/209084232-5781b4a3-0dff-4b7c-bec0-b61ee488d8b0.png)
![dont have trips](https://user-images.githubusercontent.com/11975151/209084237-e7d4f74a-2d3d-4cd8-9cf4-1a1bd2d08f98.png)
![principal](https://user-images.githubusercontent.com/11975151/209084238-1bb6ed08-ec9a-435b-bacb-efba912c7b87.png)

**Comment by Dirtylife** [comment]
See readme.md


    You have to add an api key from https://home.openweathermap.org/ in your config file, to be able to see your consumption vs exterior temperature.
    You have to add an api key from https://co2signal.com/ to have your C02 emission by KM (in France the key isn't needed).

**Comment by Dirtylife** [comment]
Workaround for Trip-Updates see:

https://github.com/flobz/psa_car_controller/issues/415#issuecomment-1309203980

**Comment by gerar19** [comment]
> See readme.md
> 
> ```
> You have to add an api key from https://home.openweathermap.org/ in your config file, to be able to see your consumption vs exterior temperature.
> You have to add an api key from https://co2signal.com/ to have your C02 emission by KM (in France the key isn't needed).
> ```

Thanks! Now record a trips
