### ISSUE TITLE
Authentication does not work anymore since a few days

### ISSUE THREAD

**Issue by xammmue** [flobz/psa_car_controller#444]
**Describe the bug**
I am using the home assistant integration and all the values went to "unavailable" a few days ago. I now tried to authenticate which didn't work.
It up updated and started my old docker integration which was still on a raspberry pi to also try it there because I did not get any error message in home assistant.
Running the docker version revealed the following message on the page:
`'NoneType' object is not subscriptable`
I verified that email and password are correct.

Was there any recent change in the PSA API which is preventing this project from working now?

**Comment by smolders33** [comment]
Have the same issue here.
see also this in the log

2022-12-12 19:24:56,905 :: WARNING :: Can't get language
2022-12-12 19:24:57,881 :: INFO :: update_data

**Comment by xammmue** [comment]
It started working again for me yesterday morning. So the issue I experienced could in fact have been a PSA server issue. I've since also read about problems with the app on Sunday from other people in a forum

**Comment by smolders33** [comment]
I still have the same issue. recreated the docker but still the same.

**Comment by PMax87** [comment]
Idem here.

**Comment by stevoh6** [comment]
I updated docker container Today and I was able to successfully authenticate. Citroen ec4, SK country.

**Comment by smolders33** [comment]
I updated the image in my docker and after this I could authenticate again.

**Comment by PMax87** [comment]
Me too, I updated the image in my docker and now works well!

**Comment by CalicodesIles** [comment]
I updated the image in docker but I still have the same issue while running "User config" process.
Don't know if someone else have the same behaviour ?

**Comment by pedroresende** [comment]
I also have it
