### ISSUE TITLE
Possible to set charging power value?

### ISSUE THREAD

**Issue by jeremiel26** [flobz/psa_car_controller#450]
To prevent the electric meter from tripping, limit the charging power of the car.
The goal would be to interface with a zigbee module (ZLinky_TIC for example) of instantaneous consumption measurement to adapt according to the consumption in real time.

**Comment by flobz** [comment]
Hello,
it's possible but I wont do it.
If someone wants to contribute it could be an interesting feature.

**Comment by stevoh6** [comment]
I would like to suggest use little bit different approach, tool values from mqtt ( and Home assistant or some other system will populate those power data).
