### ISSUE TITLE
Update the car_models.yml locally

### ISSUE THREAD

**Issue by zamzon** [flobz/psa_car_controller#456]
Hi 
Is it possible to add new car models locally?
I'm running the software in a docker in Home assistant, can I change the file with SAMBA share of file editor in HA?

**Comment by stevoh6** [comment]
It shouldnt be a problem, just edit/add your model, restart and it should works. Also please share you "model" with others, so it can be added into config.

**Comment by zamzon** [comment]
I thought so, but can you tell me where the file is placed in the docker container ?
And can the file be edited in Home assistant ?

**Comment by stevoh6** [comment]
/usr/local/lib/python3.9/dist_pactages/psa_car_controller/psacc/resources/car_models.yml

**Comment by zamzon** [comment]
Thanks 
Is there a text editor in the container, I did try with sudo nano car_models.yml but that didn't work

**Comment by stevoh6** [comment]
No, in container isnt vi or nano :D You need to add it there manually.

**Comment by zamzon** [comment]
Okay I am not an expert to docker, how do I do this t manually.
Can I access the container from elsewhere?

**Comment by stevoh6** [comment]
> Okay I am not an expert to docker, how do I do this t manually. Can I access the container from elsewhere?

Its tricky, if you are running hassio os and psa is as addon. Last time when I was trying to do in friends hassioos it was pain and I didnt success. If you run separate containers (managed by you) you can exec into dontainer, search in google "docker exec container" ;)

**Comment by zamzon** [comment]
It installed nano with the command apt-get install nano, then I changed the car_models.yml file, but every time I restart, the container erases my changed.

Venlig Hilsen
Mads Munch

________________________________
Fra: stevoh6 ***@***.***>
Sendt: Tuesday, January 10, 2023 8:00:12 PM
Til: flobz/psa_car_controller ***@***.***>
Cc: zamzon ***@***.***>; Author ***@***.***>
Emne: Re: [flobz/psa_car_controller] Update the car_models.yml locally (Issue #456)


Okay I am not an expert to docker, how do I do this t manually. Can I access the container from elsewhere?

Its tricky, if you are running hassio os and psa is as addon. Last time when I was trying to do in friends hassioos it was pain and I didnt success. If you run separate containers (managed by you) you can exec into dontainer, search in google "docker exec container" ;)

**Comment by stevoh6** [comment]
> Is there a way to restart your software without rebooting the container ?

I have separate container, Restart doesn't rewrite code, rebuild does.
