### ISSUE TITLE
Distance uses GPS instead of odometer?

### ISSUE THREAD

**Issue by filipef101** [flobz/psa_car_controller#463]
Not sure if a bug or not, the distance seems wrong,

Ex instead of 2.5 it shows 1.3, Not expert in python but happy to take a look at this if someone wants to point me in the right direction

<img width="432" alt="image" src="https://user-images.githubusercontent.com/18123246/212328230-4cb640a4-5b56-4e23-9009-14f016f55cb3.png">

**Comment by flobz** [comment]
There is an algorithm that try to find trips based on a cars positions. This algorithm ignore short trips, that's why you have a difference.

**Comment by filipef101** [comment]
I see

**Comment by filipef101** [comment]
@flobz Thanks for clarifing! any option to remove that?
