### ISSUE TITLE
Preconditioning disconnected with result code 1

### ISSUE THREAD

**Issue by atze09** [flobz/psa_car_controller#47]
Today i have tried the preconditioning start, but i got the following error.
The Android app does also not work, may be that is the root cause?

`2021-03-15 07:07:25,983 :: INFO :: {"access_token": "TOKEN", "customer_id": "OP-ACNT200007641052", "correlation_id": "ID", "req_date": "2021-03-15T06:07:25Z", "vin": "FIN", "req_parameters": {"asap": "activate", "programs": {"program1": {"day": [0, 0, 0, 0, 0, 0, 0], "hour": 34, "minute": 7, "on": 0}, "program2": {"day": [0, 0, 0, 0, 0, 0, 0], "hour": 34, "minute": 7, "on": 0}, "program3": {"day": [0, 0, 0, 0, 0, 0, 0], "hour": 34, "minute": 7, "on": 0}, "program4": {"day": [0, 0, 0, 0, 0, 0, 0], "hour": 34, "minute": 7, "on": 0}}}}
192.168.17.102 - - [15/Mar/2021 07:07:25] "GET /preconditioning/FIN/1 HTTP/1.1" 200 -
2021-03-15 07:07:26,037 :: WARNING :: Disconnected with result code 1
192.168.17.102 - - [15/Mar/2021 07:07:26] "GET /favicon.ico HTTP/1.1" 200 -`

**Comment by flobz** [comment]
The issue doesn't respect the template. Please reopen one with the template.
