### ISSUE TITLE
Edit config of AddOn (home assistant)

### ISSUE THREAD

**Issue by Gabriele-tomai00** [flobz/psa_car_controller#482]
Hi, where is the config of PSA in Home Assistant OS?
I need to change config like energy price and weather (using openweathermap key).
I don't find PSA in addons folder (it's empty).
I have HA in a VM and PSA as addons from add-on store (I add it as add-on repositories).
So, when HA recognized it, I installed it as a normal add on.

Thanks

**Comment by flobz** [comment]
duplicate
