### ISSUE TITLE
SMS - OTP

### ISSUE THREAD

**Issue by Guizmos** [flobz/psa_car_controller#483]
Hi,

Thanks for this addon.
I have a problem at the OTP SMS step.
I don't receive any SMS
I own a Peugeot in France.
My mobile number is correctly entered on my Peugeot profile.
Tested with 06 xx xx xx xx and 3306 xx xx xx xx format

What is the solution to receive the code by SMS?

**Comment by sircuri** [comment]
Did you get the SMS when you installed the Peugeot App on your mobile device?

**Comment by Guizmos** [comment]
> Did you get the SMS when you installed the Peugeot App on your mobile device?

Never. I just uninstalled/reinstalled the app... but I don't have any text messages. I don't see anywhere in the settings where you can enable two-factor authentication.

thank you for your help

**Comment by sircuri** [comment]
It seems to me you never finished the enrollment/activation of your mobile device. Please double check your account with Peugeot and verify you have a verified/trusted phone number registered.

**Comment by Guizmos** [comment]
Ok I just realized something.
The Remote service is not compatible with my vehicle because it is neither hybrid nor electric...
To receive the SMS, the remote service must be activated...
Thanks to Peugeot for voluntarily limiting use to this service.
I will therefore resolve not to integrate my vehicle data into Home Assistant

Thanks for the replies and help

**Comment by flobz** [comment]
You can still get data with PSACC even if remote control is impossible.
