### ISSUE TITLE
service documentation

### ISSUE THREAD

**Issue by zarch1972** [flobz/psa_car_controller#49]
Would you be kind enough to document turning the code into a service so that it can run in the background on a server please?

I can see you have done this on the video, but unfortunately I don't speak French to work out what you've done.

Also, someway of storing your username and password would be helpful too, especially for running on a server.

Thank you for your great work.

**Comment by flobz** [comment]
You can easily connect another app to this one with the API which is documented. For example I use domoticz to control the charge of my vehicle. Maybe I didn't understood your question? 
An open issue already talk about user/password, please look at it.

**Comment by zarch1972** [comment]
Sorry for not being clearer.
On your video at 14 min you create the configuration so that you run the code with systemctl psa_car_controller.service

Is there any written documentation how to do this anywhere?

I would find it really useful to have text copy of the log file you use in the video so I can create that service too.

Thank you.

**Comment by iamrellah** [comment]
@zarch1972 
The youtube video does mention this in the description.


> sudo nano /etc/systemd/system/psa_car_controller.service
> ```
> [Unit]
> Description=Remote Control of PSA car
> After=network-online.target
> 
> [Service]
> Type=simple
> User=psa_remote
> WorkingDirectory=~
> ExecStart=/usr/local/bin/psa_car_controller -f config.json -c charge_config.json --mail toto@mail.com --password hunter2
> 
> [Install]
> WantedBy=multi-user.target
> 
> ```
> sudo chmod 0600 /etc/systemd/system/psa_car_controller.service
> sudo systemctl daemon-reload
> sudo systemctl enable --now psa_car_controller.service

**Comment by zarch1972** [comment]
Fab, thank you.  I didn't see that.

I think it would be very useful to add those to the GitHub instructions too.

I'll close this issue down as resolved. Thanks.

**Comment by flobz** [comment]
Yes It's in in my to-do list.
