### ISSUE TITLE
IS there anyway that these values could be set in the Addon config page in future releases? I've tried everything to get 2222 access and it'S just not happening.

### ISSUE THREAD

**Issue by codeclinic** [flobz/psa_car_controller#492]
IS there anyway that these values could be set in the Addon config page in future releases? I've tried everything to get 2222 access and it'S just not happening.

**Comment by kefrens** [comment]
same request.
seems we can't have 22222 access with a VM

Current setup is i have an intel NUC running win11.
Homeassistant is HaOS running through virtualbox (with the official vm image) - but i cant edit the startup config as it doesnt boot like the normal USB

i tried to ls through terminal but couldn't find anythin related to psacontroller
