### ISSUE TITLE
timed_odometer is null / none

### ISSUE THREAD

**Issue by FlorianHinrichsen** [flobz/psa_car_controller#515]
It seems that the parameter timed_odometer is renamed in to status request.

If I look into the response json from the status call, I see only a parameter named "odometer"
`   
"odometer": {
        "createdAt": "2023-04-13T07:30:49Z",
        "mileage": 51893.1
    },
`

This causes the issue, that no odometer / Mileage is not filled anymore.

**Comment by bbr111** [comment]
The same problem in my installation

**Comment by show2go** [comment]
same here, no milage, thx

**Comment by Ilpo55** [comment]
Same here, no  milage.

**Comment by Ilpo55** [comment]
After update to 3.0.11 mileage OK.
