### ISSUE TITLE
error after update and reinstall

### ISSUE THREAD

**Issue by Aikawa24** [flobz/psa_car_controller#528]
expected a single document in the stream in "<unicode string>", line 1, column 1: !ElecModel ^ (line: 1) but found another document in "<unicode string>", line 8, column 1: - !ElecModel ^ (line: 8)

**To Reproduce**
1. deinstalled and reinstalled after update of addon
2. selected brand, typed email and password, choosed DE as Country, klicked on submit
3. Does it persist after restarting the program?  Yes
4. Does it persist after recreate config by going to http://server_address:port/config? does not open in browser

**Config file**
Give the anonymize content of the config file

**Environment (please complete the following information):**
 - OS: debian
 - Brand and model of car Peugeot 2008e
 - Application version (commit number, branch or tag)
 - Log from http://server_address:port/log and browser console log

**Additional context**

**Comment by mdkeil** [comment]
fixed with 3.0.11, but maybe with additional new bugs.. If you don't need mileage/odometer at the moment, stay to 3.0.8.
