### ISSUE TITLE
Feature request: ability to move config out of docker container or to point to outside

### ISSUE THREAD

**Issue by RMHogervorst** [flobz/psa_car_controller#531]
The following issues all have to do with running psa_car_controller in a docker container (sometimes with home assistant)

- #482
- https://github.com/Flodu31/HomeAssistant-PeugeotIntegration/issues/34
- #249 
- #511 
- #492 

It would be super useful if the config lived outside the container. or if we could map the config folder from the container to an outside folder under user control.

**Comment by mdkeil** [comment]
For docker you can make a bind to the internal /config folder to have full access to all of the important configuration-files.

**Comment by codeclinic** [comment]
> For docker you can make a bind to the internal /config folder to have full access to all of the important configuration-files.

Interesting. But, that doesn't mean much to most users. Could you elaborate on what needs to be done?

**Comment by mdkeil** [comment]
> Interesting. But, that doesn't mean much to most users. Could you elaborate on what needs to be done?

it depends on the docker-environment.. e.g. [link1](https://docs.docker.com/storage/bind-mounts/) [link2](https://docs.portainer.io/user/docker/containers/advanced)

**Comment by RMHogervorst** [comment]
I mostly ask because I want to have the config outside the container  for home assistant, but I don't know what is needed to make that happen. I made a start at this issue in the home assistant repository https://github.com/flobz/psacc-ha/issues/31 but I'm unsure of how to proceed to test this

**Comment by RMHogervorst** [comment]
also so I can add the co2 signal and other tokens to the docker config

**Comment by codeclinic** [comment]
> > Interesting. But, that doesn't mean much to most users. Could you elaborate on what needs to be done?
> 
> it depends on the docker-environment.. e.g. [link1](https://docs.docker.com/storage/bind-mounts/) [link2](https://docs.portainer.io/user/docker/containers/advanced)
> 
> https://github.com/flobz/psa_car_controller/blob/master/docs/Docker.md

In most cases (as is mine) people are going to be using this as an addon via a HassOS rpi based system.

**Comment by flobz** [comment]
Look at https://github.com/flobz/psacc-ha/tree/main/psacc-ha#modify-config-file
Config is already map outside container.
