### ISSUE TITLE
errors on logs

### ISSUE THREAD

**Issue by lvenditti** [flobz/psa_car_controller#534]
First of all thanks for this very GREAT job!

just for information, I'm finding the follow error into log:

2023-04-16 16:36:31,701 :: ERROR :: get_control_tabs:
Traceback (most recent call last):
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/control.py", line 38, in get_control_tabs
preconditionning_state = car.status.preconditionning.air_conditioning.status != "Disabled"
AttributeError: 'NoneType' object has no attribute 'preconditionning'

I don't know if it is related to car's position, because the position are no longer reported on map but the trip are there (without altitude). 

Hope could be useful to fix errors un new release.

I'm running psa_car_controller on docker on raspberry pi 4, car is Citroen E-C4

Bye

**Comment by mdkeil** [comment]
Take a look in your cars.json. If there are two separate  entries with the same vin.. stop the container, remove the cars.json and restart the container again.

**Comment by lvenditti** [comment]
> Take a look in your cars.json. If there are two separate entries with the same vin.. stop the container, remove the cars.json and restart the container again.

You right, I found the json structure repeated twice into cars.json.

I did what you suggested and now there is only one json structure into cars.json file.

This will fix also the other issue I mentioned in prevoius message about position and map?

Many thanks for your help

Ciao.
