### ISSUE TITLE
100% Battery level and 0km autonomy with DS7

### ISSUE THREAD

**Issue by Philippehaz** [flobz/psa_car_controller#537]
** Problem **
There is a bug in the stellantis/PSA API, for my car at least, where sometime the autonomy is 0km and so battery empty, still the API returns battery level as 100%. I confirm this is incorrect info coming from PSA (also in their app), and not caused by the app. This however cause other issues with the app:

- mess up the recording and retrieving/displaying of info: I dind't have time to investigate it further yet;

- with charge control enabled, the app will stop the charge, even if the stop charge level is set to 100%, when it sees that the battery level is 100%, although in reality battery is empty. => I am setting the charge level to 101% as workaround.

** Fix options **
- Currently when the charge level is set at 100%, the psa controller stops the charge when it receives a 100% battery level. It would be best not to stop the charge in this case, as it creates issue with my particular case, but also, during winter, when using preconditioning, I want the car to resume charging in the morning during/after preconditioning, even if it had reached full charge before.
- A fix could be done in the app to detect and correct PSA bug. I.e., battery level is 100% but autonomy doesn't match (0km or below at a certain treshold), then update battery level to 0% (or value estimated as correct)

**Comment by virtualj** [comment]
I think it is fixed in 3.0.10 under my suggestion https://github.com/flobz/psa_car_controller/pull/503

**Comment by Voz-DeCarabas** [comment]
I have this for my Peugeot e208 and I'm on PSA Car Controller v3.0.12

**Comment by flobz** [comment]
fixed in last version
