### ISSUE TITLE
Error while fetching data

### ISSUE THREAD

**Issue by jul78000** [flobz/psa_car_controller#552]
Once logged and cars fetched, in the log panel I read errors and the main page remains empty...
![image](https://github.com/flobz/psa_car_controller/assets/8665001/3194f089-ff79-40e0-b043-ed666df26f66)

![image](https://github.com/flobz/psa_car_controller/assets/8665001/33cb96a3-1469-49da-80bf-864bf630036e)

Thank you for your help

**Comment by Dizzybacon** [comment]
Try http://ipaddress:5000/wakeup/yourvin that helped for me. Got the data populated in those screens anyway.

I see similar errors in the logs when going to the vehicle page though.
