### ISSUE TITLE
Docker image - how to integrate OpenWeather API and Map Vizualization

### ISSUE THREAD

**Issue by bs0001** [flobz/psa_car_controller#553]
Hi,

thanks for your cool project here!
I already read the instructions but does not understand how to activate the map and use OpenWeather API.
I run your project in a docker container in my NAS.

In your instruction you wrote this:
You can add the -r argument to record the position of the vehicle and retrieve this information in a dashboard.
python3 psa-car-controller -f config.json -c charge_config.json -r
Do I have to put this line into my configuration file for creating the docker container?
If not, where have I to run this argument?

OpenWeather API
I have already an API key.
Can I put the key also into the docker configuration file for creating the container?
How is the syntax for that?
If not, where and how can I put my API key?

It would be helpful if you can give me further advice how to do that!

BR
Bernd

**Comment by DavideFioravanti** [comment]
In theory it should already enabled. It should be set in the `PSACC_OPTIONS` variable of the docker.
`PSACC_OPTIONS: -c -r --web-conf`

However I also have the same problem: the map is empty and I don't see the altitude difference. I think that there is a problem obtaining the position from the server.
Moreover I also don't get the temperature:
![image](https://github.com/flobz/psa_car_controller/assets/2470733/74bcff98-0549-44f8-80fa-2b794442f1b7)

**Comment by flobz** [comment]
I update the doc to help you : https://github.com/flobz/psa_car_controller/blob/master/docs/Docker.md
