### ISSUE TITLE
Wrong date format in the "Consumption of the car" graph. "Consumption by temperature" graph not working. Map not working.

### ISSUE THREAD

**Issue by DavideFioravanti** [flobz/psa_car_controller#559]
In the dashboard the X axis of the "Consumption of the car" graph, is in a strange format instead of date.
![image](https://github.com/flobz/psa_car_controller/assets/2470733/1cee4160-df6b-44ba-aa61-8c2e07071d3b)
I am from Italy, but the container is using the default POSIX locale. Maybe the date format is wrong?
```
root@123456789:/config# locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```

The "Consumption by temperature" graph is not working
![image](https://github.com/flobz/psa_car_controller/assets/2470733/d27a287e-af11-4b11-bd21-aa14957dae81)
Map is not working, it points to 0,0
![image](https://github.com/flobz/psa_car_controller/assets/2470733/a9dcfbb6-6c11-442e-a07e-e674cf68ec46)
I think that these two last problems are related to the missing telemetry. However the official app shows the position correctly (sometimes)
In the log I see this: `{"status": "ok", "missing": "Missing telemetry: power, speed, lat, lon, "}`

**To Reproduce**
Steps to reproduce the behavior: _Just start the container_
1. what command did you use
_Nothing special_
2. when the bug append ?
_Always_
3. Does it persist after restarting the program? 
_Yes_
4. Does it persist after recreate config by going to http://server_address:port/config? 
_Yes, I even tried to recreate the container again, but same result_

**Config file**
CONFIG.INI
```
[General]
currency = €
# minimum trip length in km so it's added to stats and map in website
minimum trip length = 10
# for future use
length unit = km
[Electricity config]
# price by kw/h
day price = 0.40
night price
# ex: 22h30
night hour start
# ex: 6h00
night hour end
dc charge price
high speed dc charge price
# minimum power in kW that should be delivered during a charge so it can be considered as a high speed charger
high speed dc charge threshold
charger efficiency = 0.8942
```
CONFIG.JSON
```
{
    "abrp": {
        "abrp_enable_vin": [
            "ANONYMIZED"
        ],
        "token": "ANONYMIZED"
    },
    "client_id": "ANONYMIZED",
    "client_secret": "ANONYMIZED",
    "co2_signal_api": "ANONYMIZED",
    "country_code": "IT",
    "customer_id": "ANONYMIZED",
    "proxies": {
        "http": "",
        "https": ""
    },
    "realm": "clientsB2CPeugeot",
    "refresh_token": "ANONYMIZED",
    "remote_refresh_token": "ANONYMIZED",
    "weather_api": "ANONYMIZED"
}
```

**Environment (please complete the following information):**
 - OS: _NAS QNAP (DOCKER IMAGE)_
 - Brand and model of car: _Peugeot e208_
 - Application version (commit number, branch or tag): _3.0.12_
 - Log from http://server_address:port/log and browser console log:
 _I also enabled the debug flag but I don't see any error or warning._

**Comment by flobz** [comment]
what is the result of http://<change by nas ip>:5000/get_vehicleinfo/YOURVIN ?

**Comment by flobz** [comment]
the content of the response show that its duplicate with https://github.com/flobz/psa_car_controller/issues/50

**Comment by DavideFioravanti** [comment]
So, the problem is caused by Peugeot and it's not fixable? The dates format are wrong for everyone?

**Comment by kvikindi** [comment]
Same problem displaying date here. Uk localisation, don't know if that has anything to do with it...
