### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by cedsib** [flobz/psa_car_controller#56]
Hello,

I installed correctly all the dependancies but when I try to install requirements.txt (or -dev whatever) I have the same error.

Any cluue ?

`root@NAS:~/psa_car_controller# pip3 install -r requirements.txt
Collecting paho-mqtt>=1.5.0 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/32/d3/6dcb8fd14746fcde6a556f932b5de8bea8fedcb85b3a092e0e986372c0e7/paho-mqtt-1.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-mvl69k71/paho-mqtt/`

**Comment by flobz** [comment]
Google first result will fixed the problem. 
 https://www.google.com/search?q=ModuleNotFoundError%3A%20No%20module%20named%20%27setuptools%27%0A%0A&ie=utf-8&oe=utf-8&client=firefox-b-m

**Comment by cedsib** [comment]
I'm verry sorry, I looked at it but without any luck.
That part works !
