### ISSUE TITLE
Stopped displaying trips and charging history

### ISSUE THREAD

**Issue by jwolansk** [flobz/psa_car_controller#565]
**Describe the bug**
Hello, thanks for the useful software!

I have PSA controller running in docker as a Home Assistant Addon.

Some 2 month after installation it stopped displaying the trips data on the dashboard with the message "No data to show, there is probably no trips recorded yet". I noticed that just after the recent HA update to latest version, maybe it's related?

The database is growing after the car is driven or charged, data is fetched from PSA as I can see it live in dashboard and in HA.

How to debug it further?

thanks

**Environment (please complete the following information):**
 - OS: Home assistant addon
 - Peugeot e208
 - Application version Addon version 3.0.12
 - Log from http://server_address:port/log and browser console log

**Additional context**

[config.ini.txt](https://github.com/flobz/psa_car_controller/files/11757026/config.ini.txt)
[psa.log](https://github.com/flobz/psa_car_controller/files/11757335/psa.log)

**Comment by jwolansk** [comment]
Hey, apparently the container restart through Portainer made it to display the history again 🧐
The Addon restart through HA didn't work, as it is not a restart but the container is recreated from scratch.
How do I interpret that?

**Comment by Ilpo55** [comment]
I have the same issue.
Restart through Portainer did not help.

**Comment by Ilpo55** [comment]
I had to uninstall / reinstall the PSACC Add-On to make it work. 
History was of course gone.

**Comment by FEmser** [comment]
I have the same issue. I pinned it down a little.
I manually edited the info.db file and after i clear the "position" data, psacc will show the dashboard "fine".
Meaning charges will be shown and the calculation fields will be shown emtpy.
If I write *anything* into the position data, the webUI will show "No data to show, there is probably no trips recorded yet" again on every tab exept control.

**Comment by FEmser** [comment]
I played around a little more and found the actual issue (at lease for me)!
The position data was fine and instead there was a row in the battery data which had no stopping time.
After deleting that row, everything worked normally again.
I think this was caused by crash of the raspberry or a reboot or somthing...

Maybe that can help you too :)
And maybe some kind of data validation can be added to remove invalid lines instead of everything not working anymore.
Thanks for the great work flobz <3

**Comment by jwolansk** [comment]
Hey, thanks! I'll have a look at my database 🙂

**Comment by gerar19** [comment]
> ¡Jugué un poco más y encontré el problema real (al menos para mí)! Los datos de posición estaban bien y en su lugar había una fila en los datos de la batería que no tenía tiempo de parada. Después de eliminar esa fila, todo volvió a funcionar con normalidad. Creo que esto fue causado por una falla de Raspberry o un reinicio o algo así...
> 
> Quizás eso también pueda ayudarte :) Y tal vez se pueda agregar algún tipo de validación de datos para eliminar líneas no válidas en lugar de que todo ya no funcione. Gracias por el gran trabajo flobz <3
> 
> ![2023-09-26 16_36_43-Dejó de mostrar viajes e historial de carga · Problema #565 · flobz_psa_car_contr](https://user-images.githubusercontent.com/52786503/270694782-5721ad45-e5b3-43b8-8b1a-e9e54c513656.png)

How i Can acces to this table? thanks

**Comment by FEmser** [comment]
I used the tool "DB Browser for SQLite" (https://sqlitebrowser.org/)
You just need a SQLite tool to open the "info.db" file.

**Comment by Omaaar90** [comment]
I had the same issue. I looked into the database and everything seemed fine. I restarted the container using docker stop <container id> and then docker start <container id>. Refreshed the page and everything works again.

**Comment by henkiejan1** [comment]
> I played around a little more and found the actual issue (at lease for me)! The position data was fine and instead there was a row in the battery data which had no stopping time. After deleting that row, everything worked normally again. I think this was caused by crash of the raspberry or a reboot or somthing...
> 
> Maybe that can help you too :) And maybe some kind of data validation can be added to remove invalid lines instead of everything not working anymore. Thanks for the great work flobz <3
> 
> ![2023-09-26 16_36_43-Stopped displaying trips and charging history · Issue #565 · flobz_psa_car_contr](https://user-images.githubusercontent.com/52786503/270694782-5721ad45-e5b3-43b8-8b1a-e9e54c513656.png)

But how did you delete that row?? I used sql lite browser but when i select and pres del om my keyboard the row is right there... ???

**Comment by flobz** [comment]
Not able to reproduce the issue.
