### ISSUE TITLE
Is this project only for electric / hybrid cars?

### ISSUE THREAD

**Issue by eric1905** [flobz/psa_car_controller#572]
I am currently trying to use this controller with my car (308 SW, year 2016). I want it just to retrieve my current fuel and the last trips. Is this possible with this controller or is it only possible with newer cars / with electricity cars?
I saw that I need the sms for control, but as I don't think controll is possible, I changed the psacc_option in Home Assistant Addon to: -r --web-conf -c --remote-disable

I am using the mypeugeot app on my smartphone to get the values, but I think they are not stored on peugeot servers, just on my smartphone. So I wonder how the controller could receive the information? Are there any other things needed?

I also tried to modify the config file according to this manual: https://github.com/flobz/psacc-ha/tree/main/psacc-ha#modify-config-file
But after logging to homeassistant via ssh and executing the command I get this output: /mnt/data/supervisor/addons/data/b9f12d83_psacc

but my /mnt folder is empty.  So there are no files I could modify.

**Environment (please complete the following information):**
 - OS: Home Assistant Add-On
 - Peugeot 308 SW

**Comment by Gamalta** [comment]
J'ai le même problème,
j'ai pu essayer sur :

- Windows
- Linux
- Home Assistant OS

À chaque fois, j'obtiens le message `"No vehicle found"`.

La connexion me renvoie bien ``"Success !!! [Go to otp config]"``, mais j'attends toujours le SMS, donc je suis obligé de relancer avec `--remote-disable` mais rien de plus (je suis sur un iPhone).

Je possède une Peugeot 208 GT diesel de 2022 (mon VIN n'étant pas dans la liste car_models.yml `VR3UBYHTKMT.**`), et sur l'application, je dispose bien de toutes les informations telles que le niveau d'essence, les trajets ou encore l'autonomie restante.

Je me suis permis de rédiger en français, l'auteur étant français.

**Comment by cascer1** [comment]
Your car needs to have connected services (I think the name differs between brands, for Opel it's called Opel Connect). You may have to activate it in your Peugeot account (I had to for my Opel)

**Comment by Gamalta** [comment]
@cascer1 I can't find any settings on my Peugeot account at https://mypeugeot.peugeot.fr/. It is currently working fine with the MyPeugeot application, but not with this tool.

**Comment by cascer1** [comment]
Can you view stuff like the odometer value or control the AC remotely from the app? If it only works when close to your car, it sounds to me like it uses Bluetooth.

**Comment by flobz** [comment]
It depends of car release date, if the car is too old PSACC wont works.
