### ISSUE TITLE
[feature]HACS plug-in

### ISSUE THREAD

**Issue by GeraldPape** [flobz/psa_car_controller#574]
can you create a HACS compatible version of your great plugin to have it easily installed and configured (without the need to ssh?)
Thank you!

**Comment by JaySea77** [comment]
You can install as addon without the need of Hacs.

**Comment by flobz** [comment]
close due to inactivity

**Comment by GeraldPape** [comment]
In HASSOS not possible, as SSH to supervisor seems not possible.
