### ISSUE TITLE
Failed to install the component

### ISSUE THREAD

**Issue by solproget** [flobz/psa_car_controller#584]
Me too with the same problem.
How can I fix?

![Screenshot 2023-07-12 090532](https://github.com/flobz/psa_car_controller/assets/77103958/d0e45153-1c9c-41b3-a9f8-6e4f00d29ec3)

**Comment by 63snoopy** [comment]
Exact same issue! No solution yet ?

**Comment by flobz** [comment]
ha issue not psacc
