### ISSUE TITLE
cannot start server - Opel Corsa-e

### ISSUE THREAD

**Issue by psimone68** [flobz/psa_car_controller#59]
**2021-04-01 09:26:30,913 :: ERROR :: Traceback (most recent call last):
  File "c:\Users\eliseo\Documents\psa_car_controller-master\ChargeControl.py", line 91, in process
    if self._next_stop_hour < now:
TypeError: '<' not supported between instances of 'NoneType' and 'datetime.datetime'**

**To Reproduce**
python server.py -f test.json -c charge_config1.json

**Environment (please complete the following information):**
 - OS: Windows 10
 - Android app Version MyOpel 1.29.0
 - Opel Corsa-e
 - Application version (commit number, branch) 

**Additional context**
[activity.log](https://github.com/flobz/psa_car_controller/files/6241827/activity.log)

**Comment by flobz** [comment]
Thanks for reporting the problem.
It's fixed now : 72ff63c
