### ISSUE TITLE
Consumption calculation in charge tab

### ISSUE THREAD

**Issue by mdauphin** [flobz/psa_car_controller#599]
First, thank you for your job, Peugeot doesn't want to get the best out of its car in its application, what a shame!

I want to precise Consumption is charge tab, is base on percent charge of the vehicle and max charge:
-   35% => 80% ( +45% )
-  45  / 100 * 46 = 20.7 kWh
 
**I think it will be great to use the charger efficiency to display the real consumption, not only for price.**

And I made some test on charger efficiency with (Tuya 3 Phase Wifi Energy meter), and I found:
- day 1 Tuya 21.25kWh => PSA car ctrl 20.7, efficiency = 0.974
- day 2 Tuya 21.91kWh => PSA car ctrl 20.7, efficiency = 0.944
- day 3 Tuya 23.87kWh => PSA car ctrl 22.54, efficency = 0.944

The default value in config file is 0.8942, where is come from ? I look like lower than my calculation...
I'm using the original 16A charger with a Green'up plug.

**Comment by flobz** [comment]
Hello,
I take 0.8942 value from internet. 
It might depends of the car model, what car do you have ?

**Comment by mdauphin** [comment]
Peugeot e208 with the original 16A charger with a Green'up plug.
I will wait multi charge, to calculate a good mean efficiency.

**Comment by flobz** [comment]
An efficiency of 95.5 seems too good.

**Comment by SabatoArdolino** [comment]
> charger efficiency

Where Can i found this value ? I've a grandland x hybrid and i want to know the exact value 
Thanks

**Comment by flobz** [comment]
Closing because too few people interested by this feature sorry.
