### ISSUE TITLE
Documentation for home assistant add-on possibly wrong for price update instructions

### ISSUE THREAD

**Issue by bgoncal** [flobz/psa_car_controller#602]
Hey folks, Ive been following the instructions to create my config and update the price per kWh but I think the instructions are incorrect or my setup is incorrect.
Context: Everything is working perfectly for me, I just can't create my config file.

 
<img width="1070" alt="Screenshot 2023-08-11 at 19 39 00" src="https://github.com/flobz/psa_car_controller/assets/5808343/1ca1e98f-52c3-4f40-a172-d11d160f3835">
<img width="772" alt="Screenshot 2023-08-11 at 19 39 04" src="https://github.com/flobz/psa_car_controller/assets/5808343/d51d09cf-63d3-4107-a0e0-2a58d5e27f85">

**Comment by kagehisa** [comment]
Same problem here. It is possible to edit the settings vie the UI but they are not persistent. The Post install docker command gives me a similiar path as @cpvbruno. But it seems that path is not existant or missing the leading part of the path that shows where docker is storing the image.

**Comment by cpvbruno** [comment]
I was able to update the config file but through a very "difficult" way... I used Portainer addon to see all HA containers, then I open a console on PSA addon container and then I found the config file and edit it

**Comment by kagehisa** [comment]
Thak you I will try that but it would still be nice to do this directly on the console.

**Comment by bgoncal** [comment]
> > I was able to update the config file but through a very "difficult" way... I used Portainer addon to see all HA containers, then I open a console on PSA addon container and then I found the config file and edit it
> 
> 
> 
> Could u tell me how i can do this? when i go to portainer and open the console on the psacc addon, i dont get nothing tho 

I don't recall exactly the path, but you need to find the config file and then use vi or nano to edit it, let me know if you find it

**Comment by Holewijn** [comment]
> > > I was able to update the config file but through a very "difficult" way... I used Portainer addon to see all HA containers, then I open a console on PSA addon container and then I found the config file and edit it
> > 
> > 
> > Could u tell me how i can do this? when i go to portainer and open the console on the psacc addon, i dont get nothing tho
> 
> I don't recall exactly the path, but you need to find the config file and then use vi or nano to edit it, let me know if you find it

Found it 
cd /data
nano config.ini
