### ISSUE TITLE
PSA Session invalidated handling

### ISSUE THREAD

**Issue by jwolansk** [flobz/psa_car_controller#603]
**Describe the bug**
The PSA addon in HA stopped working with 502 Bad Gateway error. I guessed that it might be the PSA session error as my peugeot app needed re-pairing at the same time.
The only way I found to force pairing again was to remove contents of the /data folder. But then I lose all history. Copying old info.db over the new one seems to partially work as the logs show that there is some communication with PSA servers, but the webserver won't start and 502 error is present again
Is there a way to trigger re-pairing with user account without losing data? Or is it possible to migrate old database to the new installation?
 Thanks for any input!
**Environment (please complete the following information):**
- Home Assistant
- Peugeot e208

[psa.log](https://github.com/flobz/psa_car_controller/files/12328494/psa.log)

**Comment by flobz** [comment]
you can keep the database.
