### ISSUE TITLE
Can't login on new install

### ISSUE THREAD

**Issue by youradds** [flobz/psa_car_controller#610]
**Describe the bug**

I can't log in. I'm entering the details I log in at connect.vauxhall.co.uk, but I get the JSON response:

`Traceback (most recent call last): File "/usr/local/lib/python3.10/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 48, in firstLaunchConfig token = res.json()["accessToken"] KeyError: 'accessToken' HOST_BRANDID : https://id-dcr.vauxhall.co.uk/mobile-services sitecode: VX_GB_ESP{"session":"8e9dd096c59a8885a256144348544b6e","returnCode":"NEED_AUTHORIZATION","token":"b16bb03bab4246d140c83b0c5fbff543846ef5592de7545cfd4d5d3e208cdfb2","fields":{"USR_PASSWORD":"SETPWD_LABEL_8"}}`

**To Reproduce**

Simply installed, and trying to setup using :

Who: Vauxhall
Email: my email address
Password: the one I login at connect.vauxhall.co.uk with

Then press "submit", and I get the response after a few seconds. 

**Config file**
Give the anonymize content of the config file

**Environment (please complete the following information):**

Ubuntu 22.04
Vauxhall Corsa-F 

**Additional context**

Booting up with:

python3 /usr/local/bin/psa-car-controller --web-conf

When I try and setup the config (logging in with my details), I get:

`Traceback (most recent call last): File "/usr/local/lib/python3.10/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 48, in firstLaunchConfig token = res.json()["accessToken"] KeyError: 'accessToken' HOST_BRANDID : https://id-dcr.vauxhall.co.uk/mobile-services sitecode: VX_GB_ESP{"session":"8e9dd096c59a8885a256144348544b6e","returnCode":"NEED_AUTHORIZATION","token":"b16bb03bab4246d140c83b0c5fbff543846ef5592de7545cfd4d5d3e208cdfb2","fields":{"USR_PASSWORD":"SETPWD_LABEL_8"}}`

**Comment by SteveJack34** [comment]
Is Country to GB?

**Comment by youradds** [comment]
@SteveJack34  yes it was. Weirdly, I tried it the next day and it worked fine the 1st time! Maybe an issue with the PSA servers (wouldn't be the first time!)
