### ISSUE TITLE
Can't get car model please check cars.json

### ISSUE THREAD

**Issue by iamrellah** [flobz/psa_car_controller#62]
**Describe the bug**
Starting the server mentions this in the logging: Can't get car model please check cars.json. This file seems to be auto generated. The content of the file currently is:
```
[
    {
        "battery_power": 46,
        "brand": "C",
        "fuel_capacity": 0,
        "label": null,
        "max_elec_consumption": 70,
        "max_fuel_consumption": 0,
        "vehicle_id": "ID",
        "vin": "VIN"
    }
]
```

Should the "brand" be filled with something else then "C"? My car is an Opel Corsa-e.
Im running the script with the latest commit (72ff63c05f4021a6b2271e23591a4973dfd997ea)

**To Reproduce**
1. Run server.py
2. Look in the log if the server is started successfully
3. Log return the warning: Can't get car model please check cars.json

**Config file**

```
{
    "client_id": "ID",
    "client_secret": "SECRET",
    "country_code": "NL",
    "customer_id": "ID",
    "proxies": {
        "http": "",
        "https": ""
    },
    "realm": "clientsB2COpel",
    "refresh_token": "TOKEN",
    "remote_refresh_token": "TOKEN",
    "weather_api": null
}
```

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Android app Version: 1.29.0
 - Brand and model of car: Opel Corsa-E
 - Application version: 72ff63c05f4021a6b2271e23591a4973dfd997ea

**Comment by flobz** [comment]
Thanks for reporting this issue.
It's normal behavior. O didn't know the label corresponding to the corsa-e

**Comment by flobz** [comment]
done by this commit 00b343f
