### ISSUE TITLE
Expirated Certificate (DS BRAND)

### ISSUE THREAD

**Issue by giteki** [flobz/psa_car_controller#625]
**Describe the bug**
Like https://github.com/flobz/psa_car_controller/issues/617 but with **DS BRAND**
On latest docker image, get the following error message :
`Traceback (most recent call last): File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 78, in firstLaunchConfig res_dict = res2.json()["success"] KeyError: 'success' {"code":"495", "message": "Invalid or expired client certificate"} `

<img width="327" alt="screenshot" src="https://github.com/flobz/psa_car_controller/assets/117861044/bbe747ac-c6fc-46ca-8ac6-47cd2d014286">

**To Reproduce**
download the latest container image
config your api access with DS brand selection.

It sounds like the same problem of certification expiration with the DS apk. Could you please update the docker image ?

**Comment by flobz** [comment]
Hello,
can you retry ?

**Comment by giteki** [comment]
It works like a charm with the latest docker release. Thanks
