### ISSUE TITLE
HTTPSConnectionPool

### ISSUE THREAD

**Issue by pedroresende** [flobz/psa_car_controller#627]
**Describe the bug**
When I attempt to register I get the following message

![image](https://github.com/flobz/psa_car_controller/assets/951377/3caa9688-3102-4bcf-9d10-e441f6dabae1)

**To Reproduce**
1. what command did you use
2. when the bug append ? Registration 
3. Does it persist after restarting the program? Yes
4. Does it persist after recreate config by going to http://server_address:port/config? Yes, it does

**Config file**
Give the anonymize content of the config file

[General]
currency = €
# minimum trip length in km so it's added to stats and map in website
minimum trip length = 10

length unit = km
[Electricity config]
# price by kw/h
day price = 0.2135
night price = 0.145
# ex: 22h30
night hour start = 22h00
# ex: 6h00
night hour end = 7h00
dc charge price
high speed dc charge price
# minimum power in kW that should be delivered during a charge so it can be considered as a high speed charger
high speed dc charge threshold
charger efficiency = 0.8942

**Environment (please complete the following information):**
 - OS: [e.g. Windows] -> Linux
 - Brand and model of car -> Peugeot e2008
 - Application version (commit number, branch or tag) -> Master (4b77e593d7de8485a14bb3616e467242f5fab067)
 - Log from http://server_address:port/log and browser console log

**Additional context**

**Comment by flobz** [comment]
This is a problem of your server not being able to access to github, not a PSACC issue.
