### ISSUE TITLE
Disable / Reset Stop Charge Hour

### ISSUE THREAD

**Issue by mhellmeier** [flobz/psa_car_controller#633]
The README shows different information on how to use the app. Here, it is mentioned how to set a time-based charging end:
```
2.3 Set hour to stop the charge to 6am
http://localhost:5000/charge_control?vin=yourvin&hour=6&minute=0
```

If set one time, the charging will always end at 6 a.m., every day. Is there any API call to reset the stop hour back to default (=nothing)?

**Comment by tomechio** [comment]
You could try to set the hour to 0.
http://localhost:5000/charge_control?vin=yourvin&hour=0&minute=0

If I remember correctly in some discussion this hour/minute combination was mentioned as reset.

**Comment by JaySea77** [comment]
Stop charge 0:00 is indeed reset to no stop time.

**Comment by mhellmeier** [comment]
Thanks, that worked!
