### ISSUE TITLE
Last location on map is correct but query comes up with old location

### ISSUE THREAD

**Issue by JaySea77** [flobz/psa_car_controller#641]
The location on the map shows my current location as last location using the pin on the map.
My location from work where I have left a couple hours ago still shows when I use http://localhost:5000/get_vehicleinfo/YOURVIN.
The location on http://localhost:5000/get_vehicleinfo/YOURVIN hasn't changed since I got to work this morning.

 - OS: home assistant
 - Car: Citroën ë-C4
 - Application version: v3.0.12

**Comment by flobz** [comment]
Anybody have the same issue ?

**Comment by JaySea77** [comment]
The thing is that it doesn't always do this so I do not know how to reproduce.

**Comment by Holewijn** [comment]
I have this now and then when i leave work it stays in the middle, it takes some time when it will update. And also the trip distance is then incorrect but milage is good. 

OS: Homeassistant 
Car: Opel Corsa e
App version: Latest just got it updated
