### ISSUE TITLE
Cannot get otp error

### ISSUE THREAD

**Issue by DavidFFerreira** [flobz/psa_car_controller#643]
After last HA update i cannot get the PSA Controller working anymore
Got some error.
what I did:
uninstall on a smartphone the app mycitroen
Install on a smartphone the app mycitroen
You should be asked to give your credentials
Connect and test remote control,
I already did unistall the addon. Restart HA, Install the addon again
Gave my email, password and coutry
Got the OTP Code and create a new pin
After that, i got those errors
![image](https://github.com/flobz/psa_car_controller/assets/32928749/c2006f98-711d-4265-a97c-90724172c221)

**Comment by GeraldPape** [comment]
Have this sometime after a reboot. 

Let some time go by then try again. If it won't help, delete all phones. In the app click on the person symbol top right, your name. There is a section registered smartphones or so. Delete them. Wait several minutes and then try again. 

Last time this happened to me it took about one week until I was able to use the pas car controller again.

**Comment by DavidFFerreira** [comment]
i'm like that, almost 3 months xD

**Comment by flobz** [comment]
Did you read the FAQ ?

**Comment by DavidFFerreira** [comment]
@flobz did you read all the spets I made? the same as the FAQ ... and it dont work
