### ISSUE TITLE
Docker latest image - v3.0.10rc1 instead of v3.0.12

### ISSUE THREAD

**Issue by Mikado8231** [flobz/psa_car_controller#647]
Hi,

Any reason why the docker **latest** image is related to psa_car_controller v3.0.10rc1 instead of v3.0.12 ?

Thanks.

Latest
https://hub.docker.com/layers/flobz/psa_car_controller/latest/images/sha256-403e428f8822ecc6930d9cdd7216525a40087826c1d9187c57f9c1a5740ff440?context=explore

v3.0.10rc1
https://hub.docker.com/layers/flobz/psa_car_controller/v3.0.10rc1/images/sha256-403e428f8822ecc6930d9cdd7216525a40087826c1d9187c57f9c1a5740ff440?context=explore

v3.0.12
https://hub.docker.com/layers/flobz/psa_car_controller/v3.0.12/images/sha256-13bba50a5a7cec59ff945ba718f2a89e96f316ffb9500885a8513bd5532556e0?context=explore

**Comment by flobz** [comment]
yes it was a mistake in the pipeline, not latest should be related to 3.0.13
