### ISSUE TITLE
 Can't get car model please check cars.json for corsa-e

### ISSUE THREAD

**Issue by xammmue** [flobz/psa_car_controller#65]
When initializing the car from MyPSACC.py get_vehicles, the following warning pops up even though the model corsa-e was recently added
`WARNING :: Can't get car model please check cars.json`

This is how the deserialized response looks:
```
{
 'brand': 'C',
 'created_at': None,
 'embedded': None,
 'engine': None,
 'id': 'someLongId',
 'label': None,
 ...
```

This is how the API response looks:
```
{
   "vehicles":[
      {
         "id":"theVehicleId",
         "vin":"theVIN",
         "brand":"C",
         "_links":{
            "alerts":{
               "href":"https://api.groupe-psa.com/connectedcar/v4/user/vehicles/theVehicleId/alerts"
            },
            "trips":{
               "href":"https://api.groupe-psa.com/connectedcar/v4/user/vehicles/theVehicleId/trips"
            },
            "self":{
               "href":"https://api.groupe-psa.com/connectedcar/v4/user/vehicles/theVehicleId?locale=fr-FR"
            },
            "lastPosition":{
               "href":"https://api.groupe-psa.com/connectedcar/v4/user/vehicles/theVehicleId/lastPosition"
            },
            "telemetry":{
               "href":"https://api.groupe-psa.com/connectedcar/v4/user/vehicles/theVehicleId/telemetry"
            },
            "maintenance":{
               "href":"https://api.groupe-psa.com/connectedcar/v4/user/vehicles/theVehicleId/maintenance"
            },
            "status":{
               "href":"https://api.groupe-psa.com/connectedcar/v4/user/vehicles/theVehicleId/status"
            }
         }
      }
   ]
}
```

The recent changes in 00b343f5dd1ed34d48f4b8ddce61329ca82aac67 expect the label for that car to be "C" (which would actually make sense). However the API returns no label but brand "C" which then does not lead to a recognition of the car model.

**Comment by xammmue** [comment]
I added a PR with a possible workaround.

Would be great if someone else with a corsa-e could verify that behavior.
I wonder whether Stellanties/PSA/Opel will continue with that naming scheme (C = corsa? -> M = Mokka??) or if I am missing something here

**Comment by flobz** [comment]
Hello,
Thanks for your help @xammmue .
I wonder, did you use app_decoder.py script recently ? If not can you try it because it use an other api that could get the right model.

**Comment by xammmue** [comment]
At first I didn't. I noticed that my running version called the constructor of Car 2 times. First from "from_json" which worked because of an old cars.json. Second time with the API result which failed.

I also ran the app_decoded just know, which also lead to the problem.

old cars.json (created with an older version of app_decoded.py)
`        "battery_power": 46,
        "brand": "Opel",
        "fuel_capacity": 0,
        "label": "C",
...
`

Newly created cars.json
`
"battery_power": 46,
        "brand": "C",
        "fuel_capacity": 0,
        "label": null,
...
`

So it must have worked correctly once, but I can't tell if the issue was caused by an update of the scripts or a change in the PSA API result

**Comment by CWfFO** [comment]
Hi, i have the same behavior. Also Corsa-e and WARNING :: Can't get car model please check cars.json

**Comment by xammmue** [comment]
Were you able to check the API result? 
Easiest way would be to add the following in MyPSACC.py line 226
`                print(vehicle)`
so that it looks like this:
`            for vehicle in res.embedded.vehicles:
                print(vehicle)
                self.vehicles_list.add(Car(vehicle.vin, vehicle.id, vehicle.brand, vehicle.label))`

**Comment by CalicodesIles** [comment]
Not sure if it's clearly related but it seems that I have the same issue with a Peugeot e208 (which is weird since I don't remember that I had this issue before).

In activity.log at startup
`[WARNING :: Can't get car model please check cars.json]`

```
$ cat cars.json 
[
    {
        "battery_power": 46,
        "brand": "Peugeot",
        "fuel_capacity": 0,
        "label": "",
        "max_elec_consumption": 70,
        "max_fuel_consumption": 0,
        "vehicle_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "vin": "xxxxxxxxxxxxxxxx"
    }
```

Same result with the same error while I use latest app_decoder.py :

```
$ python3 app_decoder.py /home/psa_remote/com.psa.mym.mypeugeot_1.28.1.apk 
APK loading...
Requested API level 29 is larger than maximum we have, returning API level 28 instead.
RES_TABLE_LIBRARY_TYPE chunk is not supported
RES_TABLE_LIBRARY_TYPE chunk is not supported
APK loaded !
MyPeugeot email: xxxxx@xxxxxx.xxx
MyPeugeot password: xxxxxxxxxxxxx
What is your country code ? (ex: FR, GB, DE, ES...)
FR
Can't get car model please check cars.json

Your vehicles: ["{'vin': 'xxxxxxxxxxxxxxxxxxxxxxxx, 'vehicle_id': 'xxxxxxxxxxxxxxxxxxxx', 'label': None, 'brand': 'Peugeot', 'battery_power': 46, 'fuel_capacity': 0, 'max_elec_consumption': 70, 'max_fuel_consumption': 0}"]
Success !!!
```

**Comment by spiff123** [comment]
I can confirm a e-208 gives a empty label as well with the current version. 

I get a 

"label": null, 

result.
