### ISSUE TITLE
Start/stop charging not working for the moment

### ISSUE THREAD

**Issue by JaySea77** [flobz/psa_car_controller#654]
In my Citroën e-c4 I get updates of the state of the car, but when I send the command to start or stop charging it gives a 300 error. With the MyCitroën app it still works. I needed to enter a pin on the MyCitroën app though.
I have restarted psa car controller, but that didn't solve the issue.

**Comment by JaySea77** [comment]
Today with preconditioning the same. In the MyCitroën app it takes 30 seconds for it to activate or deactivate. In psa controller I can't activate nor deactivate.
The status does get updated in psa controller though.

**Comment by Jordan87** [comment]
For me it was also not working and status was only updated on the end of charging but after reconfiguring app one more time it is working with continous updates and Im able to start/stop charging from addon.
