### ISSUE TITLE
Failed to record SOH: 'NoneType' object has no attribute 'health'

### ISSUE THREAD

**Issue by RlfSt** [flobz/psa_car_controller#675]
Car: Opel Corsa-e (2022)
App: PSA-Car-Controller 3.1.0
Env: Ubuntu 22.04.3 LTS (lxc-Container on Proxmox)

With the new feature of getting the SOH there a two errors:

Browser/JS-Console:

`Invalid argument `columns[7].type` passed into DataTable with ID "battery-table".
Expected one of ["any","numeric","text","datetime"].`

activity.log:
`2023-11-18 15:57:09,349 :: DEBUG :: Failed to record SOH: 'NoneType' object has no attribute 'health'
`

1. what command did you use
/usr/bin/python3 /usr/local/bin/psa-car-controller -R 5 -r -d -l 192.168.7.31 -p 5000

2. when the bug append ?
When calling the site http://192.168.7.31:5000

3. Does it persist after restarting the program? 
Yes.

5. Does it persist after recreate config by going to http://server_address:port/config? 
Yes.

**Comment by Dirtylife** [comment]
Exatly same Error here...
Side-Effect: Table with Chargings is empty

Car: Citroen e-C4
App: PSA-Car-Controller 3.1.0
Env: Raspbian Bookworm

**Comment by flobz** [comment]
should be fixed in next version
