### ISSUE TITLE
No more data / get_vehicle_info: ApiException: (400)

### ISSUE THREAD

**Issue by GernotAlthammer** [flobz/psa_car_controller#685]
**Describe the bug**
No vehicle data via Get_VehicleInfo since 24.11.23

**To Reproduce**
1. what command did you use; REST command Get_VehicleInfo
    (http://192.168.1.140:5000/get_vehicleinfo/VXKxxx?from_cache=1)
2. when the bug append ? Since 24.11.2023
3. Does it persist after restarting the program? Yes
4. Does it persist after recreate config by going to http://server_address:port/config? Yes

**Config file**
Give the anonymize content of the config file

**Environment (please complete the following information):**
 - OS: HASSIO Version 11.1 Core 2023.11.3 Supervisor 2023.11.3
 - PSA Car Controller v3.1.0 (Home Assistant)
 - Brand and model of car: Opel Mokka-e
 - Application version: my Opel App Version 1.42.1
 - Log from http://server_address:port/log and browser console log

** LOG **
2023-11-25 14:39:00,739 :: ERROR :: get_vehicle_info: ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Connection': 'close', 'Date': 'Sat, 25 Nov 2023 13:39:00 GMT', 'Expires': '0', 'Cache-Control': 'no-store, no-cache, must-revalidate, private', 'Set-Cookie': 'rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Fri, 24-Nov-2023 13:39:00 GMT, JSESSIONID=6vH2hwJBFb2VstXSUvLBhEMbZCzr2T64r6OKJyeD; path=/, PSACountry=DE; Domain=.groupe-psa.com; Path=/', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains', 'Content-Type': 'application/hal+json', 'X-Global-Transaction-ID': '324866796561f8f4f0f24e31', 'User-Agent': 'Swagger-Codegen/4.0/python'})
HTTP response body: {"uuid":"9e736e09-2e5b-4dde-91c4-ffcb96f1792b","code":40000,"message":" Invalid parameter: X-MPHSource","timestamp":"2023-11-25T13:39:00.614Z"}

2023-11-25 14:39:00,745 :: ERROR :: status of VINxxx is None
2023-11-25 14:39:00,747 :: ERROR :: Probably can't retrieve all information from API:
Traceback (most recent call last):
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/charge_control.py", line 83, in process
vehicle_status = self.psacc.vehicles_list.get_car_by_vin(self.vin).get_status()
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/model/car.py", line 53, in get_status
raise ValueError("status of {} is None".format(self.vin))
ValueError: status of VINxxx is None

**Comment by SabatoArdolino** [comment]
I've the same problem 
The control tab is empty

**Comment by Belly-Buster** [comment]
Just noticed this too. The Vauxhall app isn't working either to turn on the climate, so maybe it's a temporary thing.

Typical for the first day when it's freezing cold.

**Comment by elkoled** [comment]
Update your Home Assistant PSA Car Controller addon to v3.2.0, that fixed it for me.

**Comment by GernotAlthammer** [comment]
There is no PSACC-HA Version 3.2.0 available yet in Home-Assistant Add-On Store :(

**Comment by ulfkosack** [comment]
Same here with same environment like @GernotAlthammer . ReLogin via user config doesn't helps.

**Comment by GernotAlthammer** [comment]
![image](https://github.com/flobz/psa_car_controller/assets/119130972/9470b7a1-32cf-4564-8e22-649f8dfb51fe)

After Re-Installation of PSACC-HA V3.1.0 the config shows error now :(

**Comment by Kondors1** [comment]
> Update your Home Assistant PSA Car Controller addon to v3.2.0, that fixed it for me.

How can I update it in HA?

**Comment by Belly-Buster** [comment]
> > Update your Home Assistant PSA Car Controller addon to v3.2.0, that fixed it for me.
> 
> How can I update it in HA?

There's 2 separate github repos, this one https://github.com/flobz/psa_car_controller and the HA one https://github.com/flobz/psacc-ha/ 

3.2.0 was only released here a few hours ago. I suspect it will be updated on psacc-ha shortly; if you have auto-updates on it will update once released.

**Comment by GernotAlthammer** [comment]
Re-Login did not help. I do not get ny data displayed

**Comment by jeroenribbink** [comment]
I've updated to v3.20 in docker and stil got this issue with our Peugeot e-208 of 2021 (old hardware)

**Comment by Afromies** [comment]
Just uninstall and install HA addon. The addon itself pulls the new repository for you.

**Comment by GernotAlthammer** [comment]
just installed PSACC-HA V3.2.0 -> All data is back again.
Thnk you very much for the quick solution.

**Comment by ulfkosack** [comment]
Works on my ha too, without any modification. Thanks a lot.
