### ISSUE TITLE
PSAcar controller not updating automatically information

### ISSUE THREAD

**Issue by Destroyer061090** [flobz/psa_car_controller#691]
**Describe the bug**
PSAcar controller not updating automatically information and it is not storing new info as trip, charge, map. data are stopper since 23th November.

screenshot of today
![immagine](https://github.com/flobz/psa_car_controller/assets/126196958/c5fa8f90-4092-4c0b-b1c6-443483bf3d8a)

**To Reproduce**
I have installed PSAcarController on docker synology NAS and I followed the step we did (nothing wrong).
all information are downloaded and sensor in homeassistat where set correctly with a scan interval of 60s.
problem is the PSAcarController docker is not updating correctly. if i manually restart the docker container, it refrash the information

**Config file**
[log.txt](https://github.com/flobz/psa_car_controller/files/13473509/log.txt)

**Environment (please complete the following information):**
 - Brand and model of car: Peogeout 508SW

**Additional context**
additionally using follow code:
http://myIP:5000/charge_control?vin=myVINnumber&?always_check=true
![immagine](https://github.com/flobz/psa_car_controller/assets/126196958/0d5f0e9b-9da8-4798-85a0-d7c67781ea86)

**Comment by SabatoArdolino** [comment]
I've the same issue from 1 week ... I've try to reinstall app on phone re authent. but the issue remain

**Comment by Saesh123** [comment]
Same issue here.

**Comment by Nitro56** [comment]
Same issue here.
Peugeot e208

**Comment by Destroyer061090** [comment]
@flobz do you have any update or suggestion here?
from when i open the ticket i get alwasy the same result, "Charge control not setup check your PSACC configuration and logs". i tried to resetup everithing but always the same result... 

this is working:
- resource: "http://myIP:myPort/get_vehicleinfo/myVIN "
    scan_interval: 60
    sensor:
      - name: PSA
        unique_id: psa
        value_template: "OK"
        json_attributes:
          - energy
          - timed_odometer
          - battery
          - last_position
          - preconditionning
          - kinetic

this is not working:
- resource: "http://myIP:myPort/charge_control?vin=myVIN&?always_check=true"
    scan_interval: 60
    sensor:
      - name: "PSA Charge Control"
        unique_id: psa_charge_control
        value_template: "OK"
        json_attributes:
          - _next_stop_hour
          - percentage_threshold

**Comment by Destroyer061090** [comment]
@flobz with version 3.4.1 charge_control start to work again.
