### ISSUE TITLE
Issue with updating info

### ISSUE THREAD

**Issue by JaySea77** [flobz/psa_car_controller#697]
I see this error in the log when I ask for vehicle info.

2023-11-30 21:43:46,908 :: ERROR :: force_update:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/charge_control.py", line 70, in force_update
    self.psacc.remote_client.wakeup(self.vin)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/common/utils.py", line 23, in wrapper
    raise RateLimitException
psa_car_controller.common.utils.RateLimitException

Also I see my car head light turn on for a a second and turn off right after that. Could this be related to the wake up command which doesn't seem to send any info from the car to the psa server?

**Comment by Apollon77** [comment]
This error means that too many requests are sent ina too short time ...

**Comment by JaySea77** [comment]
It usually means that, but I ask info always with cache=1 and the wake up command doesn't get any response so I guess it requests a wake up more often.

**Comment by JaySea77** [comment]
Is it normal that when you get the ratelimit, that you aren't able to get any response for 2 days or more?
How long should such a ban take?

**Comment by JaySea77** [comment]
I get updates now, but none of the commands do anything anymore.
Turning preconditioning on gives a 200 status so it looks like it works, but nothing happens.
The MyCitroën app still does everything.
What can I do to make psa car controller work again?

**Comment by JaySea77** [comment]
It just started working again so no more help needed
