### ISSUE TITLE
Starting preconditioning from psa_car_controller works bug clear existing preconditioning planning previously set from MyPeugeot app

### ISSUE THREAD

**Issue by sy6sy2** [flobz/psa_car_controller#703]
**Describe the bug**
It seems that playing with the preconditioning route of the psa_car_controller API works well but clear any preconditioning planning set from the MyPeugeot app.

**To Reproduce**
1. On the MyPeugeot iOS app add a preconditioning planning (let's say at 7H30 from Monday to Saturday).
2. Everything works well and the car is preconditioned every morning.
3. Now, let's say it's 12H00 and I want to start the preconditioning before using my car, so I use `http://localhost:5000/preconditioning/YOURVIN/1` to start a manual preconditioning.
4. Everything works well, my car is preconditioned, BUT, if I open the MyPeugeot iOS app I notice that my preconditioning planning set at step 1 is not here anymore.

I am able to reproduce this issue with a fresh instance of psa_car_controller.

**Config file**
```
[General]
currency = €
# define format for data export, can be csv or xlsx
export_format = csv
# minimum trip length in km so it's added to stats and map in website
minimum trip length = 10
# for future use
length unit = km
export format = csv
[Electricity config]
# price by kw/h
day price = 0.15
night price
# ex: 22h30
night hour start
# ex: 6h00
night hour end
dc charge price
high speed dc charge price
# minimum power in kW that should be delivered during a charge so it can be considered as a high speed charger
high speed dc charge threshold
charger efficiency = 0.8942
```

**Environment (please complete the following information):**
 - OS: Debian (using the latest docker image)
 - Brand and model of car : Peugeot e-208 Style
 - Application version: 3.2.0
 - Log from http://server_address:port/log and browser console log: See attached file

[psa_log.txt](https://github.com/flobz/psa_car_controller/files/13578281/psa_log.txt)

**Comment by gerar19** [comment]
same here. Thanks

**Comment by sy6sy2** [comment]
Just tested the latest version and the issue seems to be resolved now. Don't if the issue was on PSA API side or on this utility side...
Thank you for this project anyway 😉
I will closing this issue for now.

**Comment by JaySea77** [comment]
Just tried it and I can confirm the schemes are still there.
