### ISSUE TITLE
Question: how to prevent rate limit errors

### ISSUE THREAD

**Issue by JaySea77** [flobz/psa_car_controller#705]
I do a periodically call for update info with cache=1. Lately this will get me the rate limit error in less than a day. Then I have to wait for 4 days to get access again. And after getting access, I get a rate limit error again within a day.

How can I prevent a rate limit error but also be able to have not too much out of date info?

**Comment by SabatoArdolino** [comment]
I've modify refresh every 120s

**Comment by JaySea77** [comment]
Not completed though but whatever
