### ISSUE TITLE
Can't log in any more

### ISSUE THREAD

**Issue by ncot-tech** [flobz/psa_car_controller#706]
The system was working fine for months, but recently the SoC for my car stopped updating and just reported the same value. Figuring their servers had probably gone strange again I tried generating a new OTP code but never received it. I then decided it probably just needed logging back in again. I entered my details into "user config" but now all that happens is I get a red box underneath the submit button...

If I look in the logs I see the following message repeated every time it tries to refresh the car's data.

I am using the correct email address and password though, it works in the phone app.

If only Type 2 AC charge connectors could also communicate with the car's BMS to read battery state like the CCS ones do.

`HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'X-Client-IP': '10.128.158.240', 'X-Global-Transaction-ID': 'xxxxxxxxxxxxxxxxx, 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'WWW-Authenticate': "Bearer error='invalid_token'", 'Date': 'Sat, 09 Dec 2023 15:15:48 GMT', 'Connection': 'close', 'Set-Cookie': 'PSACountry=GB; Domain=.groupe-psa.com; Path=/', 'Vary': 'Accept-Encoding'})
HTTP response body: {"httpCode":"401","httpMessage":"Unauthorized","moreInformation":"Cannot pass the security checks that are required by the target API or operation, Enable debug headers for more details."}`

![image](https://github.com/flobz/psa_car_controller/assets/7870113/576c6183-104f-455b-8b14-51faa759f5ab)

**Comment by robotfishe** [comment]
I also started having errors a few days ago, and eventually just deleted the addon from Home Assistant and started from scratch because nothing else worked. I'm now unable to sign in and getting the following errors:

```
2023-12-13 08:40:40,248 :: INFO :: Namespace mapping (55, 449) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2023-12-13 08:40:40,268 :: INFO :: APK file was successfully validated!
2023-12-13 08:40:40,269 :: WARNING :: Requested API level 33 is larger than maximum we have, returning API level 28 instead.
2023-12-13 08:40:40,894 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2023-12-13 08:40:40,895 :: WARNING ::
```

Thinking the target api version error might be pointing to the same issue?

**Comment by kurim** [comment]
API level error is quite normal, the Warning show up earlier - https://github.com/flobz/psa_car_controller/issues/181#issue-938260477
```log
Requested API level 29 is larger than maximum we have, returning API level 28 instead.
```

Maybe the used APP Version 1.33.0 (APK in GIT) is to old and need to replace with 1.43.0 (not sure, but we have similar issue https://github.com/flobz/psa_car_controller/issues/416#issuecomment-1296706168)

**Comment by flobz** [comment]
@robotfishe do you have an error in the log ?  These warnings should be ignored.

**Comment by robotfishe** [comment]
> @robotfishe do you have an error in the log ? These warnings should be ignored.

Pretty sure my issue is the same as #674 , logs look the same.

**Comment by flobz** [comment]
duplicate with #674
