### ISSUE TITLE
Mokka-e Features

### ISSUE THREAD

**Issue by andreadegiovine** [flobz/psa_car_controller#708]
This features seem not work on my Mokka-e:
-doors lock/unlock
-clima start/stop
-horn
-lights flash

Why?

**Comment by tomechio** [comment]
-doors lock/unlock
-horn
-lights flash

These most probably won't work if your vehicle is older than MY2023. 
These has been already some discussion about this topic in: 
https://github.com/flobz/psa_car_controller/issues/688

**Comment by andreadegiovine** [comment]
My Mokka-e was purchased on 26/05/2023

This is the list of enabled services.

Im using HA on a minipc and from my log i can see only:

Disconnected with result code 5

![6263FB23-C321-45D5-BAA5-3186AF9C04F4](https://github.com/flobz/psa_car_controller/assets/68383596/3d77f92c-1a05-45f1-a42c-2d27d3b00a56)

**Comment by tomechio** [comment]
Borrowed from another topic:
For anyone else looking here in the meantime: Please make sure you have either the old Remote Control service (not e-remote control) or the new Connect Plus service activated.

In your screen capture you have e-remote control.
