### ISSUE TITLE
Little question after migrate my docker container

### ISSUE THREAD

**Issue by nanoupi42** [flobz/psa_car_controller#718]
Hi,
I have recreated the container on a new synology
I have the config folder but the data has completely gone on the web interface (trips, charges sessions etc...), I don't know where the database is stored ?
I only have info.db but the size is really small, I don't think the data are here...
I have 6 month data and I don't know to recover it..
Can you tell me where is stored ?
I can start the old container on the old Synology if I have to extract the data..

Thanks !

**Comment by nanoupi42** [comment]
![Uploading Screenshot 2024-01-01 at 17.28.54.png…]()

**Comment by nosuchuser** [comment]
All the config and past data is within the files on that folder. If you install a sqlite client (open a bash shell on the container and apt install sqlite3) and open that .db you’ll see the data there.

**Comment by nanoupi42** [comment]
Thanks for your help !
Very weird I have install sqlite3, I can confirm now the data are here, and now the datas displayed correctly on the web interface, all the datas are here !!
Like the sqlite3 have deblock something ? 
Thanks again !

**Comment by nosuchuser** [comment]
It happens to me some times as well. Every now and then the web interface shows no data - it will start rendering the data correctly without any intervention.
