### ISSUE TITLE
Can't get past initial configuration on HAOS > "returnCode":"NEED_AUTHORIZATION","token":

### ISSUE THREAD

**Issue by borgqueenx** [flobz/psa_car_controller#720]
The error shows ""returnCode":"NEED_AUTHORIZATION","token":"
when i enter my correct login mail address and password, that works in the my citroen app.
How do i fix that, so i can get the car data into home assistant?
Thanks!

**Comment by flobz** [comment]
https://github.com/flobz/psa_car_controller/blob/master/FAQ.md#9-need_authorization-error
