### ISSUE TITLE
Schedules are deleted after triggering precondition

### ISSUE THREAD

**Issue by uroshj** [flobz/psa_car_controller#728]
When I trigger precondition, then all the schedules that were set are deleted.

**To Reproduce**
1. what command did you use
From the app, the preconditioning button (the same if I trigger it per web request (open in browser)
3. when the bug append ?
I installed everything yesterday
5. Does it persist after restarting the program? 
Yes
7. Does it persist after recreate config by going to http://server_address:port/config? 

**Config file**
{"General": {"currency": "\u20ac", "length_unit": "km", "minimum_trip_length": 10.0, "export_format": "csv"}, "Electricity_config": {"day_price": 0.15, "night_price": null, "night_hour_start": null, "night_hour_end": null, "dc_charge_price": null, "high_speed_dc_charge_price": null, "high_speed_dc_charge_threshold": null, "charger_efficiency": 0.8942}}

**Environment (please complete the following information):**
 - HomeAssistant
 - Citroen ec4
 - 3.3.1

**Additional context**
Nothing additional. Maybe just a question, where should I put this into, to get the records (I do not see the car location in the Map, and the same on the official app): 
III. Use the dashboard
You can add the -r argument to record the position of the vehicle and retrieve this information in a dashboard.
python3 psa-car-controller -f config.json -c charge_config.json -r

**Comment by flobz** [comment]
Closed because this is a duplicate issue
