### ISSUE TITLE
APK Version

### ISSUE THREAD

**Issue by dakesson** [flobz/psa_car_controller#74]
**Describe the bug**
Fails to run app_decoder.py. Not stated what version of the APK to use. With latest I get:
"client_id = resources.get_string(package_name, "PSA_API_CLIENT_ID_PROD")[1]" - fails

With older version 1.23.3 I get 
"There is no item named 'assets/MWPMYMA1.pfx' in the archive"

**To Reproduce**
Download 1.28.2 apk and run app_decoder.py.

Great work otherwise! :D

**Comment by flobz** [comment]
Try 1.27 please

**Comment by dakesson** [comment]
Just got it working with 1.25.2 it seems like. Thanks

**Comment by dakesson** [comment]
Old cert in 1.25.2 but 1.27 is correct!
