### ISSUE TITLE
400 - server_error : Internal Server Error at user config

### ISSUE THREAD

**Issue by francogodi** [flobz/psa_car_controller#767]
Hi, yesterday I stopped receiving data from trips or charge status.
after a reboot I was asked to login again but the login process does not work with error:
400 - server_error : Internal Server Error at user config

![image](https://github.com/flobz/psa_car_controller/assets/97960424/45d600d9-0288-414a-acbf-6638d93437c1)

**Comment by mdkeil** [comment]
duplicate; look at #733

**Comment by martynhr** [comment]
> Hi, yesterday I stopped receiving data from trips or charge status. after a reboot I was asked to login again but the login process does not work with error: 400 - server_error : Internal Server Error at user config
> 
> ![image](https://private-user-images.githubusercontent.com/97960424/305876673-45d600d9-0288-414a-acbf-6638d93437c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMzc3NTcsIm5iZiI6MTcwODMzNzQ1NywicGF0aCI6Ii85Nzk2MDQyNC8zMDU4NzY2NzMtNDVkNjAwZDktMDI4OC00MTRhLWFjYmYtNjYzOGQ5MzQzN2MxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDEwMTA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1NmU0MDFjZmY5MGJmNjU1ZTg1NTg1MWU1YWQ3Yzk4YWY4MTI2OTkyMjY3ZjliZDQzMWM1OGE5OThkYzlkZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R4W97eFqRgEn-PM1v26CxZnVMl4_1QL2Yjz91lprkYQ)

Same here.

**Comment by redzoro01** [comment]
same problem for me

**Comment by scream05** [comment]
same also on my side.

**Comment by martynhr** [comment]
> > Hi, yesterday I stopped receiving data from trips or charge status. after a reboot I was asked to login again but the login process does not work with error: 400 - server_error : Internal Server Error at user config
> > ![image](https://private-user-images.githubusercontent.com/97960424/305876673-45d600d9-0288-414a-acbf-6638d93437c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMzc3NTcsIm5iZiI6MTcwODMzNzQ1NywicGF0aCI6Ii85Nzk2MDQyNC8zMDU4NzY2NzMtNDVkNjAwZDktMDI4OC00MTRhLWFjYmYtNjYzOGQ5MzQzN2MxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDEwMTA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1NmU0MDFjZmY5MGJmNjU1ZTg1NTg1MWU1YWQ3Yzk4YWY4MTI2OTkyMjY3ZjliZDQzMWM1OGE5OThkYzlkZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R4W97eFqRgEn-PM1v26CxZnVMl4_1QL2Yjz91lprkYQ)
> 
> Same here.

Working again now

**Comment by francogodi** [comment]
> > > Hi, yesterday I stopped receiving data from trips or charge status. after a reboot I was asked to login again but the login process does not work with error: 400 - server_error : Internal Server Error at user config
> > > ![image](https://private-user-images.githubusercontent.com/97960424/305876673-45d600d9-0288-414a-acbf-6638d93437c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMzc3NTcsIm5iZiI6MTcwODMzNzQ1NywicGF0aCI6Ii85Nzk2MDQyNC8zMDU4NzY2NzMtNDVkNjAwZDktMDI4OC00MTRhLWFjYmYtNjYzOGQ5MzQzN2MxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDEwMTA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1NmU0MDFjZmY5MGJmNjU1ZTg1NTg1MWU1YWQ3Yzk4YWY4MTI2OTkyMjY3ZjliZDQzMWM1OGE5OThkYzlkZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R4W97eFqRgEn-PM1v26CxZnVMl4_1QL2Yjz91lprkYQ)
> > 
> > 
> > Same here.
> 
> Working again now

not working on my side, maybe because I need to authenticate and auth does not work

**Comment by martynhr** [comment]
I didn't do any workaround to get it working. I logged back in on the app (android) and then restarted the home assistant add-on. Initially it didn't work but a few hours later it's running again.

**Comment by wjansenw** [comment]
I tried to login to the app, and it mentioned my password was incorrect. After resetting the pwd, I got some questions around my profile, which I had to answer before I could proceed with the login. 

So hoping that I experience the same as @martynhr, and that in a couple of hours, I will manage to re-login.

**Comment by wjansenw** [comment]
The work-around in https://github.com/flobz/psa_car_controller/issues/733 worked for me.

**Comment by flavrai** [comment]
Also managed to fix it using https://github.com/flobz/psa_car_controller/issues/733

The only problem in my case - and I put the details here in case someone has a similar setup -  is that I run car-controller & homeassistant as containers in a kubecluster, so I rely on the available docker images.

Here bellow the steps in case needed:
- spin up a python container -> docker run -it -v $(pwd):/car -p 5000:5000 python bash
- use the steps from https://github.com/flobz/psa_car_controller/issues/733
- once managed to successfully login, just grab the files (config.json & otp.bin) from python container and upload them into the persistent storage of your car-controller (hosted in kubernetes/ docker). Then a restart of car-controller pod/container should make it work.

**Comment by cmjcmj123** [comment]
I have same problem in HA. I also had problems to log into the phone app MyOpel. After reporting it to Opel support I got info that they had made new rules for guilty passwords. My password didn't fulfill. So I had to click "forgot pw" and generate a new that fulfilled the new requirements. But When I logged into PSA Controller in HA with the new pw I got the 400 error
