### ISSUE TITLE
logging connection with mitmproxy

### ISSUE THREAD

**Issue by xammmue** [flobz/psa_car_controller#77]
I tried to log the requests sent by the MyOpel App with mitrmproxy running on my Ubuntu pc.

I added the proxy information in my wifi connection details and started mitmproxy using the command in the Readme.

While I can see many requests to unrelated stuff like www.facebook.com or connectivitycheck.gstatic.com I can't see any requests sent to the PSA API.
I opened the Events view with shift+e and found my entries like:
info: phoneIp:port clientconnect
info: phoneIp:port clientdisconnect

New ones come in every time I do something in the App like trigger a remote command but the app always gives me an error message (command could bno be executed try again).

Any idea what I did wrong?

**Comment by flobz** [comment]
I suppose it's a certificate problem.
For being able to see trafic from myopel you need a rooted phone,  you can use an android emulator then follow this:
https://docs.mitmproxy.org/stable/howto-install-system-trusted-ca-android/

**Comment by xammmue** [comment]
Thanks,
I think I still have a rooted phone somewhere... I will try that
