### ISSUE TITLE
v3.4.1 Issue with access_token

### ISSUE THREAD

**Issue by malbertone** [flobz/psa_car_controller#783]
Hi,
when trying to use v3.4.1 it looks the situation has improved.

Still after logging in and passing the code, while i can get a few data out of the PSA servers, i see in the container's console:
![image](https://github.com/flobz/psa_car_controller/assets/36228023/7afdd54f-9ca7-4433-b4c4-7f16b3bb3f19)

and cannot update the data once i cliek on refresh.

Another issue is in the URL reported by the console, this time it cannot be copy and pasted since it's encoded:
![image](https://github.com/flobz/psa_car_controller/assets/36228023/b210a582-96d9-46d9-95e3-cb4369268eaa)
but you can still get it from the developer's tools.
Also some of the information reported in the logs does not seem to be visible anywhere in the dashboard:
![image](https://github.com/flobz/psa_car_controller/assets/36228023/604aa3de-20e7-435f-b754-edb999453f9e)

thanks
Mike

**Comment by malbertone** [comment]
Checked again, and even if the Config OTP reports Success:
![image](https://github.com/flobz/psa_car_controller/assets/36228023/6e68f6ca-bcf5-4e38-9f4c-dd8701170156)
Still the logs in the container console show:
![image](https://github.com/flobz/psa_car_controller/assets/36228023/5fedae1c-6a23-4dff-92ed-50b537fc68cc)

**Comment by bennymamo** [comment]
To easily get the URL fixed, paste it here

https://www.url-encode-decode.com/

**Comment by grahamrjuk** [comment]
I got the URL working, and can see some data in the PSA car controller tab in HA, but I do get the "Can't configure MQTT client" error and related "KeyError: access_token"

OTP config did say it had finished, and I see some data - is this still an error with the URL, or something else?

**Comment by JeedHome44** [comment]
Hello !

I updated PSA Car 3.4.1 to Home Assistant !
I have this : 

Where is URL to login and click to ok ?

**Comment by bennymamo** [comment]
> I got the URL working, and can see some data in the PSA car controller tab in HA, but I do get the "Can't configure MQTT client" error and related "KeyError: access_token"
> 
> OTP config did say it had finished, and I see some data - is this still an error with the URL, or something else?

I had that issue once when I input by mistake one number incorrectly from SMS. Try doing OTP again

**Comment by malbertone** [comment]
Hi, 
tried more than once, and it looks the OTP suceeds, but still HA logs are reporting:
2024-02-27 00:20:07,335 :: ERROR :: Error during activation: {'newversion': None, 'newversionurl': None, 'err': 'NOK_BLOCKED'}
2024-02-27 00:20:07,879 :: ERROR :: remote_refresh_token isn't defined
2024-02-27 00:20:08,524 :: ERROR :: Error during activation: {'err': 'NOK:FORBIDDEN'}
2024-02-27 00:20:09,031 :: ERROR :: Can't refresh remote token 'access_token'
Traceback (most recent call last):
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/RemoteClient.py", line 174, in _refresh_remote_token
self._get_remote_access_token(otp_code)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/RemoteClient.py", line 206, in _get_remote_access_token
self.remoteCredentials.access_token = data["access_token"]
KeyError: 'access_token'
2024-02-27 00:20:35,243 :: INFO :: save config change
2024-02-27 00:21:09,092 :: ERROR :: Can't configure MQTT Client
2024-02-27 00:21:09,569 :: INFO :: new position recorded for xxxxxxxxxxxxxxxxxx
and cannot get up to data from the server

thanks
Mike

**Comment by show2go** [comment]
> Hi, tried more than once, and it looks the OTP suceeds, but still HA logs are reporting: 2024-02-27 00:20:07,335 :: ERROR :: Error during activation: {'newversion': None, 'newversionurl': None, 'err': 'NOK_BLOCKED'} 2024-02-27 00:20:07,879 :: ERROR :: remote_refresh_token isn't defined 2024-02-27 00:20:08,524 :: ERROR :: Error during activation: {'err': 'NOK:FORBIDDEN'} 2024-02-27 00:20:09,031 :: ERROR :: Can't refresh remote token 'access_token' Traceback (most recent call last): File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/RemoteClient.py", line 174, in _refresh_remote_token self._get_remote_access_token(otp_code) File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/RemoteClient.py", line 206, in _get_remote_access_token self.remoteCredentials.access_token = data["access_token"] KeyError: 'access_token' 2024-02-27 00:20:35,243 :: INFO :: save config change 2024-02-27 00:21:09,092 :: ERROR :: Can't configure MQTT Client 2024-02-27 00:21:09,569 :: INFO :: new position recorded for xxxxxxxxxxxxxxxxxx and cannot get up to data from the server
> 
> thanks Mike

See the FAQ
https://github.com/flobz/psa_car_controller/blob/master/FAQ.md

point 2

cheers

**Comment by MattCheetham** [comment]
> i follow all steps, but I think the step 6 is confusing. I know how to catch the uniqueidentifier, but I need to put in what console? In PSA configuration page or Stellantis webpage where i did click OK I did try the bought ways, and nothing work

Try the instructions I wrote out here, hopefully it helps. https://github.com/flobz/psa_car_controller/discussions/779#discussioncomment-8601459

**Comment by HenningS81** [comment]
> Hi, tried more than once, and it looks the OTP suceeds, but still HA logs are reporting: 2024-02-27 00:20:07,335 :: ERROR :: Error during activation: {'newversion': None, 'newversionurl': None, 'err': 'NOK_BLOCKED'} 2024-02-27 00:20:07,879 :: ERROR :: remote_refresh_token isn't defined 2024-02-27 00:20:08,524 :: ERROR :: Error during activation: {'err': 'NOK:FORBIDDEN'} 2024-02-27 00:20:09,031 :: ERROR :: Can't refresh remote token 'access_token' Traceback (most recent call last): File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/RemoteClient.py", line 174, in _refresh_remote_token self._get_remote_access_token(otp_code) File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/RemoteClient.py", line 206, in _get_remote_access_token self.remoteCredentials.access_token = data["access_token"] KeyError: 'access_token' 2024-02-27 00:20:35,243 :: INFO :: save config change 2024-02-27 00:21:09,092 :: ERROR :: Can't configure MQTT Client 2024-02-27 00:21:09,569 :: INFO :: new position recorded for xxxxxxxxxxxxxxxxxx and cannot get up to data from the server
> 
> thanks Mike

I have the same behaviour with 3.4.1. I use a docker on a synology NAS. I reinstalled the docker several times and did the whole authorization even more often. No luck so far.

**Comment by grahamrjuk** [comment]
Got it working - I did have to remove the MyVauxhall app, re-connect with the vehicle through the app, then go through the full configuration in HA, including using the correct PIN.
Thanks for all the work to get the new registration system working.
