### ISSUE TITLE
Constant RateLimitException

### ISSUE THREAD

**Issue by bennymamo** [flobz/psa_car_controller#784]
Hi, maybe someone could help me out here.

After a full night slow charging and getting updates on SOC periodically, I started getting RateLimitException. Now I'm not sure if this is an issue from psa_car_controller or Stellantis. I'm suspecting from stellantis since even my Android app is not updating anymore, and my acocunt got some kind of temporary (or permanent) ban.

I'm trying to understand how I can reduce the rate limit considering I'm slow charging. Any pointers?

psa_car_controller  | 2024-02-26 20:43:04,486 :: INFO :: charging status of VR3xxxxxxxxxxx is InProgress, battery level: 76
psa_car_controller  | 2024-02-26 20:43:04,486 :: ERROR :: force_update:
psa_car_controller  | Traceback (most recent call last):
psa_car_controller  |   File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/charge_control.py", line 70, in force_update
psa_car_controller  |     self.psacc.remote_client.wakeup(self.vin)
psa_car_controller  |   File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/common/utils.py", line 23, in wrapper
psa_car_controller  |     raise RateLimitException
psa_car_controller  | psa_car_controller.common.utils.RateLimitException

**Comment by bennymamo** [comment]
Update for whoever might get this - disconnected 12V battery for a couple minutes and everything is now working again. Seems like mobile modem or whatever is used to send commands to car was stuck or crashed.

**Comment by bueno79** [comment]
@bennymamo how did you do that ? You disconnect the main Battery of the car ?

**Comment by bennymamo** [comment]
> @bennymamo how did you do that ? You disconnect the main Battery of the car ?

I disconnected 12v battery under bonnet. It has quick release.

**Comment by bueno79** [comment]
ok. Thx for your help. I have a DS7. A battery under the hood and one more in the back. I've disconnect the one in the back for few minutes. Replug it...but still the same. It's an hybrid car.

**Comment by bennymamo** [comment]
Disconnect both of them if both are v12vvvv'vv''''v'1vv

**Comment by bennymamo** [comment]
Vg6
