### ISSUE TITLE
Where is URL login 3.4.1 

### ISSUE THREAD

**Issue by JeedHome44** [flobz/psa_car_controller#785]
Hello !

I updated PSA Car 3.4.1 to Home Assistant !
I have this : 

![image](https://github.com/flobz/psa_car_controller/assets/41892950/1fdf6a28-4551-4e77-a51a-6ff9d193aae6)

![image](https://github.com/flobz/psa_car_controller/assets/41892950/c68c3edb-69ab-44ac-bc26-f453286217fa)

Where is URL to login and click to ok ?

**Comment by stealthhack** [comment]
Copy the url from the login page(192.168.x.x:8123. . . something like this **https:// . . . . . . . .** )
Then past it in this site: https://www.url-encode-decode.com/
Then click Decode URL
Then copy the decoded URL and paste it in plain new tab, the URL will guide you to the login page of PSA server, login with your creditials for the MyPeugeot app, click **"remember me"** and login. 
Then BEFORE pressing the OK button, press F12 key, in the top center tab see Network, and press it.
Then press the OK button on the Login page, from PSA server, you will see  the login code appearing in the right(in the F12 Console part)
Copy it as described in the picture posted by you, then paste it, and press Submit. Then continue with the SMS and PIN portion, then you're DONE.

**Comment by Arnoudd** [comment]
@stealthhack Thanks! Was looking for that url too and managed to login again using your tips.

**Comment by zutislo** [comment]
Thank you flobz for adding this to UI :) Now I know where to post it :D

**Comment by antoniochacon** [comment]
Using that code I always get same massage:
400 - invalid_grant : The provided access grant is invalid, expired, or revoked.
