### ISSUE TITLE
Meanwhile data is missing

### ISSUE THREAD

**Issue by bs0001** [flobz/psa_car_controller#787]
I think it's not a Bug, mir a question.
After upgrading from 3.3.0 to 3.4.1 I can now retrieve data for my e-208 again. Is it possbile to retrieve the missing data of the last weeks or retrieve the whole history of trips and charging?
![Screenshot_20240228_163132_Chrome](https://github.com/flobz/psa_car_controller/assets/46260437/9058663b-28c0-487d-8be5-4231666f96b7)

**Comment by frans0180** [comment]
No data,

Fortunately, I can log in again after the new update :-)   (it has become very cumbersome!) 
Now I see that 5 new identities have been added, but I cannot read the 10 most important ones, what is going wrong?

![psa2](https://github.com/flobz/psa_car_controller/assets/150475372/4b482c15-afa8-41b1-a5b6-69ffd7d2a77c)

**Comment by monstergubl** [comment]
have the sam problem sensor.psa have no data
![Screenshot 2024-02-28 160623](https://github.com/flobz/psa_car_controller/assets/133626445/598b271c-19f9-47ca-bf8a-7b87dfd8fe0a)
![Screenshot 2024-02-28 160908](https://github.com/flobz/psa_car_controller/assets/133626445/824b15b4-27bf-4a74-a37b-efb9333a9748)

**Comment by flobz** [comment]
no it's note there is no history on PSA/Stellantis server.
