### ISSUE TITLE
Battery Charge not Recorded 

### ISSUE THREAD

**Issue by SabatoArdolino** [flobz/psa_car_controller#791]
After Upgrade to last release The charge of battery is not recorded. In the Control Tab I can see the correct battery level but If I try to recharge the battery the data is not recorded. 
I've try also to deinstall e reinstall entire add-on but the error is the same. 
Any idea ?

![image](https://github.com/flobz/psa_car_controller/assets/137244513/b1ae4087-e3e4-4b59-a847-0aa875703059)

**Comment by SabatoArdolino** [comment]
I've an update. When the car is charging I see the entry.. When I cut off the charge the entry is removed

**Comment by mj1985** [comment]
Same here with my Astra Hybrid (error code 300). Charging was recorded after some time, after charging was finished the status (plugged in) remains (in the App, too).

**Comment by maximumstruggle** [comment]
Hello. I have the exact same issue but with the 3.3.1 release. Seems like an issue with PSA API.

**Comment by mj1985** [comment]
According to Eevee,  it's a Stellantis issue, which has been resolved. Data is not lost:
https://intercom.help/eevee-mobility/en/articles/9018659-incident-stellantis-group

**Comment by maximumstruggle** [comment]
I had the error durint the night between Friday and Saturday. I performed a quick test yeserday evening and this morning and according to the logs and the behaviour of psa_car_controller, it looks like it is fixed.

Thank you for the information @mj1985

**Comment by SabatoArdolino** [comment]
Yes it is also for me .. now I can see always fine

**Comment by mj1985** [comment]
Fixed for me, too. This evening the charging status and traction battery changed
