### ISSUE TITLE
Wake Up command does not work anymore

### ISSUE THREAD

**Issue by Drastef31** [flobz/psa_car_controller#797]
I have an eC4, model 2021. I grab car data in my Home Assistant for stats and charge control. From the beginning, I found that when the car is off, it does not refresh the data. Until now, I used the wake up command of the API to "wake up" the car when it provides data older than 30 minutes. It was not perfect bu it worked. From few weeks, it seems that the wake up API command does not work anymore. Data continue to be dated from the last power off of the car with no chance to update (even in the APP). 
Does someone find the same problem ? Is it Stellantis server problem ? Or am I alone ?
Thank you

**Comment by vineethktpla** [comment]
I have the same issue

**Comment by Drastef31** [comment]
Hello
After a complete crash of my Raspberry PI that embed the Psa Car Controler server, I have reinstalled the system from scratch, and it is now possible to wake up the car when needed.
I don't know why 🤷‍♂️

**Comment by gernot-h** [comment]
@Drastef31, so this means you get fresh data now after waking up, right?

**Comment by Drastef31** [comment]
Correct. The wake up command works and I can get fresh data after sending a wake up command.

**Comment by gernot-h** [comment]
Ok, I also did a fresh install and now it works again for me, too. Probably somehow connected to the Stellantis backend issue described in #791?

So I guess you could close this issue, right?

**Comment by Drastef31** [comment]
Yes, I think so too.
Thank you

**Comment by Drastef31** [comment]
Can be closed
