### ISSUE TITLE
Error: Can't upgrade from 3.2.0 to 3.4.1

### ISSUE THREAD

**Issue by ricardolobo81** [flobz/psa_car_controller#798]
When I try to upgrade from 3.2.0 to 3.4.1, I get the error below.

Can't install flobz/psa_car_controller:v3.4.1: 404 Client Error for http+docker://localhost/v1.43/images/flobz/psa_car_controller:v3.4.1/json: Not Found ("No such image: flobz/psa_car_controller:v3.4.1")

 - OS: Home Assistant.
 - Brand and model of car: Peugeot e208.
 - Application version: 3.2.0

![Screenshot_2024-03-02-09-49-44-87_c3a231c25ed346e59462e84656a70e50.jpg](https://github.com/flobz/psa_car_controller/assets/11604255/a872f393-ad9f-4e97-a722-2b91aacf4cce)

![Screenshot_2024-03-02-10-08-00-83_92460851df6f172a4592fca41cc2d2e6.jpg](https://github.com/flobz/psa_car_controller/assets/11604255/46ece454-0940-429d-abfe-3edcb599b335)

@flobz can you help?

Thank you for excelent integration, keep the good work 👏👏👏

**Comment by ricardolobo81** [comment]
Same error when try to install 3.4.2.

24-03-09 19:41:33 ERROR (MainThread) [supervisor.docker.interface] Can't install flobz/psa_car_controller:v3.4.2: 404 Client Error for http+docker://localhost/v1.43/images/flobz/psa_car_controller:v3.4.2/json: Not Found ("No such image: flobz/psa_car_controller:v3.4.2")

Anyone can help me to solve this issue?

Thank you.

**Comment by ricardolobo81** [comment]
Problem solved.
I runed the docker pull command directly at the SSH command line. After that, the add-on update normally.

**Comment by Tapiosinn** [comment]
> Problem solved. I runed the docker pull command directly at the SSH command line. After that, the add-on update normally.

Hi
Can you explain how you did this? I'm having the same problem, thanks.
