### ISSUE TITLE
Besoin d'aide

### ISSUE THREAD

**Issue by mounik34** [flobz/psa_car_controller#8]
Bonjour,
j'ai bien testé ton script et fonctionne bien ! 
Mais par exemple, je ne sais pas du tout comment récupérer le kilométrage ? Il faut que je créé dans server.py une nouvelle route un peu comme 
`@app.route('/get_vehicleinfo/<string:vin>')
def get_vehicle_Info(vin):
    response = app.response_class(
        response=json.dumps(myp.get_vehicle_info(vin).to_dict(), default=str),
        status=200,
        mimetype='application/json'
    )
    return response
`
et remplacer myp.get_vehicle_info(vin).to_dict()
mais avec quelle commande, c'est là ou je ne suis pas bon du tout ...

merci de ton aide

**Comment by flobz** [comment]
You need to find the endpoint that give you this information in:
https://github.com/flobz/psa_car_controller/blob/master/api_spec.md

**Comment by mounik34** [comment]
> You need to find the endpoint that give you this information in:
> https://github.com/flobz/psa_car_controller/blob/master/api_spec.md

Hello
Ca serait cette fonction 
get_vehicle_status(id, extension=extension)
avec extension=odometer

J'ai rajouté ca dans le server.py
@app.route('/get_vehiclestatus/<string:vin>')
def get_vehiclestatus(vin):
    return jsonify(myp.get_vehicle_status(vin, extension=odometer))

mais ca  me fait une erreur 500 ;((

**Comment by flobz** [comment]
try myp.api().get_vehicle_status(vin, extension=odometer)

**Comment by flobz** [comment]
ok I test it. The open api spec given by psa had an error (again).
You can now retrieve odometer information at this endpoint:
http://127.0.0.1:5000/get_vehicleinfo/your_vin

**Comment by mounik34** [comment]
Yes it works ;) Thank you
