### ISSUE TITLE
Possibility to get the result not only from LOCALHOST?

### ISSUE THREAD

**Issue by calliou1234** [flobz/psa_car_controller#80]
Hello,
is it possible that the result can not only work on the localhost 127.0.0.1?

I have the PSA car Controller on a Raspberry PI (192.168.178.67) and I need the Data in an ioBroker System on my NAS System (192.168.178.35), so they have different IP-Adresses.

Thanks for any Response.

Thomas

**Comment by flobz** [comment]
Of course it's possible, check-out possible arguments with --help.

**Comment by calliou1234** [comment]
Hello,

thank you for your message.

In the meantime I have changed the IP address from localhost to the address of the PI 192.168.178.67.

Regardless of which computer I call the adress

http://192.168.178.67:5000/get_vehicleinfo/XXXXXX

I get the error "Website not accessible".

What am I doing wrong, or where could the error be?

Thank you for your help!

Is there a way to support you? e.g. via PayPal?

Greetings from Germany

Thomas

**Comment by flobz** [comment]
Hello,
You can use "-l 0.0.0.0" to listen on any IP address.
Maybe you have a firewall ? 

Also you can try to start the program with the "--debug" parameter and retry the request.
You may find something useful in the log.

> Is there a way to support you? e.g. via PayPal?

Yeah there is a [link](https://www.paypal.com/donate?hosted_button_id=SM652WPXFNCXS)  in the README file,
