### ISSUE TITLE
Wakeup command not works anymore

### ISSUE THREAD

**Issue by vineethktpla** [flobz/psa_car_controller#801]
Wakeup command doesnt work anymore. 
There is no changes even after executing the command. 

**To Reproduce**
1. what command did you use: http://localhost:5000/wakeup/vin
2. when the bug append ? : Since a month
3. Does it persist after restarting the program? : Yes
4. Does it persist after recreate config by going to http://server_address:port/config? : Yes

**Environment (please complete the following information):**
 - OS: Home assistant
 - Brand and model of car : Peugeot e-2008
 

**Additional context**
Battery percentage not updating in psa-car controller when car put in to charge (not even every 15 minutes).
But when I refresh the charging status from mypeugeot app, the percentage updates almost immediately.
I tried wakeup with this command, but no change detected by the app.

**Comment by gernot-h** [comment]
I had exactly the same issue, wakeup didn't work and charging progress was not shown (which also means limiting charge to a certain threshold didn't work). After reading #797, I installed from scratch including OAuth dance and now everything works again. Perhaps it's somehow connected to the Stellantis backend issue described in #791 and this requires re-authentication somehow?

**Comment by vineethktpla** [comment]
After reinstalling, the issue is fixed
