### ISSUE TITLE
API - How to get Average consumption / Electricity consumption / Trips

### ISSUE THREAD

**Issue by zazazouthecat** [flobz/psa_car_controller#802]
Possible to use API to get this informations in JSON Format ?
- Average consumption (for exemple http://localhost:5000/average_consumption/vehicleX ?)
- Electricity consumption (for exemple http://localhost:5000/electricity_consumption/vehicleX ?)
- Trips (for exemple http://localhost:5000/trips/vehicleX ?)

Thx.

**Comment by GewoonJaap** [comment]
I created a PR for your last point, the trips
https://github.com/flobz/psa_car_controller/pull/795
With that you could also calculate the (average) consumption

**Comment by GewoonJaap** [comment]
The trips endpoint and chargings endpoint just have been released :)

**Comment by vineethktpla** [comment]
> The trips endpoint and chargings endpoint just have been released :) https://github.com/flobz/psa_car_controller/blob/master/docs/psacc_api.md

I am getting the old data with these api end points. How to get the latest data ?
![image](https://github.com/flobz/psa_car_controller/assets/146456863/c92928ba-7286-4e96-9417-ce2c21ee57fa)

This is in home assistant adon

**Comment by GewoonJaap** [comment]
@vineethktpla Is there newer data available in the psa dashboard? Because the api returns the exact same data

**Comment by vineethktpla** [comment]
> @vineethktpla Is there newer data available in the psa dashboard? Because the api returns the exact same data

Yes there are. However the api returns the oldest entry
