### ISSUE TITLE
switch Preconditioning Connect with the new procedure

### ISSUE THREAD

**Issue by lanieuwe** [flobz/psa_car_controller#804]
Almost everything now works again in Home Assistant with the new procedure. However, I cannot get the "preconditioning" to work. When I enter the terminal:
curl -s "http://127.0.0.1:5000/preconditioning/xxxxxxxxxxxxxxxxx/1" then I get "true" back. But when I configure a switch in home assistant, it does not work. Code in home assistant: 
#script Configuration.yaml:
command_line: !include command_line.yaml

#script command_line.yaml:
-switch:
    name: e208_clim
    unique_id: e208_clim
    command_on: curl -s "http://127.0.0.1:5000/preconditioning/xxxxxxxxxxxxxxxxx/1"
    command_off: curl -s "http://127.0.0.1:5000/preconditioning/xxxxxxxxxxxxxxxxx/0"

What could be going on here? Does preconditioning work for you?

Thanks for contributing ideas!

**Comment by lanieuwe** [comment]
Now it works for me. I set it all up again from stretch.
I there maybe also  a solution for "Honk the horn" and "close the doors" ?

**Comment by flobz** [comment]
Please open an new issue if you can "Honk the horn" and "close the doors" in the smartphone app first.
