### ISSUE TITLE
refresh thread stop randomly

### ISSUE THREAD

**Issue by jlayec** [flobz/psa_car_controller#81]
**Describe the bug**
Sometime the refresh thread stop.
The program is still working perfectly with http://192.168.5.225:5000/get_vehicleinfo/vin or the dashboard
Usually I fix bugs myself but for this problem I need help to debug and to fix it !

**To Reproduce**
1. what command did you use
`python3 server.py -l 0.0.0.0 --remote-disable --record --refresh 5 --debug DEBUG`
2. when the bug append ?
sometimes. I observed it several times. not same period.
3. Does it persist after restarting the program? 
not applicable

**Config file**
not applicable

**Environment (please complete the following information):**
 - OS: [e.g. Windows] : Debian GNU/Linux 10 (buster)
 - Android app Version [e.g. 26.0] : not applicable, but com.psa.mym.mypeugeot_1.27.apk
 - Brand and model of car : not applicable, but SUV 3008
 - Application version (commit number, branch) : not applicable, I ve seen this issue with several branched : currently using release c2ecbde3d0937c0498cae8231f967dcd7dfc8653

**Additional context**

```
root@9250b546e088:~/psa_car_controller# ps -aef
UID        PID  PPID  C STIME TTY          TIME CMD
root     17358     0  0 Apr13 ?        00:01:29 python3 server.py -l 0.0.0.0 --remote-disable --record --refresh 5 --debug DEBUG

root@9250b546e088:~/psa_car_controller# ps -T -f -p 17358
UID        PID  SPID  PPID  C STIME TTY          TIME CMD
root     17358 17358     0  0 Apr13 ?        00:00:04 python3 server.py -l 0.0.0.0 --remote-disable --record --refresh 5 --debug DEBUG
root     17358 17456     0  0 Apr13 ?        00:01:00 python3 server.py -l 0.0.0.0 --remote-disable --record --refresh 5 --debug DEBUG
root     17358 28619     0  0 17:34 ?        00:00:00 python3 server.py -l 0.0.0.0 --remote-disable --record --refresh 5 --debug DEBUG
```

restart the daemon
`python3 server.py -l 0.0.0.0 --remote-disable --record --refresh 5 --debug DEBUG`

root@9250b546e088:~/psa_car_controller# ps -aef
```
UID        PID  PPID  C STIME TTY          TIME CMD
root     28631 28583 16 17:36 pts/0    00:00:07 python3 server.py -l 0.0.0.0 --remote-disable --record --refresh 5 --debug DEBUG

root@9250b546e088:~/psa_car_controller# ps -T -f -p 28631
UID        PID  SPID  PPID  C STIME TTY          TIME CMD
root     28631 28631 28583  4 17:36 pts/0    00:00:03 python3 server.py -l 0.0.0.0 --remote-disable --record --refresh 5 --debug DEBUG
root     28631 28726 28583  0 17:37 pts/0    00:00:00 python3 server.py -l 0.0.0.0 --remote-disable --record --refresh 5 --debug DEBUG
root     28631 28728 28583  6 17:37 pts/0    00:00:03 python3 server.py -l 0.0.0.0 --remote-disable --record --refresh 5 --debug DEBUG
root     28631 28734 28583  0 17:38 pts/0    00:00:00 python3 server.py -l 0.0.0.0 --remote-disable --record --refresh 5 --debug DEBUG
```

we can observe that we have 1 more thread.

How we can debug thread ? and then fix it :)

**Comment by flobz** [comment]
Maybe an error appear and isn't catch, add this code at the end of server.py
```
t2.join()
exit(1)
```
like this the program wil stop when the thread stop. You will be able to see what happen before the program stop. I have no better idea.

**Comment by jlayec** [comment]
Thanks ! I workedaround my code with additional debugs and the following code (don't wanna stop the program)

```
    t2.join()
    logger.debug("********************t2 thread died #1********************")
    t2 = Thread(target=web.app.myp.refresh_vehicle_info)
    t2.setDaemon(True)
    t2.start()

    t2.join()
    logger.debug("********************t2 thread died #2********************")
    t2 = Thread(target=web.app.myp.refresh_vehicle_info)
    t2.setDaemon(True)
    t2.start()

    t2.join()
    logger.debug("********************t2 thread died #3********************")
    t2 = Thread(target=web.app.myp.refresh_vehicle_info)
    t2.setDaemon(True)
    t2.start()
```

**Comment by jlayec** [comment]
Was about to close it after weeks without any issues but confirmed:

```
activity.log.1:2021-05-17 06:08:29,460 :: DEBUG :: ********************t2 thread died #1********************
activity.log:2021-05-24 16:46:42,238 :: DEBUG :: ********************t2 thread died #2********************
activity.log:2021-05-24 16:51:43,050 :: DEBUG :: ********************t2 thread died #3********************
```

I remember that on the 24th of May i was not able to use the MyPeugeot app on mobile phone. I assume this issue occurs when PSA servers are not available. Will investigate / simulate the issue.

**Comment by flobz** [comment]
All exeption are catch now so the thread should never died (in develop branch for now).
