### ISSUE TITLE
error "app_decoder.py", line 91

### ISSUE THREAD

**Issue by riddik14** [flobz/psa_car_controller#82]
(.env) psa_remote@debian-gnu-linux-vm:/usr/local/src/psa_car_controller$ python3 app_decoder.py ~/mypeugeot_1.29.apk
  File "app_decoder.py", line 91
    client_email = input(f"{BRAND[package_name]['app_name']} email: ")
                                                                    ^
SyntaxError: invalid syntax

i have try with 1.29 1.28 1.27 version

**Comment by xammmue** [comment]
The APP version shouldn't make a difference here as it's the code itself triggering the error.

The code throwing the SyntaxError requires Python >= 3.6, can you check what your version is and update if it is below 3.6?
