### ISSUE TITLE
Edit DB

### ISSUE THREAD

**Issue by CWfFO** [flobz/psa_car_controller#83]
Hi,
is there a way to edit the db?
I have a location inside which is near to Nigeria..... :(

KR
Christian

**Comment by flobz** [comment]
Hello,
yes you can. It's and sqlite database, look at the position table.

**Comment by CWfFO** [comment]
Thanks!

**Comment by CWfFO** [comment]
After i deleted one entry it stoped to record anything in the db. Permissions for the file are still the same. Old tracks i can see. Any clue?

**Comment by flobz** [comment]
maybe related to #50 ?

**Comment by CWfFO** [comment]
Strange thing: 
Charging is recorded, trips not. 
Even not if i restore the old db. 
Process is started with -r option

**Comment by CWfFO** [comment]
Yes, could be #50 
So the only possiblity is waiting? Bug on PSA side?

**Comment by xammmue** [comment]
Yes, we can only wait.
When requesting the position from the PSA API it stays the same, even though other data as SoC are updated.
