### ISSUE TITLE
How to send live data to abrp from home assistant ?

### ISSUE THREAD

**Issue by vineethktpla** [flobz/psa_car_controller#841]
I have the api- key from abrp but wondering how to send data to abrp with this key.
how can i access http://localhost:5000/abrp?token=YOURTOKEN from home assistant ?

**Comment by jove01** [comment]
You can put it direct into a browser. Perhaps you do it with your IP.
I didnot understand the next steps. Are they only to control?
And did not see, how data send to ABRP. I see their nothing.

**Comment by vineethktpla** [comment]
> try that, it's working for me
> 
> ![image](https://private-user-images.githubusercontent.com/30299307/321146364-e3e002c2-a873-4cb0-9e51-a0aaa2acc0e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MzU5MTAsIm5iZiI6MTcxMjczNTYxMCwicGF0aCI6Ii8zMDI5OTMwNy8zMjExNDYzNjQtZTNlMDAyYzItYTg3My00Y2IwLTllNTEtYTBhYWEyYWNjMGUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDA3NTMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxZTBjNmM4ZDdmN2I0NThmOTlkODhmMjgxZjIyODVkNmYwNTI3MTc4ZDY3NDVkODgzOTkxYTEzOWYwZTJlYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vOBMMJsNRT6dSAVKeJ9yN2LNwnV5jKUtuci-Hr7Fy8M)

This Worked for me !!
Thankyou for the help

**Comment by vineethktpla** [comment]
Fixed. Closing !!
