### ISSUE TITLE
ERROR :: No token provided

### ISSUE THREAD

**Issue by CWfFO** [flobz/psa_car_controller#85]
Hi,
i installed the latest files and now i get a lot of this errors in activity.log: ERROR :: No token provided
1:    what command did you use:  python3 server.py -f test.json -c charge_config.json -r -l 192.168.xx.yy
2:   when the bug append ?: after some seconds i have started and then maybe every 40 seconds
3:   Does it persist after restarting the program?: yes

    OS: [e.g. Windows] Raspian
    Android app Version [e.g. 26.0]: 1.27.1
    Brand and model of car: Opel Corsa-e
    Application version (commit number, branch): latest

KR
Christian

**Comment by CWfFO** [comment]
The strange thing is it seems to get some data. I receive the batterylevel ...
But this error is filling up the log file.... and i don't know what's the reason. In prior versions i got it from time to time but not every ~30-60 seconds

**Comment by flobz** [comment]
it means that you doesn't have an abrp token so it's not a big deal. I will change the message level to debug.

**Comment by CWfFO** [comment]
Thanks!

**Comment by flobz** [comment]
fix by 656147c
