### ISSUE TITLE
SoH invalid or is it reliable ?

### ISSUE THREAD

**Issue by vineethktpla** [flobz/psa_car_controller#854]
Im tracking my car's SoH through home assistant using psa car controller provided api. It was showing 95% till today, but all of a sudden now it's reading 100%.
So my question is how reliable this data is. I hope it's coming from car's ECU
Psa car controller also shows 100 % from yesterday 

![Screenshot_20240415-201846](https://github.com/flobz/psa_car_controller/assets/146456863/ae8a367c-9e80-4ff1-95f3-9987d3d64910)

**Comment by vineethktpla** [comment]
Now from today morning, it reset back to 95%

**Comment by Waxolunist** [comment]
Had the same. It's lower in winter than in summer because the capacity is a bit higher when it's warm.

**Comment by PeterGpp** [comment]
Is it reliable at all? 
Mine shows 24%, lately 23%, but the car's only 1 year old, and capacity seems to be ok ...

**Comment by vineethktpla** [comment]
> Is it reliable at all? Mine shows 24%, lately 23%, but the car's only 1 year old, and capacity seems to be ok ...

Weird that it shows 24%

**Comment by xplore93** [comment]
In my case, with Opel Astra GSe (PHEV), I have this data (from `/get_vehicleinfo/VIN`):
```json
    "energy": [
        {
            "updated_at": "2024-05-08 21:26:08+00:00",
            "autonomy": 44,
            "battery": {
                "capacity": null,
                "health": {
                    "capacity": 100,
                    "resistance": 31
                }
            },
            "charging": {
                "charging_mode": "No",
                "charging_rate": 0,
                "next_delayed_time": "PT0S",
                "plugged": false,
                "remaining_time": null,
                "status": "Disconnected"
            },
            "consumption": null,
            "level": 86,
            "residual": null,
            "type": "Electric"
        },
        {
            "updated_at": "2024-05-08 21:27:00+00:00",
            "autonomy": 640,
            "battery": null,
            "charging": null,
            "consumption": 0,
            "level": 100,
            "residual": null,
            "type": "Fuel"
        }
    ],
```

As you can see, the **energy.battery.resistance** is 31, this is the value I see as Battery SOH in Control tab and in `/battery/soh/VIN` request. 
It seems that the real SOH should be **energy.battery.capacity**, as it is 100 (new vehicle).
Not sure what structure have electric vehicles and other PHEV vehicles.
