### ISSUE TITLE
Value of 'x' is not the name of a column in 'data_frame'. Expected one of [] but received: date

### ISSUE THREAD

**Issue by MCDevel0per** [flobz/psa_car_controller#86]
If I record the position of my vehicle, the server can´t show them in the dashboard.

psa_car_controller-master\web\figures.py", line 98, in get_figures
    consumption_fig = px.line(consumption_df, x="date", y="consumption", title='Consumption of the car')

**Comment by flobz** [comment]
Close as it doesn't follow the bug template
