### ISSUE TITLE
Battery SOH

### ISSUE THREAD

**Issue by jvberlo** [flobz/psa_car_controller#867]
**Describe the bug**
Is it possible to add Battery SOH (state of health) as a sensor?
Picture below is for a Corsa-E
<img width="383" alt="image" src="https://github.com/flobz/psa_car_controller/assets/62310637/c41cd59b-abb4-467a-a4f2-d6e8b141ebf1">

Would be great to monitor the life expectancy of the battery

**Comment by mdkeil** [comment]
You can easily make a sensor with HA.

https://github.com/flobz/psa_car_controller/blob/master/docs/psacc_api.md

No. 15 

```
Get battery SOH
http://localhost:5000/battery/soh/YOURVIN
```

**Comment by zazazouthecat** [comment]
Here example sensor
https://github.com/flobz/psa_car_controller/discussions/690#discussioncomment-8706290
