### ISSUE TITLE
Should psacc work without any suscription to myopel app?

### ISSUE THREAD

**Issue by saliendodelaratrace** [flobz/psa_car_controller#870]
Since Two weeks ago, my suscription to myopel app is out of date. This means that i cannot even check the state of battery from myopel app.
Since that moment, i have no data in my home assistant from psacc.
Is that normal?
should i have to suscribe for the data in home assistant to appear again?
Thanks in advance.

**Comment by Jordan87** [comment]
Of course, without subscription it will not work. 
You are using Peugeot's cloud, not direct connection to car.

**Comment by saliendodelaratrace** [comment]
i only got 6 months for free when i bought a car. is that normal?

**Comment by Jordan87** [comment]
It depends when your car was ordered.
![image](https://github.com/flobz/psa_car_controller/assets/10414918/ff9e055b-fbf2-4f22-977e-6bd829177ee5)
My car was ordered is October 2022 but delivered in October 2023 and I also have it for free only for 6 months but my dealer have promised that if it will stop to work they will take care about it to deliver 3year service for Nav and Speedcams, probably I will have to pay on my own for "e-remote control" after 6 months.

**Comment by Bushrider** [comment]
Stellantis are thieves I bought my e208 in 2020 and have 10 years free services. You should complain about this situation, unbelievable to pay for such basics and essentials options for electric vehicles.

**Comment by vineethktpla** [comment]
my peugeot app shows I have subscription for 10 years ( till 2033). 
22 model e-2008. Is this issue for newer models ?

**Comment by Jordan87** [comment]
This 6months free period is maybe affecting only hybrids, maybe full electric cars have still 10 years.

**Comment by saliendodelaratrace** [comment]
> This 6months free period is maybe affecting only hybrids, maybe full electric cars have still 10 years.

My Opel corsa is full electric

**Comment by Jordan87** [comment]
Some cars are able to communicate with charging station via 15118 protocol but of course only when car is connected to it.

**Comment by saliendodelaratrace** [comment]
I can get information of the car in Home Assistant through eevee app integration each time the car moves but psacc is not able to get it...

**Comment by Jordan87** [comment]
This means you have still have valid subscription from peugeot and only psacc is having issue.

**Comment by saliendodelaratrace** [comment]
My subscription is over since 20/04/2024
I have data in psacc until that exactly day ...
In fact, even in myopel app i cant get soc for example since that day 
🤷🏻‍♂️
