### ISSUE TITLE
On Website only no Summary 

### ISSUE THREAD

**Issue by Michel83** [flobz/psa_car_controller#875]
Hello,

i have the problem that i have no data only in the summary. Trips, Charge, Map all available.

I run it on a Synology in a docker.

Anyone a idear what is the probem or what i have made wrong 

![image](https://github.com/flobz/psa_car_controller/assets/36561525/436726d3-84d7-4bb8-b2af-d6e9eded5b68)
![image](https://github.com/flobz/psa_car_controller/assets/36561525/708968ab-7610-46f7-a24c-49c0bf2efdd9)
![image](https://github.com/flobz/psa_car_controller/assets/36561525/9f666753-f955-4503-8f93-538dcac649ac)
![image](https://github.com/flobz/psa_car_controller/assets/36561525/9de86d01-c1d4-4a6c-9685-8791676cbe5b)

**Comment by zazazouthecat** [comment]
Hello,
you need to configure your config.ini file and add electricitry price.
when you did it, data will be updated

**Comment by Michel83** [comment]
It work, i made two longer trips and after this i can see all diagrams. 

Thanks
