### ISSUE TITLE
Homebridge

### ISSUE THREAD

**Issue by ballance1032** [flobz/psa_car_controller#876]
**Describe the bug**

**To Reproduce**
1. what command did you use
2. when the bug append ?
3. Does it persist after restarting the program? 
4. Does it persist after recreate config by going to http://server_address:port/config? 

**Config file**
Give the anonymize content of the config file

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
 - Brand and model of car
 - Application version (commit number, branch or tag)
 - Log from http://server_address:port/log and browser console log

**Additional context**

Is there anyway to get this working in homebridge?

**Comment by flobz** [comment]
Close as it doesn't follow the bug template
