### ISSUE TITLE
APK decode fail

### ISSUE THREAD

**Issue by fn87** [flobz/psa_car_controller#88]
I get this during the APK decode for the token. Any idea on what I need to do to solve it?

`
~/psa/psa_car_controller-master$ python3 app_decoder.py ds2.apk
APK loading...
Requested API level 29 is larger than maximum we have, returning API level 28 instead.
APK loaded !
MyDS email: xxx@yyy.com
MyDS password: XXXXXXX
What is your country code ? (ex: FR, GB, DE, ES...)
SE
Traceback (most recent call last):
  File "app_decoder.py", line 110, in <module>
    token = res.json()["accessToken"]
KeyError: 'accessToken'
HOST_BRANDID : https://id-dcr.citroen.com/mobile-services sitecode: AC_SE_ESP
{"session":"SESSION","returnCode":"NEED_AUTHORIZATION","token":"TOKEN"}
'

**Comment by moulagaufre** [comment]
I have the same error, when I enter a country code that is not mine (I'm FR and works in FR, and I get this for any other country code)

**Comment by fn87** [comment]
I get this for all country codes including the one I should be using. Are there any way of verify what code I should use?

**Comment by flobz** [comment]
You seems to be the first DS user, there was a mistake in the code.
With 7b34046 it should be fixed.

**Comment by flobz** [comment]
Your car model isn't registered in the app, please open an issue [here](https://github.com/flobz/psa_car_controller/issues/new?assignees=&labels=Car_model&template=can-t-get-car-model.md&title=%5BNew+Car+model%5D+my+model)

**Comment by fn87** [comment]
Verified, thanks.
