### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '../cars.json'

### ISSUE THREAD

**Issue by Flodu31** [flobz/psa_car_controller#90]
**Describe the bug**
I tried to update to the last version pushed, but when I try to do python3 app_decoder.py ~/mypeugeot_1.29.apk (it worked before) I've an error message:

```
PermissionError: [Errno 13] Permission denied: '../cars.json'
```

I didn't have any cars.json file on my server.

**To Reproduce**
1. what command did you use
python3 app_decoder.py ~/mypeugeot_1.29.apk
2. when the bug append ?
3. with the last version, it worked with abrp version
3. Does it persist after restarting the program? 
4. yes

**Config file**
Give the anonymize content of the config file

**Environment (please complete the following information):**
 - OS: [e.g. Windows]: Pi
 - Android app Version [e.g. 26.0]: 29.1
 - Brand and model of car: Peugeot e2008
 - Application version (commit number, branch) 

**Additional context**

**Comment by flobz** [comment]
Hello,
It's not a problem from the app. 
You probably don't have to the permissions to write in the directory. .
