### ISSUE TITLE
heads up eevee is going payed only

### ISSUE THREAD

**Issue by RMHogervorst** [flobz/psa_car_controller#937]
This is only partially related to PSA. 

I and others started using eevee ( app), because for reasons only known to stallantis, GPS and other things don't work otherwise for our cars.

I received an email that from Oct 1? Eevee will only allow payed accounts. It seems we have to find another way to force stallantis to send all information.

**Comment by R-dehaan** [comment]
Probably related to my issue #975

**Comment by RMHogervorst** [comment]
https://intercom.help/eevee-mobility/en/articles/9659645-introducing-our-pro-subscription-for-the-eevee-driver-app (explanation)
