### ISSUE TITLE
[New Car model] DS7 Crossback E-Tense 300 4x4

### ISSUE THREAD

**Issue by fn87** [flobz/psa_car_controller#96]
I have a "Can't get car model" error.
Information to add my car model to the app:
- Brand: DS
- Model: 7
- First ten letter of my VIN:  VR1J45GBUK
- Useable Electric capacity in kw: 13,2
- Fuel capacity in liter: 43

**Comment by flobz** [comment]
Ok it's added with 03dd06a.
Is your two vehicles are registred in the same mypeugeot account ? 
Because if it does, it might not work well with my app because it's not fully compatible with more than one vehicle.
