### ISSUE TITLE
Last location is only updated at the end.

### ISSUE THREAD

**Issue by R-dehaan** [flobz/psa_car_controller#975]
**Describe the bug**
Last position is not updateded anymore, only last location is shown.

**To Reproduce**
1. what command did you use
None
2. when the bug append ?
Yesterday
3. Does it persist after restarting the program? 
Yes
4. Does it persist after recreate config by going to http://server_address:port/config? 
Yes

**Config file**
Nothing special, everything updates fine except last location data.

**Additional context**
Initially it was working by using EEVEE which enabled for some reason regular updates of the latest location.
See issue: [https://github.com/flobz/psa_car_controller/issues/50]

However as that is now a paid subscription I don't know due to this the updates location stopped working?

**Comment by zazazouthecat** [comment]
Hello,
try to rearm your OTP configuration.

**Comment by R-dehaan** [comment]
Tried that but not working

**Comment by flobz** [comment]
duplicate #956
